In [623]:
import pandas as pd
import numpy as np

In [624]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [625]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Hackathon/Data_Train.csv')
df

,ID,Asst_Reg,GGGrade,Experience,Validation,Yearly Income,Home Status,Unpaid 2 years,Already Defaulted,Designation,...,File Status,State,Account Open,Total Unpaid CL,Duration,Unpaid Amount,Reason,Claim Type,Due Fee,Loan/No Loan
0,95074,421802,II,>10yrs,Vfied,633600.00,MOR??AGE,0,0,GLENDALE NISSAN,...,fully paid,California,17,58598.0,3 years,31216.05,debt consolidation,I,0.0,0
1,134131,3964312,IV,7yrs,Source Verified,85483.20,REN?,0,0,Business Teacher,...,whole,NC,15,18924.0,5 years,11660.49,debt consolidation,I,0.0,0
2,92602,4247560,III,<1yr,Source Verified,79200.00,REN?,0,0,driver,...,whole,Florida,7,15604.0,5 years,5637.87,major purchase,I,0.0,0
3,22591,197179,III,<1yr,Vfied,61600.00,REN?,0,0,AvePoint,...,fully paid,NewJersey,9,22410.0,3 years,15607.17,major purchase,I,0.0,1
4,125060,4646684,V,2yrs,Source Verified,68053.92,REN?,0,0,Lead Tester,...,fully paid,LA,10,36022.0,5 years,27472.86,debt consolidation,I,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87495,120884,4535984,II,>10yrs,Not Vfied,75680.00,REN?,0,0,Engineer Support II,...,whole,MI,12,32702.0,3 years,10012.05,debt consolidation,I,0.0,0
87496,33259,2624710,IV,3yrs,Source Verified,90423.52,REN?,0,0,Dental Hygienist,...,whole,MA,23,32204.0,5 years,24921.54,debt consolidation,I,0.0,0
87497,102153,5966919,II,>10yrs,Source Verified,91520.00,MOR??AGE,0,0,Interface Coordinator,...,fully paid,CT,8,29050.0,3 years,14517.90,debt consolidation,I,0.0,0
87498,115343,2630667,III,1yrs,Source Verified,61600.00,MOR??AGE,0,0,PARTS CLERK,...,whole,PA,11,24900.0,3 years,8454.24,debt consolidation,I,0.0,0
87499,104968,6637289,III,2yrs,Vfied,NaN,REN?,0,0,Outside sales rep,...,whole,California,7,21746.0,5 years,8717.58,debt consolidation,I,0.0,0

In [626]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87500 entries, 0 to 87499
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   87500 non-null  int64
 1   Asst_Reg             87500 non-null  int64
 2   GGGrade              87500 non-null  object
 3   Experience           87500 non-null  object
 4   Validation           87500 non-null  object
 5   Yearly Income        81925 non-null  float64
 6   Home Status          87500 non-null  object
 7   Unpaid 2 years       87500 non-null  int64
 8   Already Defaulted    87500 non-null  int64
 9   Designation          86086 non-null  object
 10  Debt to Income       84011 non-null  float64
 11  Postal Code          86111 non-null  float64
 12  Lend Amount          87500 non-null  float64
 13  Deprecatory Records  87500 non-null  int64
 14  Interest Charged     87500 non-null  float64
 15  Usage Rate           87500 non-null  float64
 16  Inquiries            87500 non-null  int64
 17  Present Balance      87500 non-null  float64
 18  Gross Collection     87500 non-null  float64
 19  Sub GGGrade          87500 non-null  int64
 20  File Status          87500 non-null  object
 21  State                87500 non-null  object
 22  Account Open         87500 non-null  int64
 23  Total Unpaid CL      83314 non-null  float64
 24  Duration             87500 non-null  object
 25  Unpaid Amount        82648 non-null  float64
 26  Reason               87500 non-null  object
 27  Claim Type           87500 non-null  object
 28  Due Fee              87500 non-null  float64
 29  Loan/No Loan         87500 non-null  int64
dtypes: float64(11), int64(9), object(10)
memory usage: 20.0+ MB

In [627]:
df.drop('ID',axis=1,inplace=True)

In [628]:
df['Postal Code'] = df['Postal Code'].astype("object")

In [629]:
df.isnull().sum()

Asst_Reg                  0
GGGrade                   0
Experience                0
Validation                0
Yearly Income          5575
Home Status               0
Unpaid 2 years            0
Already Defaulted         0
Designation            1414
Debt to Income         3489
Postal Code            1389
Lend Amount               0
Deprecatory Records       0
Interest Charged          0
Usage Rate                0
Inquiries                 0
Present Balance           0
Gross Collection          0
Sub GGGrade               0
File Status               0
State                     0
Account Open              0
Total Unpaid CL        4186
Duration                  0
Unpaid Amount          4852
Reason                    0
Claim Type                0
Due Fee                   0
Loan/No Loan              0
dtype: int64

In [630]:
df['Loan/No Loan'].value_counts()

0    70988
1    16512
Name: Loan/No Loan, dtype: int64

In [631]:
df['Loan/No Loan'].value_counts(normalize=True)

0    0.811291
1    0.188709
Name: Loan/No Loan, dtype: float64

In [632]:
df['Yearly Income'].fillna(df['Yearly Income'].mean(),inplace=True)
df['Debt to Income'].fillna(df['Debt to Income'].mean(),inplace=True)
df['Total Unpaid CL'].fillna(df['Total Unpaid CL'].mean(),inplace=True)
df['Unpaid Amount'].fillna(df['Unpaid Amount'].mean(),inplace=True)

df['Postal Code'].fillna(df['Postal Code'].value_counts().index[0],inplace=True)
df['Designation'].fillna(df['Designation'].value_counts().index[0],inplace=True)

In [633]:
df.isnull().sum()

Asst_Reg               0
GGGrade                0
Experience             0
Validation             0
Yearly Income          0
Home Status            0
Unpaid 2 years         0
Already Defaulted      0
Designation            0
Debt to Income         0
Postal Code            0
Lend Amount            0
Deprecatory Records    0
Interest Charged       0
Usage Rate             0
Inquiries              0
Present Balance        0
Gross Collection       0
Sub GGGrade            0
File Status            0
State                  0
Account Open           0
Total Unpaid CL        0
Duration               0
Unpaid Amount          0
Reason                 0
Claim Type             0
Due Fee                0
Loan/No Loan           0
dtype: int64

In [634]:
df.dropna(inplace=True)
df

,Asst_Reg,GGGrade,Experience,Validation,Yearly Income,Home Status,Unpaid 2 years,Already Defaulted,Designation,Debt to Income,...,File Status,State,Account Open,Total Unpaid CL,Duration,Unpaid Amount,Reason,Claim Type,Due Fee,Loan/No Loan
0,421802,II,>10yrs,Vfied,633600.00000,MOR??AGE,0,0,GLENDALE NISSAN,12.5496,...,fully paid,California,17,58598.0,3 years,31216.05,debt consolidation,I,0.0,0
1,3964312,IV,7yrs,Source Verified,85483.20000,REN?,0,0,Business Teacher,9.0048,...,whole,NC,15,18924.0,5 years,11660.49,debt consolidation,I,0.0,0
2,4247560,III,<1yr,Source Verified,79200.00000,REN?,0,0,driver,24.9144,...,whole,Florida,7,15604.0,5 years,5637.87,major purchase,I,0.0,0
3,197179,III,<1yr,Vfied,61600.00000,REN?,0,0,AvePoint,16.5816,...,fully paid,NewJersey,9,22410.0,3 years,15607.17,major purchase,I,0.0,1
4,4646684,V,2yrs,Source Verified,68053.92000,REN?,0,0,Lead Tester,40.0512,...,fully paid,LA,10,36022.0,5 years,27472.86,debt consolidation,I,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87495,4535984,II,>10yrs,Not Vfied,75680.00000,REN?,0,0,Engineer Support II,19.3200,...,whole,MI,12,32702.0,3 years,10012.05,debt consolidation,I,0.0,0
87496,2624710,IV,3yrs,Source Verified,90423.52000,REN?,0,0,Dental Hygienist,48.8208,...,whole,MA,23,32204.0,5 years,24921.54,debt consolidation,I,0.0,0
87497,5966919,II,>10yrs,Source Verified,91520.00000,MOR??AGE,0,0,Interface Coordinator,7.7952,...,fully paid,CT,8,29050.0,3 years,14517.90,debt consolidation,I,0.0,0
87498,2630667,III,1yrs,Source Verified,61600.00000,MOR??AGE,0,0,PARTS CLERK,8.2992,...,whole,PA,11,24900.0,3 years,8454.24,debt consolidation,I,0.0,0
87499,6637289,III,2yrs,Vfied,134859.62978,REN?,0,0,Outside sales rep,15.1872,...,whole,California,7,21746.0,5 years,8717.58,debt consolidation,I,0.0,0

In [635]:
# df['Asst_Reg'] = df['Asst_Reg'].astype("object")
df['Unpaid 2 years'] = df['Unpaid 2 years'].astype("object")
# df['Already Defaulted'] = df['Already Defaulted'].astype("object")
# df['Postal Code'] = df['Postal Code'].astype("object")
# df['Deprecatory Records'] = df['Deprecatory Records'].astype("object")
#df['Inquiries'] = df['Inquiries'].astype("object")
# df['Sub GGGrade'] = df['Sub GGGrade'].astype("object")
# #Account Open

In [636]:
#df = df.drop('Asst_Reg', axis=1)
# df = df.drop('Sub GGGrade', axis=1)
# df = df.drop('Postal Code', axis=1)
# #Designation
# #Postal Code
# #Sub GGGrade
# #State
# #Account Open

In [637]:
# df['GGGrade'].replace('VII',7,inplace=True)
# df['GGGrade'].replace('VI',6,inplace=True)
# df['GGGrade'].replace('V',5,inplace=True)
# df['GGGrade'].replace('IV',4,inplace=True)
# df['GGGrade'].replace('III',3,inplace=True)
# df['GGGrade'].replace('II',2,inplace=True)
# df['GGGrade'].replace('I',1,inplace=True)
# df['GGGrade'] = df['GGGrade'].astype(int)

In [638]:
# df['Experience'].replace('<1yr',0.3,inplace=True)
# df['Experience'].replace('1yrs',1,inplace=True)
# df['Experience'].replace('2yrs',2,inplace=True)
# df['Experience'].replace('3yrs',3,inplace=True)
# df['Experience'].replace('4yrs',4,inplace=True)
# df['Experience'].replace('5yrs',5,inplace=True)
# df['Experience'].replace('6yrs',6,inplace=True)
# df['Experience'].replace('7yrs',7,inplace=True)
# df['Experience'].replace('8yrs',8,inplace=True)
# df['Experience'].replace('9yrs',9,inplace=True)
# df['Experience'].replace('>10yrs',12,inplace=True)
# df['Experience'] = df['Experience'].astype(int)

In [639]:
# df['Validation'].replace('Source Verified','Vfied',inplace=True)

In [640]:
for tag in df.columns[df.dtypes == "object"]:
  print("----",tag,"---")
  print(df[tag].value_counts(normalize=True))
  print("\n\n")

---- GGGrade ---
II     0.285326
III    0.281737
I      0.161954
IV     0.158480
V      0.081760
VI     0.025051
VII    0.005691
Name: GGGrade, dtype: float64



---- Experience ---
>10yrs    0.352560
2yrs      0.092160
3yrs      0.084000
<1yr      0.082389
1yrs      0.066891
5yrs      0.064263
4yrs      0.060846
7yrs      0.054423
8yrs      0.052617
6yrs      0.048629
9yrs      0.041223
Name: Experience, dtype: float64



---- Validation ---
Source Verified    0.394331
Vfied              0.304480
Not Vfied          0.301189
Name: Validation, dtype: float64



---- Home Status ---
MOR??AGE    0.504686
REN?        0.399017
OWN         0.096183
OTHER       0.000069
NONE        0.000046
Name: Home Status, dtype: float64



---- Unpaid 2 years ---
0     0.797337
1     0.132617
2     0.041806
3     0.014560
4     0.006457
5     0.003143
6     0.001783
7     0.000766
8     0.000491
9     0.000297
10    0.000251
12    0.000171
11    0.000149
18    0.000046
14    0.000046
13    0.000034
16    0.000023
15    0.000023
Name: Unpaid 2 years, dtype: float64



---- Designation ---
School Teacher                 0.034274
Super Lead                     0.015109
Nurse                          0.008491
RN                             0.007383
Owner                          0.007120
                                 ...
B.R. Amon and Sons             0.000011
Medical record technician      0.000011
Executive Field Assistant      0.000011
Speech language pathologist    0.000011
Outside sales rep              0.000011
Name: Designation, Length: 40354, dtype: float64



---- File Status ---
whole         0.529143
fully paid    0.470857
Name: File Status, dtype: float64



---- State ---
California    0.144286
Newyork       0.082400
TX            0.081486
Florida       0.066434
IL            0.040023
NewJersey     0.037177
PA            0.036217
Ohio          0.033931
GA            0.033417
VA            0.029086
NC            0.028800
MI            0.025749
Maryland      0.023691
AZ            0.023520
MA            0.023143
CO            0.021509
WA            0.021257
MN            0.019120
IN            0.016377
MO            0.016114
TN            0.015554
CT            0.015143
NV            0.013394
AL            0.013029
WI            0.012754
OR            0.012000
LA            0.011646
SC            0.011486
KY            0.009383
KS            0.009360
OK            0.008754
AR            0.007429
UT            0.007303
NM            0.005680
HI            0.005314
NH            0.004880
MS            0.004686
WV            0.004434
RI            0.004251
MT            0.002960
DE            0.002720
DC            0.002686
AK            0.002526
WY            0.002126
SD            0.002069
VT            0.002034
NE            0.001531
ND            0.000571
ME            0.000560
Name: State, dtype: float64



---- Duration ---
3 years    0.686411
5 years    0.313589
Name: Duration, dtype: float64



---- Reason ---
debt  consolidation    0.600674
credit  card           0.241166
home  improvement      0.055840
other                  0.043131
major  purchase        0.017280
medical                0.009383
small  business        0.008583
car                    0.008114
moving                 0.005749
vacation               0.004846
house                  0.003554
wedding                0.001246
renewable  energy      0.000434
Name: Reason, dtype: float64



---- Claim Type ---
I    0.999474
J    0.000526
Name: Claim Type, dtype: float64

In [641]:
categorical_features_indices = np.where(df.dtypes == "object")[0]
categorical_features_indices

array([ 1,  2,  3,  5,  6,  8, 19, 20, 23, 25, 26])

In [642]:
from scipy.stats import chi2_contingency
for tag in df.columns[df.dtypes == "object"]:
  obs = pd.crosstab(df['Loan/No Loan'],df[tag])
  a = chi2_contingency(obs)
  print(tag,"------------",a[1])

GGGrade ------------ 2.144329159989683e-24
Experience ------------ 9.923109817794896e-18
Validation ------------ 7.901712747516952e-149
Home Status ------------ 5.073302694937398e-15
Unpaid 2 years ------------ 9.45472934215492e-14
Designation ------------ 2.032036187627349e-247
File Status ------------ 0.0
State ------------ 2.9414806201127534e-36
Duration ------------ 7.782945756987817e-199
Reason ------------ 4.229149735817299e-39
Claim Type ------------ 0.002046205766921692

In [643]:
# df = df.drop('File Status', axis=1)

In [644]:
# df = df.drop(['Designation','State'], axis=1)

In [645]:
X = df.drop('Loan/No Loan', axis=1)

y = df['Loan/No Loan']

In [646]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 87500 entries, 0 to 87499
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Asst_Reg             87500 non-null  int64
 1   GGGrade              87500 non-null  object
 2   Experience           87500 non-null  object
 3   Validation           87500 non-null  object
 4   Yearly Income        87500 non-null  float64
 5   Home Status          87500 non-null  object
 6   Unpaid 2 years       87500 non-null  object
 7   Already Defaulted    87500 non-null  int64
 8   Designation          87500 non-null  object
 9   Debt to Income       87500 non-null  float64
 10  Postal Code          87500 non-null  float64
 11  Lend Amount          87500 non-null  float64
 12  Deprecatory Records  87500 non-null  int64
 13  Interest Charged     87500 non-null  float64
 14  Usage Rate           87500 non-null  float64
 15  Inquiries            87500 non-null  int64
 16  Present Balance      87500 non-null  float64
 17  Gross Collection     87500 non-null  float64
 18  Sub GGGrade          87500 non-null  int64
 19  File Status          87500 non-null  object
 20  State                87500 non-null  object
 21  Account Open         87500 non-null  int64
 22  Total Unpaid CL      87500 non-null  float64
 23  Duration             87500 non-null  object
 24  Unpaid Amount        87500 non-null  float64
 25  Reason               87500 non-null  object
 26  Claim Type           87500 non-null  object
 27  Due Fee              87500 non-null  float64
dtypes: float64(11), int64(6), object(11)
memory usage: 19.4+ MB

In [647]:
##reduced F1
# X['Postal Code'] = X['Postal Code'].astype("object")
# X['Postal Code'].dtype

In [648]:
# #reduced F1
# tags = ['Postal Code']
# for tag in tags:
#   for i in range(X.shape[0]):
#     #print (i)
#     X[tag][i] = str(X[tag][i])

In [649]:
# X.drop('Postal Code',axis=1,inplace=True)

In [650]:
X.drop('Designation',axis=1,inplace=True)

In [651]:
X = pd.get_dummies(X,drop_first=True)

In [652]:
# tags = X.columns[categorical_features_indices]
# for tag in tags:
#   for i in range(X.shape[0]):
#     #print (i)
#     X[tag][i] = str(X[tag][i])

In [653]:
# for tag in X.columns[categorical_features_indices]:
#   X[tag] = X[tag].astype("category")

In [654]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 87500 entries, 0 to 87499
Columns: 119 entries, Asst_Reg to Claim Type_J
dtypes: float64(11), int64(6), uint8(102)
memory usage: 20.5 MB

In [655]:
# from imblearn.over_sampling import SMOTENC
# cat_indx =categorical_features_indices
# sm = SMOTENC(categorical_features= cat_indx, random_state=0, sampling_strategy = 0.25)
# X_train_res, y_train_res = sm.fit_resample(X, y)

In [656]:
# X = X_train_res.copy()
# y = y_train_res.copy()

In [657]:
X.columns = X.columns.str.replace(',', '_')

In [658]:
X.columns = X.columns.str.replace('<', 'l_')
X.columns = X.columns.str.replace('V', 'g_')

In [659]:
pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.7/dist-packages (0.90)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from xgboost) (1.4.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from xgboost) (1.21.6)

In [660]:
# from xgboost import XGBClassifier
# clf = XGBClassifier()
# model=clf.fit(X,y)

In [661]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Hackathon/Data_Test.csv')
df

,ID,Asst_Reg,GGGrade,Experience,Validation,Yearly Income,Home Status,Unpaid 2 years,Already Defaulted,Designation,...,Sub GGGrade,File Status,State,Account Open,Total Unpaid CL,Duration,Unpaid Amount,Reason,Claim Type,Due Fee
0,198980,1773284,II,2yrs,Source Verified,140800.00,OWN,0,0,processor,...,17,fully paid,California,23,33532.0,3 years,15755.94,major purchase,I,0.0
1,167688,5298273,II,>10yrs,Vfied,146080.00,MOR??AGE,0,0,Speech Language Pathologist,...,19,whole,Florida,17,149234.0,5 years,68237.55,debt consolidation,I,0.0
2,198768,189781,VI,>10yrs,Vfied,202222.24,MOR??AGE,0,0,Raytheon,...,37,whole,NM,15,70218.0,5 years,66272.76,debt consolidation,I,0.0
3,192564,1530906,II,>10yrs,Vfied,105600.00,MOR??AGE,1,0,Computer/Network Technician,...,19,fully paid,DE,18,79182.0,3 years,15595.20,credit card,I,0.0
4,151199,4410316,III,4yrs,Not Vfied,151360.00,MOR??AGE,0,0,NDE Tech,...,25,fully paid,Florida,7,13612.0,3 years,8850.96,debt consolidation,I,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37495,191405,5774816,IV,4yrs,Vfied,308000.00,MOR??AGE,1,0,Regional Manager,...,29,fully paid,California,19,132468.0,3 years,57683.43,debt consolidation,I,0.0
37496,164868,1423834,IV,8yrs,Source Verified,158400.00,MOR??AGE,0,0,Clinical Coordinator,...,28,fully paid,PA,14,51958.0,5 years,51395.76,credit card,I,0.0
37497,163156,1895531,V,>10yrs,Not Vfied,52800.00,OWN,0,0,administrative,...,33,fully paid,California,9,8466.0,3 years,2783.88,debt consolidation,I,0.0
37498,169610,2168910,VI,9yrs,Not Vfied,52800.00,OWN,5,0,ParaEducator,...,40,whole,TN,9,17264.0,3 years,NaN,home improvement,I,0.0
37499,175557,4140268,II,>10yrs,Source Verified,121440.00,MOR??AGE,0,0,School Teacher,...,19,fully paid,California,15,47310.0,3 years,29504.34,debt consolidation,I,0.0

In [662]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37500 entries, 0 to 37499
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   37500 non-null  int64
 1   Asst_Reg             37500 non-null  int64
 2   GGGrade              37500 non-null  object
 3   Experience           37500 non-null  object
 4   Validation           37500 non-null  object
 5   Yearly Income        35075 non-null  float64
 6   Home Status          37500 non-null  object
 7   Unpaid 2 years       37500 non-null  int64
 8   Already Defaulted    37500 non-null  int64
 9   Designation          36914 non-null  object
 10  Debt to Income       35989 non-null  float64
 11  Postal Code          36889 non-null  float64
 12  Lend Amount          37500 non-null  float64
 13  Deprecatory Records  37500 non-null  int64
 14  Interest Charged     37500 non-null  float64
 15  Usage Rate           37500 non-null  float64
 16  Inquiries            37500 non-null  int64
 17  Present Balance      37500 non-null  float64
 18  Gross Collection     37500 non-null  float64
 19  Sub GGGrade          37500 non-null  int64
 20  File Status          37500 non-null  object
 21  State                37500 non-null  object
 22  Account Open         37500 non-null  int64
 23  Total Unpaid CL      35686 non-null  float64
 24  Duration             37500 non-null  object
 25  Unpaid Amount        35431 non-null  float64
 26  Reason               37500 non-null  object
 27  Claim Type           37500 non-null  object
 28  Due Fee              37500 non-null  float64
dtypes: float64(11), int64(8), object(10)
memory usage: 8.3+ MB

In [663]:
df.isnull().sum()

ID                        0
Asst_Reg                  0
GGGrade                   0
Experience                0
Validation                0
Yearly Income          2425
Home Status               0
Unpaid 2 years            0
Already Defaulted         0
Designation             586
Debt to Income         1511
Postal Code             611
Lend Amount               0
Deprecatory Records       0
Interest Charged          0
Usage Rate                0
Inquiries                 0
Present Balance           0
Gross Collection          0
Sub GGGrade               0
File Status               0
State                     0
Account Open              0
Total Unpaid CL        1814
Duration                  0
Unpaid Amount          2069
Reason                    0
Claim Type                0
Due Fee                   0
dtype: int64

In [664]:
df['Postal Code'] = df['Postal Code'].astype("object")

In [665]:
df['Yearly Income'].fillna(df['Yearly Income'].mean(),inplace=True)
df['Debt to Income'].fillna(df['Debt to Income'].mean(),inplace=True)
df['Total Unpaid CL'].fillna(df['Total Unpaid CL'].mean(),inplace=True)
df['Unpaid Amount'].fillna(df['Unpaid Amount'].mean(),inplace=True)

df['Postal Code'].fillna(df['Postal Code'].value_counts().index[0],inplace=True)
df['Designation'].fillna(df['Designation'].value_counts().index[0],inplace=True)

In [666]:
df.isnull().sum()

ID                     0
Asst_Reg               0
GGGrade                0
Experience             0
Validation             0
Yearly Income          0
Home Status            0
Unpaid 2 years         0
Already Defaulted      0
Designation            0
Debt to Income         0
Postal Code            0
Lend Amount            0
Deprecatory Records    0
Interest Charged       0
Usage Rate             0
Inquiries              0
Present Balance        0
Gross Collection       0
Sub GGGrade            0
File Status            0
State                  0
Account Open           0
Total Unpaid CL        0
Duration               0
Unpaid Amount          0
Reason                 0
Claim Type             0
Due Fee                0
dtype: int64

In [667]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37500 entries, 0 to 37499
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   37500 non-null  int64
 1   Asst_Reg             37500 non-null  int64
 2   GGGrade              37500 non-null  object
 3   Experience           37500 non-null  object
 4   Validation           37500 non-null  object
 5   Yearly Income        37500 non-null  float64
 6   Home Status          37500 non-null  object
 7   Unpaid 2 years       37500 non-null  int64
 8   Already Defaulted    37500 non-null  int64
 9   Designation          37500 non-null  object
 10  Debt to Income       37500 non-null  float64
 11  Postal Code          37500 non-null  float64
 12  Lend Amount          37500 non-null  float64
 13  Deprecatory Records  37500 non-null  int64
 14  Interest Charged     37500 non-null  float64
 15  Usage Rate           37500 non-null  float64
 16  Inquiries            37500 non-null  int64
 17  Present Balance      37500 non-null  float64
 18  Gross Collection     37500 non-null  float64
 19  Sub GGGrade          37500 non-null  int64
 20  File Status          37500 non-null  object
 21  State                37500 non-null  object
 22  Account Open         37500 non-null  int64
 23  Total Unpaid CL      37500 non-null  float64
 24  Duration             37500 non-null  object
 25  Unpaid Amount        37500 non-null  float64
 26  Reason               37500 non-null  object
 27  Claim Type           37500 non-null  object
 28  Due Fee              37500 non-null  float64
dtypes: float64(11), int64(8), object(10)
memory usage: 8.3+ MB

In [668]:
# df['Asst_Reg'] = df['Asst_Reg'].astype("object")
df['Unpaid 2 years'] = df['Unpaid 2 years'].astype("object")
# df['Already Defaulted'] = df['Already Defaulted'].astype("object")
#df['Postal Code'] = df['Postal Code'].astype("object")
# df['Deprecatory Records'] = df['Deprecatory Records'].astype("object")
# df['Inquiries'] = df['Inquiries'].astype("object")
# df['Sub GGGrade'] = df['Sub GGGrade'].astype("object")
# #Account Open

# df = df.drop('Asst_Reg', axis=1)
# df = df.drop('Sub GGGrade', axis=1)
# df = df.drop('Postal Code', axis=1)
# df = df.drop('File Status', axis=1)

In [669]:
# tags = ['Postal Code']
# for tag in tags:
#   for i in range(df.shape[0]):
#     #print (i)
#     df[tag][i] = str(df[tag][i])

In [670]:
# df['GGGrade'].replace('VII',7,inplace=True)
# df['GGGrade'].replace('VI',6,inplace=True)
# df['GGGrade'].replace('V',5,inplace=True)
# df['GGGrade'].replace('IV',4,inplace=True)
# df['GGGrade'].replace('III',3,inplace=True)
# df['GGGrade'].replace('II',2,inplace=True)
# df['GGGrade'].replace('I',1,inplace=True)
# df['GGGrade'] = df['GGGrade'].astype(int)

In [671]:
# df['Experience'].replace('<1yr',0.3,inplace=True)
# df['Experience'].replace('1yrs',1,inplace=True)
# df['Experience'].replace('2yrs',2,inplace=True)
# df['Experience'].replace('3yrs',3,inplace=True)
# df['Experience'].replace('4yrs',4,inplace=True)
# df['Experience'].replace('5yrs',5,inplace=True)
# df['Experience'].replace('6yrs',6,inplace=True)
# df['Experience'].replace('7yrs',7,inplace=True)
# df['Experience'].replace('8yrs',8,inplace=True)
# df['Experience'].replace('9yrs',9,inplace=True)
# df['Experience'].replace('>10yrs',12,inplace=True)
# df['Experience'] = df['Experience'].astype(int)

In [672]:
# df['Validation'].replace('Source Verified','Vfied',inplace=True)

In [673]:
# df = df.drop(['Designation','State'], axis=1)

In [674]:
# df.drop('Postal Code',axis=1,inplace=True)

In [675]:
categorical_features_indices = np.where(df.dtypes == "object")[0]
categorical_features_indices

array([ 2,  3,  4,  6,  7,  9, 20, 21, 24, 26, 27])

In [676]:
# for tag in df.columns[categorical_features_indices]:
#   df[tag] = df[tag].astype("category")

In [677]:
df.drop('Designation',axis=1,inplace=True)
df = pd.get_dummies(df,drop_first=True)
df.columns = df.columns.str.replace(',', '_')
df.columns = df.columns.str.replace('<', 'l_')
df.columns = df.columns.str.replace('V', 'g_')

In [678]:
len(X.columns)

119

In [679]:
len(df.columns)

120

In [680]:
for tag in X.columns:
  if (tag in X.columns) and (tag in df.columns):
    pass
  else:
    print("##",tag)
    X.drop(tag,axis=1,inplace=True)

## Unpaid 2 years_16

In [681]:
lst=[]
for tag in df.columns:
  if (tag in X.columns) and (tag in df.columns) and (tag != 'ID'):
    pass
  else:
    if tag=='ID':
      pass
    else:
      print("##",tag)
      df.drop(tag,axis=1,inplace=True)

## Unpaid 2 years_17

In [682]:
from sklearn.metrics import f1_score
import numpy as np

def f1_eval(y_pred, dtrain):
    y_true = dtrain.get_label()
    err = 1-f1_score(y_true, np.round(y_pred))
    return 'f1_err', err

In [683]:
from lightgbm import LGBMClassifier
clf = LGBMClassifier(n_estimators=1000,early_stopping_rounds=100,device='gpu')
model=clf.fit(X,y,eval_metric=f1_eval)

/usr/local/lib/python3.7/dist-packages/lightgbm/engine.py:123: UserWarning: Found `early_stopping_rounds` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))

LightGBMError: ignored

In [ ]:
# from xgboost import XGBClassifier
# clf = XGBClassifier(tree_method='gpu_hist',sampling_method='gradient_based',subsample=0.2,iterations=10000,eta=0.1,gamma = 1000)
# # clf = XGBClassifier(tree_method='gpu_hist',sampling_method='gradient_based',subsample=0.2,iterations=10000,eta=0.1,booster='gblinear',reg_lambda=5.0 )
# model=clf.fit(X,y,eval_metric=f1_eval)

In [ ]:
df['Loan/No Loan'] = model.predict(df.drop('ID',axis=1))
df

In [ ]:
pred_prob = model.predict_proba(df.drop(['ID','Loan/No Loan'],axis=1))
pred_prob = pred_prob[:,1]
pred_prob

In [ ]:
custom_prob = 0.24
custom_cutoff_data=[]

for i in range(0,len(pred_prob)):  #2333
    if pred_prob[i] >custom_prob:
        a= 1
    else:
        a=0
    custom_cutoff_data.append(a)

In [ ]:
df['Loan/No Loan'] = custom_cutoff_data

In [ ]:
df2=df[['ID','Loan/No Loan']]
df2['ID'] = df2['ID'].astype('int64')
df2['Loan/No Loan'] = df2['Loan/No Loan'].astype('int64')
df2

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Hackathon/Data_Test.csv')
df

In [ ]:
df2['ID'] = df['ID']
df2.info()

In [ ]:
df2.to_csv('/content/drive/MyDrive/Colab Notebooks/Hackathon/lgbm1.csv',index=0)