In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Data_Train.csv')
df

,ID,Asst_Reg,GGGrade,Experience,Validation,Yearly Income,Home Status,Unpaid 2 years,Already Defaulted,Designation,...,File Status,State,Account Open,Total Unpaid CL,Duration,Unpaid Amount,Reason,Claim Type,Due Fee,Loan/No Loan
0,95074,421802,II,>10yrs,Vfied,633600.00,MOR??AGE,0,0,GLENDALE NISSAN,...,fully paid,California,17,58598.0,3 years,31216.05,debt consolidation,I,0.0,0
1,134131,3964312,IV,7yrs,Source Verified,85483.20,REN?,0,0,Business Teacher,...,whole,NC,15,18924.0,5 years,11660.49,debt consolidation,I,0.0,0
2,92602,4247560,III,<1yr,Source Verified,79200.00,REN?,0,0,driver,...,whole,Florida,7,15604.0,5 years,5637.87,major purchase,I,0.0,0
3,22591,197179,III,<1yr,Vfied,61600.00,REN?,0,0,AvePoint,...,fully paid,NewJersey,9,22410.0,3 years,15607.17,major purchase,I,0.0,1
4,125060,4646684,V,2yrs,Source Verified,68053.92,REN?,0,0,Lead Tester,...,fully paid,LA,10,36022.0,5 years,27472.86,debt consolidation,I,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87495,120884,4535984,II,>10yrs,Not Vfied,75680.00,REN?,0,0,Engineer Support II,...,whole,MI,12,32702.0,3 years,10012.05,debt consolidation,I,0.0,0
87496,33259,2624710,IV,3yrs,Source Verified,90423.52,REN?,0,0,Dental Hygienist,...,whole,MA,23,32204.0,5 years,24921.54,debt consolidation,I,0.0,0
87497,102153,5966919,II,>10yrs,Source Verified,91520.00,MOR??AGE,0,0,Interface Coordinator,...,fully paid,CT,8,29050.0,3 years,14517.90,debt consolidation,I,0.0,0
87498,115343,2630667,III,1yrs,Source Verified,61600.00,MOR??AGE,0,0,PARTS CLERK,...,whole,PA,11,24900.0,3 years,8454.24,debt consolidation,I,0.0,0
87499,104968,6637289,III,2yrs,Vfied,NaN,REN?,0,0,Outside sales rep,...,whole,California,7,21746.0,5 years,8717.58,debt consolidation,I,0.0,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87500 entries, 0 to 87499
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   87500 non-null  int64
 1   Asst_Reg             87500 non-null  int64
 2   GGGrade              87500 non-null  object
 3   Experience           87500 non-null  object
 4   Validation           87500 non-null  object
 5   Yearly Income        81925 non-null  float64
 6   Home Status          87500 non-null  object
 7   Unpaid 2 years       87500 non-null  int64
 8   Already Defaulted    87500 non-null  int64
 9   Designation          86086 non-null  object
 10  Debt to Income       84011 non-null  float64
 11  Postal Code          86111 non-null  float64
 12  Lend Amount          87500 non-null  float64
 13  Deprecatory Records  87500 non-null  int64
 14  Interest Charged     87500 non-null  float64
 15  Usage Rate           87500 non-null  float64
 16  Inquiries            87500 non-null  int64
 17  Present Balance      87500 non-null  float64
 18  Gross Collection     87500 non-null  float64
 19  Sub GGGrade          87500 non-null  int64
 20  File Status          87500 non-null  object
 21  State                87500 non-null  object
 22  Account Open         87500 non-null  int64
 23  Total Unpaid CL      83314 non-null  float64
 24  Duration             87500 non-null  object
 25  Unpaid Amount        82648 non-null  float64
 26  Reason               87500 non-null  object
 27  Claim Type           87500 non-null  object
 28  Due Fee              87500 non-null  float64
 29  Loan/No Loan         87500 non-null  int64
dtypes: float64(11), int64(9), object(10)
memory usage: 20.0+ MB

In [4]:
for feature in df.columns:
    print("--",feature,"--")
    print (df[feature].value_counts(normalize=True))
    print("\n\n")

-- ID --
95074     0.000011
102140    0.000011
102258    0.000011
80480     0.000011
39012     0.000011
            ...
79773     0.000011
40215     0.000011
61647     0.000011
76276     0.000011
104968    0.000011
Name: ID, Length: 87500, dtype: float64



-- Asst_Reg --
6238431    0.000034
7054989    0.000034
6428230    0.000034
4738693    0.000034
1195917    0.000034
             ...
6084772    0.000011
391671     0.000011
6095924    0.000011
4728725    0.000011
6637289    0.000011
Name: Asst_Reg, Length: 83966, dtype: float64



-- GGGrade --
II     0.285326
III    0.281737
I      0.161954
IV     0.158480
V      0.081760
VI     0.025051
VII    0.005691
Name: GGGrade, dtype: float64



-- Experience --
>10yrs    0.352560
2yrs      0.092160
3yrs      0.084000
<1yr      0.082389
1yrs      0.066891
5yrs      0.064263
4yrs      0.060846
7yrs      0.054423
8yrs      0.052617
6yrs      0.048629
9yrs      0.041223
Name: Experience, dtype: float64



-- Validation --
Source Verified    0.394331
Vfied              0.304480
Not Vfied          0.301189
Name: Validation, dtype: float64



-- Yearly Income --
105600.00    0.039194
88000.00     0.034898
114400.00    0.030381
123200.00    0.029417
70400.00     0.027904
               ...
108894.72    0.000012
179688.96    0.000012
62575.04     0.000012
168590.40    0.000012
90423.52     0.000012
Name: Yearly Income, Length: 6871, dtype: float64



-- Home Status --
MOR??AGE    0.504686
REN?        0.399017
OWN         0.096183
OTHER       0.000069
NONE        0.000046
Name: Home Status, dtype: float64



-- Unpaid 2 years --
0     0.797337
1     0.132617
2     0.041806
3     0.014560
4     0.006457
5     0.003143
6     0.001783
7     0.000766
8     0.000491
9     0.000297
10    0.000251
12    0.000171
11    0.000149
18    0.000046
14    0.000046
13    0.000034
16    0.000023
15    0.000023
Name: Unpaid 2 years, dtype: float64



-- Already Defaulted --
0    0.994686
1    0.005017
2    0.000251
6    0.000011
5    0.000011
4    0.000011
3    0.000011
Name: Already Defaulted, dtype: float64



-- Designation --
School Teacher                 0.018412
Super Lead                     0.015357
Nurse                          0.008631
RN                             0.007504
Owner                          0.007237
                                 ...
B.R. Amon and Sons             0.000012
Medical record technician      0.000012
Executive Field Assistant      0.000012
Speech language pathologist    0.000012
Outside sales rep              0.000012
Name: Designation, Length: 40354, dtype: float64



-- Debt to Income --
22.9824    0.000726
28.2240    0.000726
36.2880    0.000714
24.1920    0.000702
32.2560    0.000702
             ...
59.6736    0.000012
64.9152    0.000012
0.5880     0.000012
65.2344    0.000012
63.6888    0.000012
Name: Debt to Income, Length: 3964, dtype: float64



-- Postal Code --
75000.0    0.011346
94500.0    0.010742
11200.0    0.010486
60600.0    0.009778
33100.0    0.008988
             ...
4300.0     0.000012
90100.0    0.000012
50000.0    0.000012
96500.0    0.000012
83800.0    0.000012
Name: Postal Code, Length: 865, dtype: float64



-- Lend Amount --
17100.00    0.069909
20520.00    0.056514
34200.00    0.055749
25650.00    0.055269
59850.00    0.043794
              ...
56900.25    0.000011
55275.75    0.000011
1923.75     0.000011
45400.50    0.000011
52796.25    0.000011
Name: Lend Amount, Length: 1298, dtype: float64



-- Deprecatory Records --
0     0.843737
1     0.129760
2     0.016926
3     0.005314
4     0.002206
5     0.000971
6     0.000446
7     0.000274
8     0.000160
10    0.000080
9     0.000034
16    0.000023
12    0.000011
86    0.000011
11    0.000011
13    0.000011
22    0.000011
15    0.000011
Name: Deprecatory Records, dtype: float64



-- Interest Charged --
14.56    0.000857
15.69    0.000846
9.53     0.000846
23.65    0.000834
12.57    0.000834
           ...
13.00    0.000389
16.20    0.000377
8.00     0.000354
9.93     0.000354
25.00    0.000286
Name: Interest Charged, Length: 1701, dtype: float64



-- Usage Rate --
0.000      0.002697
113.520    0.002400
91.160     0.002354
99.760     0.002343
96.320     0.002103
             ...
194.360    0.000011
179.740    0.000011
193.672    0.000011
189.716    0.000011
222.740    0.000011
Name: Usage Rate, Length: 1088, dtype: float64



-- Inquiries --
0    0.569749
1    0.269726
2    0.103314
3    0.040423
4    0.012069
5    0.003600
6    0.001109
8    0.000011
Name: Inquiries, dtype: float64



-- Present Balance --
0.00         0.000160
39779.40     0.000069
22114.14     0.000069
40570.98     0.000069
43530.22     0.000069
               ...
262744.44    0.000011
191517.27    0.000011
114039.29    0.000011
913563.48    0.000011
10445.85     0.000011
Name: Present Balance, Length: 73819, dtype: float64



-- Gross Collection --
0.00        0.980743
2080.72     0.000023
11.90       0.000023
5437.55     0.000023
1200.00     0.000023
              ...
1054.22     0.000011
803.04      0.000011
2108.94     0.000011
13832.92    0.000011
691.56      0.000011
Name: Gross Collection, Length: 1678, dtype: float64



-- Sub GGGrade --
19    0.062331
18    0.061291
22    0.059600
21    0.059131
23    0.057863
24    0.056651
17    0.055371
20    0.054949
16    0.051383
15    0.049497
25    0.048491
26    0.041760
14    0.037600
27    0.033840
28    0.030034
29    0.028697
13    0.025954
11    0.025051
30    0.024149
12    0.023851
31    0.020777
32    0.019737
33    0.016880
34    0.013440
35    0.010926
36    0.007749
37    0.005509
38    0.004994
39    0.003749
40    0.003051
41    0.002023
42    0.001383
43    0.001040
45    0.000663
44    0.000583
Name: Sub GGGrade, dtype: float64



-- File Status --
whole         0.529143
fully paid    0.470857
Name: File Status, dtype: float64



-- State --
California    0.144286
Newyork       0.082400
TX            0.081486
Florida       0.066434
IL            0.040023
NewJersey     0.037177
PA            0.036217
Ohio          0.033931
GA            0.033417
VA            0.029086
NC            0.028800
MI            0.025749
Maryland      0.023691
AZ            0.023520
MA            0.023143
CO            0.021509
WA            0.021257
MN            0.019120
IN            0.016377
MO            0.016114
TN            0.015554
CT            0.015143
NV            0.013394
AL            0.013029
WI            0.012754
OR            0.012000
LA            0.011646
SC            0.011486
KY            0.009383
KS            0.009360
OK            0.008754
AR            0.007429
UT            0.007303
NM            0.005680
HI            0.005314
NH            0.004880
MS            0.004686
WV            0.004434
RI            0.004251
MT            0.002960
DE            0.002720
DC            0.002686
AK            0.002526
WY            0.002126
SD            0.002069
VT            0.002034
NE            0.001531
ND            0.000571
ME            0.000560
Name: State, dtype: float64



-- Account Open --
11    0.090594
10    0.089040
9     0.083783
12    0.082526
13    0.074354
8     0.072011
14    0.065566
7     0.060457
15    0.055371
16    0.046206
6     0.041520
17    0.038514
18    0.032514
19    0.026000
5     0.023943
20    0.021406
21    0.016926
22    0.014343
23    0.011783
24    0.009097
4     0.008331
25    0.006743
26    0.005611
27    0.004057
28    0.003486
29    0.002971
3     0.002240
30    0.002114
31    0.001760
32    0.001326
33    0.001097
34    0.000869
35    0.000594
36    0.000537
37    0.000469
39    0.000274
38    0.000263
2     0.000206
40    0.000149
43    0.000137
41    0.000137
42    0.000126
49    0.000080
45    0.000080
44    0.000069
46    0.000046
48    0.000046
51    0.000034
50    0.000034
54    0.000034
56    0.000023
52    0.000023
80    0.000011
83    0.000011
63    0.000011
68    0.000011
57    0.000011
65    0.000011
47    0.000011
Name: Account Open, dtype: float64



-- Total Unpaid CL --
24070.00     0.003457
14110.00     0.003385
24900.00     0.003373
19090.00     0.003373
27390.00     0.003253
               ...
274232.00    0.000012
30226.94     0.000012
12101.40     0.000012
103972.44    0.000012
105859.86    0.000012
Name: Total Unpaid CL, Length: 4385, dtype: float64



-- Duration --
3 years    0.686411
5 years    0.313589
Name: Duration, dtype: float64



-- Unpaid Amount --
0.00        0.002190
11407.41    0.000169
25915.05    0.000157
12763.44    0.000145
8864.64     0.000145
              ...
68526.54    0.000012
28683.54    0.000012
76825.17    0.000012
50424.48    0.000012
52676.55    0.000012
Name: Unpaid Amount, Length: 34679, dtype: float64



-- Reason --
debt  consolidation    0.600674
credit  card           0.241166
home  improvement      0.055840
other                  0.043131
major  purchase        0.017280
medical                0.009383
small  business        0.008583
car                    0.008114
moving                 0.005749
vacation               0.004846
house                  0.003554
wedding                0.001246
renewable  energy      0.000434
Name: Reason, dtype: float64



-- Claim Type --
I    0.999474
J    0.000526
Name: Claim Type, dtype: float64



-- Due Fee --
0.00     0.988697
15.00    0.003143
30.00    0.000320
20.50    0.000046
44.03    0.000046
           ...
84.92    0.000011
28.18    0.000011
15.21    0.000011
38.02    0.000011
18.06    0.000011
Name: Due Fee, Length: 608, dtype: float64



-- Loan/No Loan --
0    0.811291
1    0.188709
Name: Loan/No Loan, dtype: float64

In [5]:
df['GGGrade'].replace('VII','VI',inplace=True)
df['GGGrade'].replace('VI','V',inplace=True)

In [6]:
df['GGGrade'].value_counts(normalize=True)

II     0.285326
III    0.281737
I      0.161954
IV     0.158480
V      0.112503
Name: GGGrade, dtype: float64

In [7]:
df['Experience'].value_counts(normalize=True)

>10yrs    0.352560
2yrs      0.092160
3yrs      0.084000
<1yr      0.082389
1yrs      0.066891
5yrs      0.064263
4yrs      0.060846
7yrs      0.054423
8yrs      0.052617
6yrs      0.048629
9yrs      0.041223
Name: Experience, dtype: float64

In [8]:
df['Experience'].replace('<1yr','1-3',inplace=True)
df['Experience'].replace('1yrs','1-3',inplace=True)
df['Experience'].replace('2yrs','1-3',inplace=True)
df['Experience'].replace('3yrs','1-3',inplace=True)

In [9]:
df['Experience'].replace('4yrs','4-9',inplace=True)
df['Experience'].replace('5yrs','4-9',inplace=True)
df['Experience'].replace('6yrs','4-9',inplace=True)
df['Experience'].replace('7yrs','4-9',inplace=True)
df['Experience'].replace('8yrs','4-9',inplace=True)
df['Experience'].replace('9yrs','4-9',inplace=True)

In [10]:
df['Validation'].value_counts(normalize=True)

Source Verified    0.394331
Vfied              0.304480
Not Vfied          0.301189
Name: Validation, dtype: float64

In [11]:
df['Validation'].replace('Source Verified','Vfied',inplace=True)

In [12]:
df['Home Status'].value_counts(normalize=True)

MOR??AGE    0.504686
REN?        0.399017
OWN         0.096183
OTHER       0.000069
NONE        0.000046
Name: Home Status, dtype: float64

In [13]:
df['Home Status'].replace('NONE','MOR??AGE',inplace=True)
df['Home Status'].replace('OTHER','MOR??AGE',inplace=True)

In [14]:
df['Unpaid 2 years'] = df['Unpaid 2 years'].astype(str)
df

,ID,Asst_Reg,GGGrade,Experience,Validation,Yearly Income,Home Status,Unpaid 2 years,Already Defaulted,Designation,...,File Status,State,Account Open,Total Unpaid CL,Duration,Unpaid Amount,Reason,Claim Type,Due Fee,Loan/No Loan
0,95074,421802,II,>10yrs,Vfied,633600.00,MOR??AGE,0,0,GLENDALE NISSAN,...,fully paid,California,17,58598.0,3 years,31216.05,debt consolidation,I,0.0,0
1,134131,3964312,IV,4-9,Vfied,85483.20,REN?,0,0,Business Teacher,...,whole,NC,15,18924.0,5 years,11660.49,debt consolidation,I,0.0,0
2,92602,4247560,III,1-3,Vfied,79200.00,REN?,0,0,driver,...,whole,Florida,7,15604.0,5 years,5637.87,major purchase,I,0.0,0
3,22591,197179,III,1-3,Vfied,61600.00,REN?,0,0,AvePoint,...,fully paid,NewJersey,9,22410.0,3 years,15607.17,major purchase,I,0.0,1
4,125060,4646684,V,1-3,Vfied,68053.92,REN?,0,0,Lead Tester,...,fully paid,LA,10,36022.0,5 years,27472.86,debt consolidation,I,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87495,120884,4535984,II,>10yrs,Not Vfied,75680.00,REN?,0,0,Engineer Support II,...,whole,MI,12,32702.0,3 years,10012.05,debt consolidation,I,0.0,0
87496,33259,2624710,IV,1-3,Vfied,90423.52,REN?,0,0,Dental Hygienist,...,whole,MA,23,32204.0,5 years,24921.54,debt consolidation,I,0.0,0
87497,102153,5966919,II,>10yrs,Vfied,91520.00,MOR??AGE,0,0,Interface Coordinator,...,fully paid,CT,8,29050.0,3 years,14517.90,debt consolidation,I,0.0,0
87498,115343,2630667,III,1-3,Vfied,61600.00,MOR??AGE,0,0,PARTS CLERK,...,whole,PA,11,24900.0,3 years,8454.24,debt consolidation,I,0.0,0
87499,104968,6637289,III,1-3,Vfied,NaN,REN?,0,0,Outside sales rep,...,whole,California,7,21746.0,5 years,8717.58,debt consolidation,I,0.0,0

In [15]:
df['Unpaid 2 years'].value_counts(normalize=True)

0     0.797337
1     0.132617
2     0.041806
3     0.014560
4     0.006457
5     0.003143
6     0.001783
7     0.000766
8     0.000491
9     0.000297
10    0.000251
12    0.000171
11    0.000149
18    0.000046
14    0.000046
13    0.000034
16    0.000023
15    0.000023
Name: Unpaid 2 years, dtype: float64

In [16]:
for i in range(df.shape[0]):
    if (df.loc[i,'Unpaid 2 years'] != '0') and (df.loc[i,'Unpaid 2 years'] != '1') and (df.loc[i,'Unpaid 2 years'] != '2'):
        df.loc[i,'Unpaid 2 years'] = 3

In [17]:
df['Already Defaulted'] = df['Already Defaulted'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87500 entries, 0 to 87499
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   87500 non-null  int64
 1   Asst_Reg             87500 non-null  int64
 2   GGGrade              87500 non-null  object
 3   Experience           87500 non-null  object
 4   Validation           87500 non-null  object
 5   Yearly Income        81925 non-null  float64
 6   Home Status          87500 non-null  object
 7   Unpaid 2 years       87500 non-null  object
 8   Already Defaulted    87500 non-null  object
 9   Designation          86086 non-null  object
 10  Debt to Income       84011 non-null  float64
 11  Postal Code          86111 non-null  float64
 12  Lend Amount          87500 non-null  float64
 13  Deprecatory Records  87500 non-null  int64
 14  Interest Charged     87500 non-null  float64
 15  Usage Rate           87500 non-null  float64
 16  Inquiries            87500 non-null  int64
 17  Present Balance      87500 non-null  float64
 18  Gross Collection     87500 non-null  float64
 19  Sub GGGrade          87500 non-null  int64
 20  File Status          87500 non-null  object
 21  State                87500 non-null  object
 22  Account Open         87500 non-null  int64
 23  Total Unpaid CL      83314 non-null  float64
 24  Duration             87500 non-null  object
 25  Unpaid Amount        82648 non-null  float64
 26  Reason               87500 non-null  object
 27  Claim Type           87500 non-null  object
 28  Due Fee              87500 non-null  float64
 29  Loan/No Loan         87500 non-null  int64
dtypes: float64(11), int64(7), object(12)
memory usage: 20.0+ MB

In [18]:
df['Already Defaulted'].value_counts(normalize=True)

0    0.994686
1    0.005017
2    0.000251
6    0.000011
5    0.000011
4    0.000011
3    0.000011
Name: Already Defaulted, dtype: float64

In [19]:
for i in range(df.shape[0]):
    if df.loc[i,'Already Defaulted'] != '0':
        df.loc[i,'Already Defaulted'] = '1'

In [20]:
df['Designation'].value_counts(normalize=True)

School Teacher                 0.018412
Super Lead                     0.015357
Nurse                          0.008631
RN                             0.007504
Owner                          0.007237
                                 ...
B.R. Amon and Sons             0.000012
Medical record technician      0.000012
Executive Field Assistant      0.000012
Speech language pathologist    0.000012
Outside sales rep              0.000012
Name: Designation, Length: 40354, dtype: float64

In [21]:
df['Postal Code'] = df['Postal Code'].astype(str)
df['Postal Code'].value_counts(normalize=True)

nan        0.015874
75000.0    0.011166
94500.0    0.010571
11200.0    0.010320
60600.0    0.009623
             ...
4300.0     0.000011
90100.0    0.000011
50000.0    0.000011
96500.0    0.000011
83800.0    0.000011
Name: Postal Code, Length: 866, dtype: float64

In [22]:
df['Deprecatory Records'] = df['Deprecatory Records'].astype(str)
df['Deprecatory Records'].value_counts(normalize=True)

0     0.843737
1     0.129760
2     0.016926
3     0.005314
4     0.002206
5     0.000971
6     0.000446
7     0.000274
8     0.000160
10    0.000080
9     0.000034
16    0.000023
12    0.000011
86    0.000011
11    0.000011
13    0.000011
22    0.000011
15    0.000011
Name: Deprecatory Records, dtype: float64

In [23]:
for i in range(df.shape[0]):
    if (df.loc[i,'Deprecatory Records'] != '0') and (df.loc[i,'Deprecatory Records'] != '1'):
        df.loc[i,'Deprecatory Records'] = '2'

In [24]:
df['Inquiries'] = df['Inquiries'].astype(str)
df['Inquiries'].value_counts(normalize=True)

0    0.569749
1    0.269726
2    0.103314
3    0.040423
4    0.012069
5    0.003600
6    0.001109
8    0.000011
Name: Inquiries, dtype: float64

In [25]:
for i in range(df.shape[0]):
    if (df.loc[i,'Inquiries'] != '0') and (df.loc[i,'Inquiries'] != '1') and (df.loc[i,'Inquiries'] != '2'):
        df.loc[i,'Inquiries'] = '3'

In [26]:
df['Reason'].value_counts(normalize=True)

debt  consolidation    0.600674
credit  card           0.241166
home  improvement      0.055840
other                  0.043131
major  purchase        0.017280
medical                0.009383
small  business        0.008583
car                    0.008114
moving                 0.005749
vacation               0.004846
house                  0.003554
wedding                0.001246
renewable  energy      0.000434
Name: Reason, dtype: float64

In [27]:
for i in range(df.shape[0]):
    if (df.loc[i,'Inquiries'] != 'debt  consolidation') and (df.loc[i,'Inquiries'] != 'credit  card') and (df.loc[i,'Inquiries'] != 'home  improvement') and (df.loc[i,'Inquiries'] != 'other'):
        df.loc[i,'Inquiries'] = 'other-1'

In [28]:
df.drop(['Designation','Asst_Reg','Postal Code','Claim Type'],axis=1,inplace=True)

In [29]:
df.drop(['Account Open', 'State', 'Sub GGGrade'],axis=1,inplace=True)

In [30]:
df.drop('ID',axis=1,inplace=True)

In [31]:
df.isnull().sum()

GGGrade                   0
Experience                0
Validation                0
Yearly Income          5575
Home Status               0
Unpaid 2 years            0
Already Defaulted         0
Debt to Income         3489
Lend Amount               0
Deprecatory Records       0
Interest Charged          0
Usage Rate                0
Inquiries                 0
Present Balance           0
Gross Collection          0
File Status               0
Total Unpaid CL        4186
Duration                  0
Unpaid Amount          4852
Reason                    0
Due Fee                   0
Loan/No Loan              0
dtype: int64

In [32]:
df['Loan/No Loan'].value_counts()

0    70988
1    16512
Name: Loan/No Loan, dtype: int64

In [33]:
df['Loan/No Loan'].value_counts(normalize=True)

0    0.811291
1    0.188709
Name: Loan/No Loan, dtype: float64

In [35]:
df['Yearly Income'].fillna(df['Yearly Income'].mean(),inplace=True)
df['Debt to Income'].fillna(df['Debt to Income'].mean(),inplace=True)
df['Total Unpaid CL'].fillna(df['Total Unpaid CL'].mean(),inplace=True)
df['Unpaid Amount'].fillna(df['Unpaid Amount'].mean(),inplace=True)

#df['Postal Code'].fillna(df['Postal Code'].value_counts().index[0],inplace=True)
#df['Designation'].fillna(df['Designation'].value_counts().index[0],inplace=True)

In [36]:
df.isnull().sum()

GGGrade                0
Experience             0
Validation             0
Yearly Income          0
Home Status            0
Unpaid 2 years         0
Already Defaulted      0
Debt to Income         0
Lend Amount            0
Deprecatory Records    0
Interest Charged       0
Usage Rate             0
Inquiries              0
Present Balance        0
Gross Collection       0
File Status            0
Total Unpaid CL        0
Duration               0
Unpaid Amount          0
Reason                 0
Due Fee                0
Loan/No Loan           0
dtype: int64

In [37]:
df.dropna(inplace=True)
df

,GGGrade,Experience,Validation,Yearly Income,Home Status,Unpaid 2 years,Already Defaulted,Debt to Income,Lend Amount,Deprecatory Records,...,Inquiries,Present Balance,Gross Collection,File Status,Total Unpaid CL,Duration,Unpaid Amount,Reason,Due Fee,Loan/No Loan
0,II,>10yrs,Vfied,633600.00000,MOR??AGE,0,0,12.5496,42023.25,0,...,other-1,607161.90,0.0,fully paid,58598.0,3 years,31216.05,debt consolidation,0.0,0
1,IV,4-9,Vfied,85483.20000,REN?,0,0,9.0048,38133.00,0,...,other-1,269234.06,0.0,whole,18924.0,5 years,11660.49,debt consolidation,0.0,0
2,III,1-3,Vfied,79200.00000,REN?,0,0,24.9144,17100.00,0,...,other-1,22476.53,0.0,whole,15604.0,5 years,5637.87,major purchase,0.0,0
3,III,1-3,Vfied,61600.00000,REN?,0,0,16.5816,5130.00,0,...,other-1,15242.09,0.0,fully paid,22410.0,3 years,15607.17,major purchase,0.0,1
4,V,1-3,Vfied,68053.92000,REN?,0,0,40.0512,19665.00,0,...,other-1,65433.94,0.0,fully paid,36022.0,5 years,27472.86,debt consolidation,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87495,II,>10yrs,Not Vfied,75680.00000,REN?,0,0,19.3200,10260.00,0,...,other-1,15100.14,0.0,whole,32702.0,3 years,10012.05,debt consolidation,0.0,0
87496,IV,1-3,Vfied,90423.52000,REN?,0,0,48.8208,27360.00,0,...,other-1,102811.88,0.0,whole,32204.0,5 years,24921.54,debt consolidation,0.0,0
87497,II,>10yrs,Vfied,91520.00000,MOR??AGE,0,0,7.7952,8550.00,2,...,other-1,14584.11,0.0,fully paid,29050.0,3 years,14517.90,debt consolidation,0.0,0
87498,III,1-3,Vfied,61600.00000,MOR??AGE,0,0,8.2992,23769.00,1,...,other-1,59281.66,0.0,whole,24900.0,3 years,8454.24,debt consolidation,0.0,0
87499,III,1-3,Vfied,134859.62978,REN?,0,0,15.1872,28471.50,1,...,other-1,10445.85,0.0,whole,21746.0,5 years,8717.58,debt consolidation,0.0,0

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 87500 entries, 0 to 87499
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   GGGrade              87500 non-null  object
 1   Experience           87500 non-null  object
 2   Validation           87500 non-null  object
 3   Yearly Income        87500 non-null  float64
 4   Home Status          87500 non-null  object
 5   Unpaid 2 years       87500 non-null  object
 6   Already Defaulted    87500 non-null  object
 7   Debt to Income       87500 non-null  float64
 8   Lend Amount          87500 non-null  float64
 9   Deprecatory Records  87500 non-null  object
 10  Interest Charged     87500 non-null  float64
 11  Usage Rate           87500 non-null  float64
 12  Inquiries            87500 non-null  object
 13  Present Balance      87500 non-null  float64
 14  Gross Collection     87500 non-null  float64
 15  File Status          87500 non-null  object
 16  Total Unpaid CL      87500 non-null  float64
 17  Duration             87500 non-null  object
 18  Unpaid Amount        87500 non-null  float64
 19  Reason               87500 non-null  object
 20  Due Fee              87500 non-null  float64
 21  Loan/No Loan         87500 non-null  int64
dtypes: float64(10), int64(1), object(11)
memory usage: 15.4+ MB

In [39]:
X = df.drop('Loan/No Loan', axis=1)

y = df['Loan/No Loan']

In [40]:
categorical_features_indices = np.where(X.dtypes == "object")[0]
categorical_features_indices

array([ 0,  1,  2,  4,  5,  6,  9, 12, 15, 17, 19], dtype=int64)

In [41]:
from catboost import CatBoostClassifier
clf = CatBoostClassifier(random_state=1,cat_features=categorical_features_indices,eval_metric="F1")
model=clf.fit(X,y)

Learning rate set to 0.06953
0:	learn: 0.0000000	total: 306ms	remaining: 5m 5s
1:	learn: 0.0000000	total: 456ms	remaining: 3m 47s
2:	learn: 0.0000000	total: 636ms	remaining: 3m 31s
3:	learn: 0.0000000	total: 717ms	remaining: 2m 58s
4:	learn: 0.0000000	total: 933ms	remaining: 3m 5s
5:	learn: 0.0000000	total: 1.04s	remaining: 2m 52s
6:	learn: 0.0000000	total: 1.23s	remaining: 2m 54s
7:	learn: 0.0000000	total: 1.28s	remaining: 2m 39s
8:	learn: 0.0000000	total: 1.44s	remaining: 2m 38s
9:	learn: 0.0000000	total: 1.61s	remaining: 2m 39s
10:	learn: 0.0000000	total: 1.8s	remaining: 2m 41s
11:	learn: 0.0000000	total: 1.96s	remaining: 2m 41s
12:	learn: 0.0000000	total: 2.15s	remaining: 2m 43s
13:	learn: 0.0000000	total: 2.37s	remaining: 2m 46s
14:	learn: 0.0000000	total: 2.53s	remaining: 2m 46s
15:	learn: 0.0000000	total: 2.7s	remaining: 2m 46s
16:	learn: 0.0000000	total: 2.89s	remaining: 2m 46s
17:	learn: 0.0000000	total: 3.04s	remaining: 2m 45s
18:	learn: 0.0000000	total: 3.21s	remaining: 2m 45s
19:	learn: 0.0000000	total: 3.39s	remaining: 2m 46s
20:	learn: 0.0000000	total: 3.54s	remaining: 2m 45s
21:	learn: 0.0000000	total: 3.71s	remaining: 2m 44s
22:	learn: 0.0000000	total: 3.85s	remaining: 2m 43s
23:	learn: 0.0000000	total: 3.94s	remaining: 2m 40s
24:	learn: 0.0000000	total: 4.03s	remaining: 2m 36s
25:	learn: 0.0000000	total: 4.21s	remaining: 2m 37s
26:	learn: 0.0000000	total: 4.27s	remaining: 2m 33s
27:	learn: 0.0000000	total: 4.41s	remaining: 2m 33s
28:	learn: 0.0000000	total: 4.53s	remaining: 2m 31s
29:	learn: 0.0000000	total: 4.69s	remaining: 2m 31s
30:	learn: 0.0000000	total: 4.84s	remaining: 2m 31s
31:	learn: 0.0000000	total: 4.99s	remaining: 2m 31s
32:	learn: 0.0000000	total: 5.16s	remaining: 2m 31s
33:	learn: 0.0000000	total: 5.33s	remaining: 2m 31s
34:	learn: 0.0000000	total: 5.53s	remaining: 2m 32s
35:	learn: 0.0000000	total: 5.67s	remaining: 2m 31s
36:	learn: 0.0003633	total: 5.84s	remaining: 2m 31s
37:	learn: 0.0006054	total: 6s	remaining: 2m 31s
38:	learn: 0.0007265	total: 6.15s	remaining: 2m 31s
39:	learn: 0.0007265	total: 6.32s	remaining: 2m 31s
40:	learn: 0.0012104	total: 6.47s	remaining: 2m 31s
41:	learn: 0.0024194	total: 6.66s	remaining: 2m 31s
42:	learn: 0.0031433	total: 6.86s	remaining: 2m 32s
43:	learn: 0.0039877	total: 7.02s	remaining: 2m 32s
44:	learn: 0.0041080	total: 7.2s	remaining: 2m 32s
45:	learn: 0.0041080	total: 7.36s	remaining: 2m 32s
46:	learn: 0.0038671	total: 7.53s	remaining: 2m 32s
47:	learn: 0.0043489	total: 7.69s	remaining: 2m 32s
48:	learn: 0.0050715	total: 7.81s	remaining: 2m 31s
49:	learn: 0.0051917	total: 7.96s	remaining: 2m 31s
50:	learn: 0.0051917	total: 8.11s	remaining: 2m 30s
51:	learn: 0.0051917	total: 8.26s	remaining: 2m 30s
52:	learn: 0.0050715	total: 8.41s	remaining: 2m 30s
53:	learn: 0.0050715	total: 8.58s	remaining: 2m 30s
54:	learn: 0.0050715	total: 8.75s	remaining: 2m 30s
55:	learn: 0.0050715	total: 8.92s	remaining: 2m 30s
56:	learn: 0.0053114	total: 9.06s	remaining: 2m 29s
57:	learn: 0.0055519	total: 9.27s	remaining: 2m 30s
58:	learn: 0.0057926	total: 9.43s	remaining: 2m 30s
59:	learn: 0.0061535	total: 9.6s	remaining: 2m 30s
60:	learn: 0.0062738	total: 9.74s	remaining: 2m 29s
61:	learn: 0.0063940	total: 9.89s	remaining: 2m 29s
62:	learn: 0.0063940	total: 10s	remaining: 2m 29s
63:	learn: 0.0063940	total: 10.2s	remaining: 2m 29s
64:	learn: 0.0063940	total: 10.4s	remaining: 2m 29s
65:	learn: 0.0062738	total: 10.5s	remaining: 2m 29s
66:	learn: 0.0062738	total: 10.7s	remaining: 2m 29s
67:	learn: 0.0063940	total: 10.9s	remaining: 2m 28s
68:	learn: 0.0063940	total: 11s	remaining: 2m 28s
69:	learn: 0.0065143	total: 11.2s	remaining: 2m 28s
70:	learn: 0.0067547	total: 11.4s	remaining: 2m 28s
71:	learn: 0.0068749	total: 11.5s	remaining: 2m 28s
72:	learn: 0.0069951	total: 11.7s	remaining: 2m 28s
73:	learn: 0.0069951	total: 11.9s	remaining: 2m 28s
74:	learn: 0.0067547	total: 12.1s	remaining: 2m 28s
75:	learn: 0.0069951	total: 12.2s	remaining: 2m 28s
76:	learn: 0.0072350	total: 12.4s	remaining: 2m 28s
77:	learn: 0.0072350	total: 12.6s	remaining: 2m 28s
78:	learn: 0.0072350	total: 12.7s	remaining: 2m 28s
79:	learn: 0.0072350	total: 12.8s	remaining: 2m 26s
80:	learn: 0.0072350	total: 12.9s	remaining: 2m 26s
81:	learn: 0.0073552	total: 13.1s	remaining: 2m 26s
82:	learn: 0.0073552	total: 13.3s	remaining: 2m 26s
83:	learn: 0.0073552	total: 13.5s	remaining: 2m 26s
84:	learn: 0.0073552	total: 13.6s	remaining: 2m 26s
85:	learn: 0.0075954	total: 13.8s	remaining: 2m 26s
86:	learn: 0.0075954	total: 13.9s	remaining: 2m 26s
87:	learn: 0.0077155	total: 14.1s	remaining: 2m 26s
88:	learn: 0.0077155	total: 14.3s	remaining: 2m 26s
89:	learn: 0.0077155	total: 14.5s	remaining: 2m 26s
90:	learn: 0.0077155	total: 14.7s	remaining: 2m 26s
91:	learn: 0.0077155	total: 14.8s	remaining: 2m 26s
92:	learn: 0.0078356	total: 15s	remaining: 2m 26s
93:	learn: 0.0078356	total: 15.1s	remaining: 2m 25s
94:	learn: 0.0080757	total: 15.3s	remaining: 2m 26s
95:	learn: 0.0080757	total: 15.5s	remaining: 2m 26s
96:	learn: 0.0080757	total: 15.7s	remaining: 2m 25s
97:	learn: 0.0080757	total: 15.9s	remaining: 2m 26s
98:	learn: 0.0083158	total: 16s	remaining: 2m 25s
99:	learn: 0.0083158	total: 16.2s	remaining: 2m 25s
100:	learn: 0.0081957	total: 16.4s	remaining: 2m 25s
101:	learn: 0.0081957	total: 16.5s	remaining: 2m 25s
102:	learn: 0.0081957	total: 16.7s	remaining: 2m 25s
103:	learn: 0.0081957	total: 16.9s	remaining: 2m 25s
104:	learn: 0.0081957	total: 17s	remaining: 2m 25s
105:	learn: 0.0081957	total: 17.2s	remaining: 2m 25s
106:	learn: 0.0081957	total: 17.4s	remaining: 2m 24s
107:	learn: 0.0084358	total: 17.5s	remaining: 2m 24s
108:	learn: 0.0085552	total: 17.7s	remaining: 2m 24s
109:	learn: 0.0086752	total: 17.9s	remaining: 2m 24s
110:	learn: 0.0085552	total: 18s	remaining: 2m 24s
111:	learn: 0.0085552	total: 18.2s	remaining: 2m 24s
112:	learn: 0.0086757	total: 18.4s	remaining: 2m 24s
113:	learn: 0.0087957	total: 18.5s	remaining: 2m 23s
114:	learn: 0.0087957	total: 18.7s	remaining: 2m 23s
115:	learn: 0.0087957	total: 18.9s	remaining: 2m 23s
116:	learn: 0.0087957	total: 19.1s	remaining: 2m 23s
117:	learn: 0.0089157	total: 19.2s	remaining: 2m 23s
118:	learn: 0.0090356	total: 19.3s	remaining: 2m 23s
119:	learn: 0.0087952	total: 19.5s	remaining: 2m 22s
120:	learn: 0.0086752	total: 19.7s	remaining: 2m 23s
121:	learn: 0.0089157	total: 19.9s	remaining: 2m 22s
122:	learn: 0.0097543	total: 20s	remaining: 2m 22s
123:	learn: 0.0099928	total: 20.2s	remaining: 2m 22s
124:	learn: 0.0102330	total: 20.3s	remaining: 2m 22s
125:	learn: 0.0101126	total: 20.5s	remaining: 2m 22s
126:	learn: 0.0102323	total: 20.7s	remaining: 2m 22s
127:	learn: 0.0103521	total: 20.9s	remaining: 2m 22s
128:	learn: 0.0103521	total: 21.1s	remaining: 2m 22s
129:	learn: 0.0108310	total: 21.2s	remaining: 2m 21s
130:	learn: 0.0109507	total: 21.4s	remaining: 2m 21s
131:	learn: 0.0107113	total: 21.5s	remaining: 2m 21s
132:	learn: 0.0110690	total: 21.7s	remaining: 2m 21s
133:	learn: 0.0110690	total: 21.9s	remaining: 2m 21s
134:	learn: 0.0110690	total: 22s	remaining: 2m 21s
135:	learn: 0.0110690	total: 22.2s	remaining: 2m 20s
136:	learn: 0.0110690	total: 22.2s	remaining: 2m 20s
137:	learn: 0.0110690	total: 22.4s	remaining: 2m 19s
138:	learn: 0.0109493	total: 22.6s	remaining: 2m 19s
139:	learn: 0.0109493	total: 22.6s	remaining: 2m 18s
140:	learn: 0.0110690	total: 22.8s	remaining: 2m 18s
141:	learn: 0.0110690	total: 22.9s	remaining: 2m 18s
142:	learn: 0.0111886	total: 23.1s	remaining: 2m 18s
143:	learn: 0.0113083	total: 23.3s	remaining: 2m 18s
144:	learn: 0.0113083	total: 23.4s	remaining: 2m 18s
145:	learn: 0.0113083	total: 23.6s	remaining: 2m 17s
146:	learn: 0.0113083	total: 23.7s	remaining: 2m 17s
147:	learn: 0.0113083	total: 23.9s	remaining: 2m 17s
148:	learn: 0.0113083	total: 24.1s	remaining: 2m 17s
149:	learn: 0.0113083	total: 24.3s	remaining: 2m 17s
150:	learn: 0.0114279	total: 24.4s	remaining: 2m 17s
151:	learn: 0.0114279	total: 24.5s	remaining: 2m 16s
152:	learn: 0.0114279	total: 24.7s	remaining: 2m 16s
153:	learn: 0.0114279	total: 24.8s	remaining: 2m 16s
154:	learn: 0.0114279	total: 25s	remaining: 2m 16s
155:	learn: 0.0114279	total: 25.2s	remaining: 2m 16s
156:	learn: 0.0114279	total: 25.4s	remaining: 2m 16s

157:	learn: 0.0114272	total: 25.5s	remaining: 2m 15s
158:	learn: 0.0114272	total: 25.6s	remaining: 2m 15s
159:	learn: 0.0114279	total: 25.8s	remaining: 2m 15s
160:	learn: 0.0114279	total: 25.9s	remaining: 2m 15s
161:	learn: 0.0115468	total: 26.1s	remaining: 2m 15s
162:	learn: 0.0115475	total: 26.2s	remaining: 2m 14s
163:	learn: 0.0115475	total: 26.4s	remaining: 2m 14s
164:	learn: 0.0114279	total: 26.6s	remaining: 2m 14s
165:	learn: 0.0114272	total: 26.8s	remaining: 2m 14s
166:	learn: 0.0115468	total: 26.9s	remaining: 2m 14s
167:	learn: 0.0115468	total: 27.1s	remaining: 2m 14s
168:	learn: 0.0115468	total: 27.2s	remaining: 2m 13s
169:	learn: 0.0115468	total: 27.4s	remaining: 2m 13s
170:	learn: 0.0115468	total: 27.5s	remaining: 2m 13s
171:	learn: 0.0115468	total: 27.7s	remaining: 2m 13s
172:	learn: 0.0116664	total: 27.8s	remaining: 2m 13s
173:	learn: 0.0120250	total: 28s	remaining: 2m 12s
174:	learn: 0.0121445	total: 28.1s	remaining: 2m 12s
175:	learn: 0.0121445	total: 28.3s	remaining: 2m 12s
176:	learn: 0.0123835	total: 28.5s	remaining: 2m 12s
177:	learn: 0.0125015	total: 28.7s	remaining: 2m 12s
178:	learn: 0.0129784	total: 28.9s	remaining: 2m 12s
179:	learn: 0.0130970	total: 29s	remaining: 2m 12s
180:	learn: 0.0130970	total: 29.2s	remaining: 2m 12s
181:	learn: 0.0132164	total: 29.3s	remaining: 2m 11s
182:	learn: 0.0133357	total: 29.5s	remaining: 2m 11s
183:	learn: 0.0133357	total: 29.7s	remaining: 2m 11s
184:	learn: 0.0134551	total: 29.8s	remaining: 2m 11s
185:	learn: 0.0134551	total: 30s	remaining: 2m 11s
186:	learn: 0.0136929	total: 30.1s	remaining: 2m 11s
187:	learn: 0.0136937	total: 30.4s	remaining: 2m 11s
188:	learn: 0.0139314	total: 30.5s	remaining: 2m 11s
189:	learn: 0.0141691	total: 30.7s	remaining: 2m 10s
190:	learn: 0.0144066	total: 30.9s	remaining: 2m 10s
191:	learn: 0.0147641	total: 31.1s	remaining: 2m 10s
192:	learn: 0.0147641	total: 31.2s	remaining: 2m 10s
193:	learn: 0.0146441	total: 31.4s	remaining: 2m 10s
194:	learn: 0.0148824	total: 31.6s	remaining: 2m 10s
195:	learn: 0.0148824	total: 31.7s	remaining: 2m 10s
196:	learn: 0.0151206	total: 31.9s	remaining: 2m 10s
197:	learn: 0.0151206	total: 32.1s	remaining: 2m 9s
198:	learn: 0.0151206	total: 32.2s	remaining: 2m 9s
199:	learn: 0.0150015	total: 32.4s	remaining: 2m 9s
200:	learn: 0.0150015	total: 32.5s	remaining: 2m 9s
201:	learn: 0.0154778	total: 32.7s	remaining: 2m 9s
202:	learn: 0.0155978	total: 32.9s	remaining: 2m 8s
203:	learn: 0.0157169	total: 33s	remaining: 2m 8s
204:	learn: 0.0161929	total: 33.2s	remaining: 2m 8s
205:	learn: 0.0160739	total: 33.4s	remaining: 2m 8s
206:	learn: 0.0160729	total: 33.5s	remaining: 2m 8s
207:	learn: 0.0160729	total: 33.7s	remaining: 2m 8s
208:	learn: 0.0160729	total: 33.8s	remaining: 2m 8s
209:	learn: 0.0160739	total: 34s	remaining: 2m 7s
210:	learn: 0.0161919	total: 34.1s	remaining: 2m 7s
211:	learn: 0.0160729	total: 34.3s	remaining: 2m 7s
212:	learn: 0.0166697	total: 34.5s	remaining: 2m 7s
213:	learn: 0.0164328	total: 34.6s	remaining: 2m 7s
214:	learn: 0.0166707	total: 34.8s	remaining: 2m 7s
215:	learn: 0.0167896	total: 35s	remaining: 2m 6s
216:	learn: 0.0166707	total: 35.2s	remaining: 2m 6s
217:	learn: 0.0165517	total: 35.3s	remaining: 2m 6s
218:	learn: 0.0167886	total: 35.5s	remaining: 2m 6s
219:	learn: 0.0169075	total: 35.6s	remaining: 2m 6s
220:	learn: 0.0170264	total: 35.7s	remaining: 2m 6s
221:	learn: 0.0169075	total: 35.9s	remaining: 2m 5s
222:	learn: 0.0170264	total: 36.1s	remaining: 2m 5s
223:	learn: 0.0171442	total: 36.2s	remaining: 2m 5s
224:	learn: 0.0171453	total: 36.4s	remaining: 2m 5s
225:	learn: 0.0172641	total: 36.5s	remaining: 2m 5s
226:	learn: 0.0174997	total: 36.7s	remaining: 2m 4s
227:	learn: 0.0174997	total: 36.9s	remaining: 2m 4s
228:	learn: 0.0177373	total: 37s	remaining: 2m 4s
229:	learn: 0.0179759	total: 37.2s	remaining: 2m 4s
230:	learn: 0.0179759	total: 37.4s	remaining: 2m 4s
231:	learn: 0.0178571	total: 37.5s	remaining: 2m 4s
232:	learn: 0.0180936	total: 37.7s	remaining: 2m 4s
233:	learn: 0.0180947	total: 37.8s	remaining: 2m 3s
234:	learn: 0.0183310	total: 38s	remaining: 2m 3s
235:	learn: 0.0184497	total: 38.2s	remaining: 2m 3s
236:	learn: 0.0185684	total: 38.4s	remaining: 2m 3s
237:	learn: 0.0185684	total: 38.5s	remaining: 2m 3s
238:	learn: 0.0189244	total: 38.7s	remaining: 2m 3s
239:	learn: 0.0190431	total: 38.9s	remaining: 2m 3s
240:	learn: 0.0191617	total: 39.1s	remaining: 2m 3s
241:	learn: 0.0191617	total: 39.2s	remaining: 2m 2s
242:	learn: 0.0193989	total: 39.4s	remaining: 2m 2s
243:	learn: 0.0193989	total: 39.6s	remaining: 2m 2s
244:	learn: 0.0193977	total: 39.7s	remaining: 2m 2s
245:	learn: 0.0193977	total: 39.9s	remaining: 2m 2s
246:	learn: 0.0196348	total: 40.1s	remaining: 2m 2s
247:	learn: 0.0196348	total: 40.2s	remaining: 2m 1s
248:	learn: 0.0201089	total: 40.4s	remaining: 2m 1s
249:	learn: 0.0201089	total: 40.5s	remaining: 2m 1s
250:	learn: 0.0199880	total: 40.7s	remaining: 2m 1s
251:	learn: 0.0198695	total: 40.9s	remaining: 2m 1s
252:	learn: 0.0201065	total: 41s	remaining: 2m 1s
253:	learn: 0.0199880	total: 41.2s	remaining: 2m 1s
254:	learn: 0.0199880	total: 41.4s	remaining: 2m
255:	learn: 0.0202250	total: 41.5s	remaining: 2m
256:	learn: 0.0201053	total: 41.7s	remaining: 2m
257:	learn: 0.0202238	total: 41.8s	remaining: 2m
258:	learn: 0.0204619	total: 42s	remaining: 2m
259:	learn: 0.0204619	total: 42.1s	remaining: 1m 59s
260:	learn: 0.0205815	total: 42.3s	remaining: 1m 59s
261:	learn: 0.0207000	total: 42.4s	remaining: 1m 59s
262:	learn: 0.0207000	total: 42.5s	remaining: 1m 59s
263:	learn: 0.0210526	total: 42.7s	remaining: 1m 58s
264:	learn: 0.0211710	total: 42.9s	remaining: 1m 58s
265:	learn: 0.0210526	total: 43s	remaining: 1m 58s
266:	learn: 0.0211710	total: 43.2s	remaining: 1m 58s
267:	learn: 0.0211710	total: 43.3s	remaining: 1m 58s
268:	learn: 0.0211710	total: 43.5s	remaining: 1m 58s
269:	learn: 0.0214076	total: 43.6s	remaining: 1m 57s
270:	learn: 0.0214064	total: 43.9s	remaining: 1m 57s
271:	learn: 0.0217625	total: 44s	remaining: 1m 57s
272:	learn: 0.0217625	total: 44.2s	remaining: 1m 57s
273:	learn: 0.0218808	total: 44.4s	remaining: 1m 57s
274:	learn: 0.0221186	total: 44.5s	remaining: 1m 57s
275:	learn: 0.0221186	total: 44.7s	remaining: 1m 57s
276:	learn: 0.0220004	total: 44.9s	remaining: 1m 57s
277:	learn: 0.0218834	total: 45s	remaining: 1m 56s
278:	learn: 0.0217638	total: 45.2s	remaining: 1m 56s
279:	learn: 0.0217638	total: 45.3s	remaining: 1m 56s
280:	learn: 0.0221173	total: 45.5s	remaining: 1m 56s
281:	learn: 0.0219990	total: 45.7s	remaining: 1m 56s
282:	learn: 0.0218808	total: 45.9s	remaining: 1m 56s
283:	learn: 0.0221173	total: 46s	remaining: 1m 56s
284:	learn: 0.0223537	total: 46.2s	remaining: 1m 55s
285:	learn: 0.0223537	total: 46.4s	remaining: 1m 55s
286:	learn: 0.0224719	total: 46.5s	remaining: 1m 55s
287:	learn: 0.0224719	total: 46.7s	remaining: 1m 55s
288:	learn: 0.0224719	total: 46.8s	remaining: 1m 55s
289:	learn: 0.0225901	total: 47s	remaining: 1m 54s
290:	learn: 0.0225901	total: 47.1s	remaining: 1m 54s
291:	learn: 0.0227069	total: 47.3s	remaining: 1m 54s
292:	learn: 0.0224719	total: 47.4s	remaining: 1m 54s
293:	learn: 0.0224719	total: 47.6s	remaining: 1m 54s
294:	learn: 0.0225901	total: 47.8s	remaining: 1m 54s
295:	learn: 0.0227083	total: 48s	remaining: 1m 54s
296:	learn: 0.0227083	total: 48.1s	remaining: 1m 53s
297:	learn: 0.0227083	total: 48.3s	remaining: 1m 53s
298:	learn: 0.0227083	total: 48.4s	remaining: 1m 53s
299:	learn: 0.0229446	total: 48.6s	remaining: 1m 53s
300:	learn: 0.0228264	total: 48.8s	remaining: 1m 53s
301:	learn: 0.0228264	total: 48.9s	remaining: 1m 53s
302:	learn: 0.0228264	total: 49.1s	remaining: 1m 52s
303:	learn: 0.0228264	total: 49.3s	remaining: 1m 52s
304:	learn: 0.0230627	total: 49.4s	remaining: 1m 52s
305:	learn: 0.0230613	total: 49.6s	remaining: 1m 52s
306:	learn: 0.0230613	total: 49.8s	remaining: 1m 52s
307:	learn: 0.0230613	total: 49.9s	remaining: 1m 52s
308:	learn: 0.0232947	total: 50.1s	remaining: 1m 52s
309:	learn: 0.0232947	total: 50.3s	remaining: 1m 51s
310:	learn: 0.0237669	total: 50.4s	remaining: 1m 51s
311:	learn: 0.0242388	total: 50.6s	remaining: 1m 51s
312:	learn: 0.0244747	total: 50.8s	remaining: 1m 51s
313:	learn: 0.0244747	total: 50.9s	remaining: 1m 51s
314:	learn: 0.0245941	total: 51.1s	remaining: 1m 51s

315:	learn: 0.0245941	total: 51.3s	remaining: 1m 50s
316:	learn: 0.0244762	total: 51.4s	remaining: 1m 50s
317:	learn: 0.0244762	total: 51.6s	remaining: 1m 50s
318:	learn: 0.0245926	total: 51.7s	remaining: 1m 50s
319:	learn: 0.0248269	total: 51.9s	remaining: 1m 50s
320:	learn: 0.0248269	total: 52s	remaining: 1m 50s
321:	learn: 0.0250627	total: 52.2s	remaining: 1m 49s
322:	learn: 0.0251790	total: 52.3s	remaining: 1m 49s
323:	learn: 0.0252968	total: 52.5s	remaining: 1m 49s
324:	learn: 0.0254161	total: 52.6s	remaining: 1m 49s
325:	learn: 0.0255339	total: 52.8s	remaining: 1m 49s
326:	learn: 0.0256502	total: 53s	remaining: 1m 49s
327:	learn: 0.0257680	total: 53.1s	remaining: 1m 48s
328:	learn: 0.0257680	total: 53.3s	remaining: 1m 48s
329:	learn: 0.0257680	total: 53.4s	remaining: 1m 48s
330:	learn: 0.0261227	total: 53.6s	remaining: 1m 48s
331:	learn: 0.0260050	total: 53.8s	remaining: 1m 48s
332:	learn: 0.0257695	total: 53.9s	remaining: 1m 48s
333:	learn: 0.0257695	total: 54.1s	remaining: 1m 47s
334:	learn: 0.0258888	total: 54.2s	remaining: 1m 47s
335:	learn: 0.0260050	total: 54.4s	remaining: 1m 47s
336:	learn: 0.0257695	total: 54.6s	remaining: 1m 47s
337:	learn: 0.0257695	total: 54.7s	remaining: 1m 47s
338:	learn: 0.0258842	total: 54.9s	remaining: 1m 46s
339:	learn: 0.0260019	total: 55s	remaining: 1m 46s
340:	learn: 0.0260019	total: 55.2s	remaining: 1m 46s
341:	learn: 0.0260019	total: 55.3s	remaining: 1m 46s
342:	learn: 0.0262358	total: 55.5s	remaining: 1m 46s
343:	learn: 0.0258811	total: 55.7s	remaining: 1m 46s
344:	learn: 0.0258811	total: 55.8s	remaining: 1m 45s
345:	learn: 0.0259988	total: 55.9s	remaining: 1m 45s
346:	learn: 0.0257634	total: 56.1s	remaining: 1m 45s
347:	learn: 0.0258811	total: 56.3s	remaining: 1m 45s
348:	learn: 0.0259988	total: 56.4s	remaining: 1m 45s
349:	learn: 0.0262342	total: 56.6s	remaining: 1m 45s
350:	learn: 0.0262326	total: 56.8s	remaining: 1m 44s
351:	learn: 0.0261165	total: 56.9s	remaining: 1m 44s
352:	learn: 0.0260004	total: 57s	remaining: 1m 44s
353:	learn: 0.0263550	total: 57.2s	remaining: 1m 44s
354:	learn: 0.0262358	total: 57.4s	remaining: 1m 44s
355:	learn: 0.0265904	total: 57.5s	remaining: 1m 44s
356:	learn: 0.0270609	total: 57.7s	remaining: 1m 43s
357:	learn: 0.0269433	total: 57.8s	remaining: 1m 43s
358:	learn: 0.0276470	total: 58s	remaining: 1m 43s
359:	learn: 0.0274120	total: 58.2s	remaining: 1m 43s
360:	learn: 0.0275295	total: 58.3s	remaining: 1m 43s
361:	learn: 0.0275295	total: 58.5s	remaining: 1m 43s
362:	learn: 0.0276470	total: 58.6s	remaining: 1m 42s
363:	learn: 0.0274120	total: 58.8s	remaining: 1m 42s
364:	learn: 0.0276470	total: 59s	remaining: 1m 42s
365:	learn: 0.0275295	total: 59.1s	remaining: 1m 42s
366:	learn: 0.0277645	total: 59.3s	remaining: 1m 42s
367:	learn: 0.0278820	total: 59.5s	remaining: 1m 42s
368:	learn: 0.0278820	total: 59.6s	remaining: 1m 41s
369:	learn: 0.0278820	total: 59.8s	remaining: 1m 41s
370:	learn: 0.0277662	total: 59.9s	remaining: 1m 41s
371:	learn: 0.0277662	total: 1m	remaining: 1m 41s
372:	learn: 0.0278820	total: 1m	remaining: 1m 41s
373:	learn: 0.0278804	total: 1m	remaining: 1m 41s
374:	learn: 0.0278820	total: 1m	remaining: 1m 40s
375:	learn: 0.0278820	total: 1m	remaining: 1m 40s
376:	learn: 0.0279995	total: 1m	remaining: 1m 40s
377:	learn: 0.0279995	total: 1m 1s	remaining: 1m 40s
378:	learn: 0.0283502	total: 1m 1s	remaining: 1m 40s
379:	learn: 0.0282345	total: 1m 1s	remaining: 1m 40s
380:	learn: 0.0282328	total: 1m 1s	remaining: 1m 39s
381:	learn: 0.0285867	total: 1m 1s	remaining: 1m 39s
382:	learn: 0.0285867	total: 1m 1s	remaining: 1m 39s
383:	learn: 0.0287024	total: 1m 1s	remaining: 1m 39s
384:	learn: 0.0285850	total: 1m 2s	remaining: 1m 39s
385:	learn: 0.0285867	total: 1m 2s	remaining: 1m 39s
386:	learn: 0.0292927	total: 1m 2s	remaining: 1m 38s
387:	learn: 0.0297619	total: 1m 2s	remaining: 1m 38s
388:	learn: 0.0297619	total: 1m 2s	remaining: 1m 38s
389:	learn: 0.0297601	total: 1m 2s	remaining: 1m 38s
390:	learn: 0.0298774	total: 1m 3s	remaining: 1m 38s
391:	learn: 0.0301119	total: 1m 3s	remaining: 1m 38s
392:	learn: 0.0303463	total: 1m 3s	remaining: 1m 37s
393:	learn: 0.0304635	total: 1m 3s	remaining: 1m 37s
394:	learn: 0.0304617	total: 1m 3s	remaining: 1m 37s
395:	learn: 0.0304617	total: 1m 3s	remaining: 1m 37s
396:	learn: 0.0305789	total: 1m 4s	remaining: 1m 37s
397:	learn: 0.0305789	total: 1m 4s	remaining: 1m 37s
398:	learn: 0.0306960	total: 1m 4s	remaining: 1m 37s
399:	learn: 0.0308132	total: 1m 4s	remaining: 1m 37s
400:	learn: 0.0308132	total: 1m 4s	remaining: 1m 36s
401:	learn: 0.0310456	total: 1m 4s	remaining: 1m 36s
402:	learn: 0.0310456	total: 1m 5s	remaining: 1m 36s
403:	learn: 0.0311627	total: 1m 5s	remaining: 1m 36s
404:	learn: 0.0315139	total: 1m 5s	remaining: 1m 36s
405:	learn: 0.0315139	total: 1m 5s	remaining: 1m 35s
406:	learn: 0.0316309	total: 1m 5s	remaining: 1m 35s
407:	learn: 0.0313949	total: 1m 5s	remaining: 1m 35s
408:	learn: 0.0312779	total: 1m 6s	remaining: 1m 35s
409:	learn: 0.0310474	total: 1m 6s	remaining: 1m 35s
410:	learn: 0.0310437	total: 1m 6s	remaining: 1m 35s
411:	learn: 0.0310437	total: 1m 6s	remaining: 1m 35s
412:	learn: 0.0312779	total: 1m 6s	remaining: 1m 34s
413:	learn: 0.0312779	total: 1m 6s	remaining: 1m 34s
414:	learn: 0.0313949	total: 1m 7s	remaining: 1m 34s
415:	learn: 0.0312760	total: 1m 7s	remaining: 1m 34s
416:	learn: 0.0313949	total: 1m 7s	remaining: 1m 34s
417:	learn: 0.0315120	total: 1m 7s	remaining: 1m 33s
418:	learn: 0.0317441	total: 1m 7s	remaining: 1m 33s
419:	learn: 0.0317441	total: 1m 7s	remaining: 1m 33s
420:	learn: 0.0322121	total: 1m 7s	remaining: 1m 33s
421:	learn: 0.0323290	total: 1m 8s	remaining: 1m 33s
422:	learn: 0.0326797	total: 1m 8s	remaining: 1m 33s
423:	learn: 0.0330304	total: 1m 8s	remaining: 1m 32s
424:	learn: 0.0330304	total: 1m 8s	remaining: 1m 32s
425:	learn: 0.0328005	total: 1m 8s	remaining: 1m 32s
426:	learn: 0.0326836	total: 1m 8s	remaining: 1m 32s
427:	learn: 0.0328005	total: 1m 9s	remaining: 1m 32s
428:	learn: 0.0328005	total: 1m 9s	remaining: 1m 32s
429:	learn: 0.0329135	total: 1m 9s	remaining: 1m 32s
430:	learn: 0.0330304	total: 1m 9s	remaining: 1m 31s
431:	learn: 0.0330304	total: 1m 9s	remaining: 1m 31s
432:	learn: 0.0332660	total: 1m 9s	remaining: 1m 31s
433:	learn: 0.0332660	total: 1m 10s	remaining: 1m 31s
434:	learn: 0.0333828	total: 1m 10s	remaining: 1m 31s
435:	learn: 0.0335016	total: 1m 10s	remaining: 1m 30s
436:	learn: 0.0336184	total: 1m 10s	remaining: 1m 30s
437:	learn: 0.0339688	total: 1m 10s	remaining: 1m 30s
438:	learn: 0.0344357	total: 1m 10s	remaining: 1m 30s
439:	learn: 0.0347857	total: 1m 10s	remaining: 1m 30s
440:	learn: 0.0346670	total: 1m 11s	remaining: 1m 30s
441:	learn: 0.0349024	total: 1m 11s	remaining: 1m 29s
442:	learn: 0.0347857	total: 1m 11s	remaining: 1m 29s
443:	learn: 0.0349024	total: 1m 11s	remaining: 1m 29s
444:	learn: 0.0351356	total: 1m 11s	remaining: 1m 29s
445:	learn: 0.0353688	total: 1m 11s	remaining: 1m 29s
446:	learn: 0.0353688	total: 1m 12s	remaining: 1m 29s
447:	learn: 0.0354854	total: 1m 12s	remaining: 1m 29s
448:	learn: 0.0351335	total: 1m 12s	remaining: 1m 28s
449:	learn: 0.0351335	total: 1m 12s	remaining: 1m 28s
450:	learn: 0.0353667	total: 1m 12s	remaining: 1m 28s
451:	learn: 0.0353667	total: 1m 12s	remaining: 1m 28s
452:	learn: 0.0355999	total: 1m 13s	remaining: 1m 28s
453:	learn: 0.0359495	total: 1m 13s	remaining: 1m 28s
454:	learn: 0.0358329	total: 1m 13s	remaining: 1m 27s
455:	learn: 0.0358329	total: 1m 13s	remaining: 1m 27s
456:	learn: 0.0359495	total: 1m 13s	remaining: 1m 27s
457:	learn: 0.0358308	total: 1m 13s	remaining: 1m 27s
458:	learn: 0.0358287	total: 1m 13s	remaining: 1m 27s
459:	learn: 0.0359452	total: 1m 14s	remaining: 1m 27s
460:	learn: 0.0360617	total: 1m 14s	remaining: 1m 26s
461:	learn: 0.0362968	total: 1m 14s	remaining: 1m 26s
462:	learn: 0.0365297	total: 1m 14s	remaining: 1m 26s
463:	learn: 0.0362968	total: 1m 14s	remaining: 1m 26s
464:	learn: 0.0362968	total: 1m 14s	remaining: 1m 26s
465:	learn: 0.0362968	total: 1m 15s	remaining: 1m 26s
466:	learn: 0.0365297	total: 1m 15s	remaining: 1m 25s
467:	learn: 0.0367625	total: 1m 15s	remaining: 1m 25s
468:	learn: 0.0368811	total: 1m 15s	remaining: 1m 25s
469:	learn: 0.0367647	total: 1m 15s	remaining: 1m 25s

470:	learn: 0.0368855	total: 1m 15s	remaining: 1m 25s
471:	learn: 0.0366526	total: 1m 16s	remaining: 1m 25s
472:	learn: 0.0371183	total: 1m 16s	remaining: 1m 24s
473:	learn: 0.0370019	total: 1m 16s	remaining: 1m 24s
474:	learn: 0.0370019	total: 1m 16s	remaining: 1m 24s
475:	learn: 0.0368855	total: 1m 16s	remaining: 1m 24s
476:	learn: 0.0371161	total: 1m 16s	remaining: 1m 24s
477:	learn: 0.0372325	total: 1m 16s	remaining: 1m 24s
478:	learn: 0.0376978	total: 1m 17s	remaining: 1m 23s
479:	learn: 0.0378141	total: 1m 17s	remaining: 1m 23s
480:	learn: 0.0376978	total: 1m 17s	remaining: 1m 23s
481:	learn: 0.0375815	total: 1m 17s	remaining: 1m 23s
482:	learn: 0.0376978	total: 1m 17s	remaining: 1m 23s
483:	learn: 0.0379304	total: 1m 18s	remaining: 1m 23s
484:	learn: 0.0380467	total: 1m 18s	remaining: 1m 23s
485:	learn: 0.0380467	total: 1m 18s	remaining: 1m 22s
486:	learn: 0.0381630	total: 1m 18s	remaining: 1m 22s
487:	learn: 0.0381607	total: 1m 18s	remaining: 1m 22s
488:	learn: 0.0382769	total: 1m 18s	remaining: 1m 22s
489:	learn: 0.0385094	total: 1m 18s	remaining: 1m 22s
490:	learn: 0.0385117	total: 1m 19s	remaining: 1m 22s
491:	learn: 0.0386279	total: 1m 19s	remaining: 1m 21s
492:	learn: 0.0386279	total: 1m 19s	remaining: 1m 21s
493:	learn: 0.0383954	total: 1m 19s	remaining: 1m 21s
494:	learn: 0.0385140	total: 1m 19s	remaining: 1m 21s
495:	learn: 0.0393295	total: 1m 19s	remaining: 1m 21s
496:	learn: 0.0390972	total: 1m 20s	remaining: 1m 21s
497:	learn: 0.0392134	total: 1m 20s	remaining: 1m 20s
498:	learn: 0.0393295	total: 1m 20s	remaining: 1m 20s
499:	learn: 0.0393318	total: 1m 20s	remaining: 1m 20s
500:	learn: 0.0394480	total: 1m 20s	remaining: 1m 20s
501:	learn: 0.0392157	total: 1m 20s	remaining: 1m 20s
502:	learn: 0.0392157	total: 1m 20s	remaining: 1m 20s
503:	learn: 0.0395617	total: 1m 21s	remaining: 1m 19s
504:	learn: 0.0396802	total: 1m 21s	remaining: 1m 19s
505:	learn: 0.0395641	total: 1m 21s	remaining: 1m 19s
506:	learn: 0.0396802	total: 1m 21s	remaining: 1m 19s
507:	learn: 0.0395617	total: 1m 21s	remaining: 1m 19s
508:	learn: 0.0397939	total: 1m 21s	remaining: 1m 18s
509:	learn: 0.0402605	total: 1m 22s	remaining: 1m 18s
510:	learn: 0.0403765	total: 1m 22s	remaining: 1m 18s
511:	learn: 0.0406085	total: 1m 22s	remaining: 1m 18s
512:	learn: 0.0403765	total: 1m 22s	remaining: 1m 18s
513:	learn: 0.0404925	total: 1m 22s	remaining: 1m 18s
514:	learn: 0.0402581	total: 1m 22s	remaining: 1m 18s
515:	learn: 0.0400261	total: 1m 23s	remaining: 1m 17s
516:	learn: 0.0402581	total: 1m 23s	remaining: 1m 17s
517:	learn: 0.0402605	total: 1m 23s	remaining: 1m 17s
518:	learn: 0.0403765	total: 1m 23s	remaining: 1m 17s
519:	learn: 0.0403741	total: 1m 23s	remaining: 1m 17s
520:	learn: 0.0406061	total: 1m 23s	remaining: 1m 17s
521:	learn: 0.0411859	total: 1m 23s	remaining: 1m 16s
522:	learn: 0.0413018	total: 1m 24s	remaining: 1m 16s
523:	learn: 0.0415335	total: 1m 24s	remaining: 1m 16s
524:	learn: 0.0415335	total: 1m 24s	remaining: 1m 16s
525:	learn: 0.0415360	total: 1m 24s	remaining: 1m 16s
526:	learn: 0.0415385	total: 1m 24s	remaining: 1m 16s
527:	learn: 0.0417677	total: 1m 24s	remaining: 1m 15s
528:	learn: 0.0417677	total: 1m 25s	remaining: 1m 15s
529:	learn: 0.0416519	total: 1m 25s	remaining: 1m 15s
530:	learn: 0.0416543	total: 1m 25s	remaining: 1m 15s
531:	learn: 0.0416519	total: 1m 25s	remaining: 1m 15s
532:	learn: 0.0420044	total: 1m 25s	remaining: 1m 15s
533:	learn: 0.0421202	total: 1m 25s	remaining: 1m 15s
534:	learn: 0.0422360	total: 1m 26s	remaining: 1m 14s
535:	learn: 0.0423468	total: 1m 26s	remaining: 1m 14s
536:	learn: 0.0422310	total: 1m 26s	remaining: 1m 14s
537:	learn: 0.0423468	total: 1m 26s	remaining: 1m 14s
538:	learn: 0.0422310	total: 1m 26s	remaining: 1m 14s
539:	learn: 0.0421152	total: 1m 26s	remaining: 1m 14s
540:	learn: 0.0422310	total: 1m 27s	remaining: 1m 13s
541:	learn: 0.0424651	total: 1m 27s	remaining: 1m 13s
542:	learn: 0.0424651	total: 1m 27s	remaining: 1m 13s
543:	learn: 0.0425809	total: 1m 27s	remaining: 1m 13s
544:	learn: 0.0423493	total: 1m 27s	remaining: 1m 13s
545:	learn: 0.0425809	total: 1m 27s	remaining: 1m 13s
546:	learn: 0.0426966	total: 1m 27s	remaining: 1m 12s
547:	learn: 0.0429281	total: 1m 28s	remaining: 1m 12s
548:	learn: 0.0430413	total: 1m 28s	remaining: 1m 12s
549:	learn: 0.0430413	total: 1m 28s	remaining: 1m 12s
550:	learn: 0.0433909	total: 1m 28s	remaining: 1m 12s
551:	learn: 0.0435065	total: 1m 28s	remaining: 1m 12s
552:	learn: 0.0437378	total: 1m 28s	remaining: 1m 11s
553:	learn: 0.0437378	total: 1m 29s	remaining: 1m 11s
554:	learn: 0.0440846	total: 1m 29s	remaining: 1m 11s
555:	learn: 0.0440846	total: 1m 29s	remaining: 1m 11s
556:	learn: 0.0440820	total: 1m 29s	remaining: 1m 11s
557:	learn: 0.0441976	total: 1m 29s	remaining: 1m 11s
558:	learn: 0.0439638	total: 1m 29s	remaining: 1m 10s
559:	learn: 0.0439638	total: 1m 30s	remaining: 1m 10s
560:	learn: 0.0439638	total: 1m 30s	remaining: 1m 10s
561:	learn: 0.0444234	total: 1m 30s	remaining: 1m 10s
562:	learn: 0.0444234	total: 1m 30s	remaining: 1m 10s
563:	learn: 0.0447726	total: 1m 30s	remaining: 1m 10s
564:	learn: 0.0445363	total: 1m 30s	remaining: 1m 10s
565:	learn: 0.0444182	total: 1m 31s	remaining: 1m 9s
566:	learn: 0.0444182	total: 1m 31s	remaining: 1m 9s
567:	learn: 0.0444208	total: 1m 31s	remaining: 1m 9s
568:	learn: 0.0444182	total: 1m 31s	remaining: 1m 9s
569:	learn: 0.0445390	total: 1m 31s	remaining: 1m 9s
570:	learn: 0.0443053	total: 1m 31s	remaining: 1m 9s
571:	learn: 0.0443079	total: 1m 32s	remaining: 1m 8s
572:	learn: 0.0443079	total: 1m 32s	remaining: 1m 8s
573:	learn: 0.0444234	total: 1m 32s	remaining: 1m 8s
574:	learn: 0.0443053	total: 1m 32s	remaining: 1m 8s
575:	learn: 0.0447699	total: 1m 32s	remaining: 1m 8s
576:	learn: 0.0448828	total: 1m 32s	remaining: 1m 8s
577:	learn: 0.0448828	total: 1m 33s	remaining: 1m 7s
578:	learn: 0.0448828	total: 1m 33s	remaining: 1m 7s
579:	learn: 0.0447673	total: 1m 33s	remaining: 1m 7s
580:	learn: 0.0452318	total: 1m 33s	remaining: 1m 7s
581:	learn: 0.0452291	total: 1m 33s	remaining: 1m 7s
582:	learn: 0.0451137	total: 1m 33s	remaining: 1m 7s
583:	learn: 0.0456907	total: 1m 34s	remaining: 1m 7s
584:	learn: 0.0455726	total: 1m 34s	remaining: 1m 6s
585:	learn: 0.0460340	total: 1m 34s	remaining: 1m 6s
586:	learn: 0.0459241	total: 1m 34s	remaining: 1m 6s
587:	learn: 0.0463854	total: 1m 34s	remaining: 1m 6s
588:	learn: 0.0464979	total: 1m 34s	remaining: 1m 6s
589:	learn: 0.0466132	total: 1m 35s	remaining: 1m 6s
590:	learn: 0.0466132	total: 1m 35s	remaining: 1m 5s
591:	learn: 0.0466104	total: 1m 35s	remaining: 1m 5s
592:	learn: 0.0464952	total: 1m 35s	remaining: 1m 5s
593:	learn: 0.0470658	total: 1m 35s	remaining: 1m 5s
594:	learn: 0.0470658	total: 1m 35s	remaining: 1m 5s
595:	learn: 0.0470658	total: 1m 35s	remaining: 1m 5s
596:	learn: 0.0470658	total: 1m 36s	remaining: 1m 4s
597:	learn: 0.0468409	total: 1m 36s	remaining: 1m 4s
598:	learn: 0.0468464	total: 1m 36s	remaining: 1m 4s
599:	learn: 0.0469617	total: 1m 36s	remaining: 1m 4s
600:	learn: 0.0470769	total: 1m 36s	remaining: 1m 4s
601:	learn: 0.0470769	total: 1m 36s	remaining: 1m 4s
602:	learn: 0.0473017	total: 1m 36s	remaining: 1m 3s
603:	learn: 0.0475320	total: 1m 37s	remaining: 1m 3s
604:	learn: 0.0475320	total: 1m 37s	remaining: 1m 3s
605:	learn: 0.0477623	total: 1m 37s	remaining: 1m 3s
606:	learn: 0.0476471	total: 1m 37s	remaining: 1m 3s
607:	learn: 0.0478774	total: 1m 37s	remaining: 1m 2s
608:	learn: 0.0481075	total: 1m 37s	remaining: 1m 2s
609:	learn: 0.0477594	total: 1m 38s	remaining: 1m 2s
610:	learn: 0.0479953	total: 1m 38s	remaining: 1m 2s
611:	learn: 0.0481104	total: 1m 38s	remaining: 1m 2s
612:	learn: 0.0479925	total: 1m 38s	remaining: 1m 2s
613:	learn: 0.0481075	total: 1m 38s	remaining: 1m 1s
614:	learn: 0.0485706	total: 1m 38s	remaining: 1m 1s
615:	learn: 0.0486827	total: 1m 38s	remaining: 1m 1s
616:	learn: 0.0485677	total: 1m 38s	remaining: 1m 1s
617:	learn: 0.0485677	total: 1m 39s	remaining: 1m 1s
618:	learn: 0.0491427	total: 1m 39s	remaining: 1m 1s
619:	learn: 0.0487977	total: 1m 39s	remaining: 1m
620:	learn: 0.0492576	total: 1m 39s	remaining: 1m
621:	learn: 0.0492576	total: 1m 39s	remaining: 1m
622:	learn: 0.0494875	total: 1m 39s	remaining: 1m
623:	learn: 0.0492605	total: 1m 40s	remaining: 1m
624:	learn: 0.0491456	total: 1m 40s	remaining: 1m

625:	learn: 0.0492576	total: 1m 40s	remaining: 59.9s
626:	learn: 0.0492576	total: 1m 40s	remaining: 59.8s
627:	learn: 0.0493696	total: 1m 40s	remaining: 59.6s
628:	learn: 0.0493696	total: 1m 40s	remaining: 59.4s
629:	learn: 0.0494845	total: 1m 40s	remaining: 59.3s
630:	learn: 0.0497143	total: 1m 41s	remaining: 59.1s
631:	learn: 0.0498321	total: 1m 41s	remaining: 58.9s
632:	learn: 0.0500618	total: 1m 41s	remaining: 58.7s
633:	learn: 0.0501767	total: 1m 41s	remaining: 58.6s
634:	learn: 0.0501767	total: 1m 41s	remaining: 58.4s
635:	learn: 0.0499470	total: 1m 41s	remaining: 58.2s
636:	learn: 0.0499470	total: 1m 41s	remaining: 58s
637:	learn: 0.0500618	total: 1m 41s	remaining: 57.9s
638:	learn: 0.0499440	total: 1m 42s	remaining: 57.7s
639:	learn: 0.0506389	total: 1m 42s	remaining: 57.5s
640:	learn: 0.0507537	total: 1m 42s	remaining: 57.4s
641:	learn: 0.0507507	total: 1m 42s	remaining: 57.2s
642:	learn: 0.0508624	total: 1m 42s	remaining: 57s
643:	learn: 0.0507507	total: 1m 42s	remaining: 56.9s
644:	learn: 0.0507507	total: 1m 43s	remaining: 56.7s
645:	learn: 0.0506329	total: 1m 43s	remaining: 56.6s
646:	learn: 0.0507507	total: 1m 43s	remaining: 56.4s
647:	learn: 0.0507507	total: 1m 43s	remaining: 56.3s
648:	learn: 0.0508654	total: 1m 43s	remaining: 56.1s
649:	learn: 0.0507507	total: 1m 43s	remaining: 55.9s
650:	learn: 0.0506389	total: 1m 44s	remaining: 55.8s
651:	learn: 0.0505271	total: 1m 44s	remaining: 55.6s
652:	learn: 0.0508714	total: 1m 44s	remaining: 55.4s
653:	learn: 0.0510979	total: 1m 44s	remaining: 55.3s
654:	learn: 0.0510979	total: 1m 44s	remaining: 55.1s
655:	learn: 0.0510949	total: 1m 44s	remaining: 54.9s
656:	learn: 0.0514390	total: 1m 44s	remaining: 54.8s
657:	learn: 0.0512096	total: 1m 45s	remaining: 54.6s
658:	learn: 0.0513243	total: 1m 45s	remaining: 54.5s
659:	learn: 0.0513243	total: 1m 45s	remaining: 54.3s
660:	learn: 0.0513243	total: 1m 45s	remaining: 54.1s
661:	learn: 0.0514390	total: 1m 45s	remaining: 54s
662:	learn: 0.0514329	total: 1m 45s	remaining: 53.8s
663:	learn: 0.0515476	total: 1m 46s	remaining: 53.6s
664:	learn: 0.0515476	total: 1m 46s	remaining: 53.5s
665:	learn: 0.0520061	total: 1m 46s	remaining: 53.3s
666:	learn: 0.0522322	total: 1m 46s	remaining: 53.2s
667:	learn: 0.0523499	total: 1m 46s	remaining: 53s
668:	learn: 0.0522414	total: 1m 46s	remaining: 52.9s
669:	learn: 0.0522414	total: 1m 46s	remaining: 52.7s
670:	learn: 0.0524706	total: 1m 47s	remaining: 52.5s
671:	learn: 0.0524706	total: 1m 47s	remaining: 52.4s
672:	learn: 0.0526997	total: 1m 47s	remaining: 52.3s
673:	learn: 0.0524706	total: 1m 47s	remaining: 52.1s
674:	learn: 0.0524706	total: 1m 48s	remaining: 52s
675:	learn: 0.0523560	total: 1m 48s	remaining: 51.9s
676:	learn: 0.0523560	total: 1m 48s	remaining: 51.8s
677:	learn: 0.0528111	total: 1m 48s	remaining: 51.6s
678:	learn: 0.0530401	total: 1m 48s	remaining: 51.5s
679:	learn: 0.0530401	total: 1m 49s	remaining: 51.4s
680:	learn: 0.0532659	total: 1m 49s	remaining: 51.3s
681:	learn: 0.0536061	total: 1m 49s	remaining: 51.1s
682:	learn: 0.0537173	total: 1m 49s	remaining: 51s
683:	learn: 0.0538317	total: 1m 50s	remaining: 50.8s
684:	learn: 0.0538317	total: 1m 50s	remaining: 50.7s
685:	learn: 0.0539461	total: 1m 50s	remaining: 50.6s
686:	learn: 0.0539461	total: 1m 50s	remaining: 50.4s
687:	learn: 0.0541779	total: 1m 50s	remaining: 50.3s
688:	learn: 0.0539492	total: 1m 51s	remaining: 50.1s
689:	learn: 0.0539461	total: 1m 51s	remaining: 50s
690:	learn: 0.0538317	total: 1m 51s	remaining: 49.9s
691:	learn: 0.0541716	total: 1m 51s	remaining: 49.7s
692:	learn: 0.0540541	total: 1m 51s	remaining: 49.6s
693:	learn: 0.0540572	total: 1m 52s	remaining: 49.4s
694:	learn: 0.0540572	total: 1m 52s	remaining: 49.3s
695:	learn: 0.0541747	total: 1m 52s	remaining: 49.1s
696:	learn: 0.0541747	total: 1m 52s	remaining: 49s
697:	learn: 0.0541716	total: 1m 52s	remaining: 48.8s
698:	learn: 0.0542891	total: 1m 53s	remaining: 48.7s
699:	learn: 0.0549715	total: 1m 53s	remaining: 48.6s
700:	learn: 0.0548573	total: 1m 53s	remaining: 48.4s
701:	learn: 0.0549715	total: 1m 53s	remaining: 48.3s
702:	learn: 0.0550857	total: 1m 53s	remaining: 48.1s
703:	learn: 0.0549715	total: 1m 54s	remaining: 48s
704:	learn: 0.0553142	total: 1m 54s	remaining: 47.9s
705:	learn: 0.0555392	total: 1m 54s	remaining: 47.8s
706:	learn: 0.0553142	total: 1m 55s	remaining: 47.7s
707:	learn: 0.0558849	total: 1m 55s	remaining: 47.5s
708:	learn: 0.0558849	total: 1m 55s	remaining: 47.4s
709:	learn: 0.0557708	total: 1m 55s	remaining: 47.2s
710:	learn: 0.0559991	total: 1m 55s	remaining: 47.1s
711:	learn: 0.0561132	total: 1m 56s	remaining: 46.9s
712:	learn: 0.0564521	total: 1m 56s	remaining: 46.8s
713:	learn: 0.0565661	total: 1m 56s	remaining: 46.7s
714:	learn: 0.0565661	total: 1m 56s	remaining: 46.5s
715:	learn: 0.0564521	total: 1m 56s	remaining: 46.4s
716:	learn: 0.0566802	total: 1m 57s	remaining: 46.2s
717:	learn: 0.0567942	total: 1m 57s	remaining: 46.1s
718:	learn: 0.0570222	total: 1m 57s	remaining: 45.9s
719:	learn: 0.0569082	total: 1m 57s	remaining: 45.8s
720:	learn: 0.0569082	total: 1m 57s	remaining: 45.6s
721:	learn: 0.0569082	total: 1m 58s	remaining: 45.5s
722:	learn: 0.0570255	total: 1m 58s	remaining: 45.4s
723:	learn: 0.0570255	total: 1m 58s	remaining: 45.2s
724:	learn: 0.0571395	total: 1m 58s	remaining: 45.1s
725:	learn: 0.0579370	total: 1m 59s	remaining: 44.9s
726:	learn: 0.0585063	total: 1m 59s	remaining: 44.8s
727:	learn: 0.0585063	total: 1m 59s	remaining: 44.6s
728:	learn: 0.0583924	total: 1m 59s	remaining: 44.5s
729:	learn: 0.0583924	total: 1m 59s	remaining: 44.3s
730:	learn: 0.0585063	total: 1m 59s	remaining: 44.2s
731:	learn: 0.0585063	total: 2m	remaining: 44s
732:	learn: 0.0586201	total: 2m	remaining: 43.8s
733:	learn: 0.0587339	total: 2m	remaining: 43.7s
734:	learn: 0.0587339	total: 2m	remaining: 43.5s
735:	learn: 0.0587339	total: 2m	remaining: 43.4s
736:	learn: 0.0588477	total: 2m 1s	remaining: 43.2s
737:	learn: 0.0586201	total: 2m 1s	remaining: 43.1s
738:	learn: 0.0588511	total: 2m 1s	remaining: 42.9s
739:	learn: 0.0590821	total: 2m 1s	remaining: 42.8s
740:	learn: 0.0591959	total: 2m 1s	remaining: 42.6s
741:	learn: 0.0590821	total: 2m 2s	remaining: 42.5s
742:	learn: 0.0591993	total: 2m 2s	remaining: 42.3s
743:	learn: 0.0595440	total: 2m 2s	remaining: 42.2s
744:	learn: 0.0594303	total: 2m 2s	remaining: 42s
745:	learn: 0.0595406	total: 2m 2s	remaining: 41.9s
746:	learn: 0.0598816	total: 2m 3s	remaining: 41.7s
747:	learn: 0.0596543	total: 2m 3s	remaining: 41.5s
748:	learn: 0.0597680	total: 2m 3s	remaining: 41.4s
749:	learn: 0.0595406	total: 2m 3s	remaining: 41.2s
750:	learn: 0.0594268	total: 2m 3s	remaining: 41.1s
751:	learn: 0.0597680	total: 2m 4s	remaining: 40.9s
752:	learn: 0.0597680	total: 2m 4s	remaining: 40.8s
753:	learn: 0.0598816	total: 2m 4s	remaining: 40.6s
754:	learn: 0.0599953	total: 2m 4s	remaining: 40.5s
755:	learn: 0.0598816	total: 2m 4s	remaining: 40.3s
756:	learn: 0.0599953	total: 2m 5s	remaining: 40.1s
757:	learn: 0.0605599	total: 2m 5s	remaining: 40s
758:	learn: 0.0603327	total: 2m 5s	remaining: 39.8s
759:	learn: 0.0606771	total: 2m 5s	remaining: 39.7s
760:	learn: 0.0609042	total: 2m 5s	remaining: 39.5s
761:	learn: 0.0609042	total: 2m 6s	remaining: 39.4s
762:	learn: 0.0612448	total: 2m 6s	remaining: 39.2s
763:	learn: 0.0613583	total: 2m 6s	remaining: 39.1s
764:	learn: 0.0614718	total: 2m 6s	remaining: 38.9s
765:	learn: 0.0614754	total: 2m 6s	remaining: 38.8s
766:	learn: 0.0618158	total: 2m 7s	remaining: 38.6s
767:	learn: 0.0617024	total: 2m 7s	remaining: 38.5s
768:	learn: 0.0618158	total: 2m 7s	remaining: 38.3s
769:	learn: 0.0619293	total: 2m 7s	remaining: 38.2s
770:	learn: 0.0622696	total: 2m 7s	remaining: 38s
771:	learn: 0.0622696	total: 2m 8s	remaining: 37.9s
772:	learn: 0.0622696	total: 2m 8s	remaining: 37.7s
773:	learn: 0.0622696	total: 2m 8s	remaining: 37.5s
774:	learn: 0.0625000	total: 2m 8s	remaining: 37.4s
775:	learn: 0.0623830	total: 2m 8s	remaining: 37.2s
776:	learn: 0.0627231	total: 2m 9s	remaining: 37.1s
777:	learn: 0.0629497	total: 2m 9s	remaining: 36.9s
778:	learn: 0.0631764	total: 2m 9s	remaining: 36.8s
779:	learn: 0.0631764	total: 2m 9s	remaining: 36.6s
780:	learn: 0.0630631	total: 2m 10s	remaining: 36.5s
781:	learn: 0.0630631	total: 2m 10s	remaining: 36.3s

782:	learn: 0.0631764	total: 2m 10s	remaining: 36.2s
783:	learn: 0.0632897	total: 2m 10s	remaining: 36s
784:	learn: 0.0632897	total: 2m 10s	remaining: 35.8s
785:	learn: 0.0631764	total: 2m 11s	remaining: 35.7s
786:	learn: 0.0630631	total: 2m 11s	remaining: 35.5s
787:	learn: 0.0631764	total: 2m 11s	remaining: 35.4s
788:	learn: 0.0634029	total: 2m 11s	remaining: 35.2s
789:	learn: 0.0634029	total: 2m 11s	remaining: 35.1s
790:	learn: 0.0637501	total: 2m 12s	remaining: 34.9s
791:	learn: 0.0637501	total: 2m 12s	remaining: 34.8s
792:	learn: 0.0639766	total: 2m 12s	remaining: 34.6s
793:	learn: 0.0640861	total: 2m 12s	remaining: 34.4s
794:	learn: 0.0638596	total: 2m 12s	remaining: 34.3s
795:	learn: 0.0637427	total: 2m 13s	remaining: 34.1s
796:	learn: 0.0639729	total: 2m 13s	remaining: 34s
797:	learn: 0.0640861	total: 2m 13s	remaining: 33.8s
798:	learn: 0.0645388	total: 2m 13s	remaining: 33.6s
799:	learn: 0.0645388	total: 2m 13s	remaining: 33.5s
800:	learn: 0.0645388	total: 2m 14s	remaining: 33.3s
801:	learn: 0.0646519	total: 2m 14s	remaining: 33.2s
802:	learn: 0.0646519	total: 2m 14s	remaining: 33.1s
803:	learn: 0.0649874	total: 2m 15s	remaining: 32.9s
804:	learn: 0.0654397	total: 2m 15s	remaining: 32.8s
805:	learn: 0.0656657	total: 2m 15s	remaining: 32.6s
806:	learn: 0.0656619	total: 2m 15s	remaining: 32.5s
807:	learn: 0.0656619	total: 2m 16s	remaining: 32.3s
808:	learn: 0.0657749	total: 2m 16s	remaining: 32.2s
809:	learn: 0.0658879	total: 2m 16s	remaining: 32s
810:	learn: 0.0660008	total: 2m 16s	remaining: 31.9s
811:	learn: 0.0662267	total: 2m 16s	remaining: 31.7s
812:	learn: 0.0658917	total: 2m 17s	remaining: 31.5s
813:	learn: 0.0660047	total: 2m 17s	remaining: 31.4s
814:	learn: 0.0660047	total: 2m 17s	remaining: 31.2s
815:	learn: 0.0661176	total: 2m 17s	remaining: 31.1s
816:	learn: 0.0662306	total: 2m 17s	remaining: 30.9s
817:	learn: 0.0663396	total: 2m 18s	remaining: 30.7s
818:	learn: 0.0660008	total: 2m 18s	remaining: 30.6s
819:	learn: 0.0658879	total: 2m 18s	remaining: 30.4s
820:	learn: 0.0664564	total: 2m 18s	remaining: 30.3s
821:	learn: 0.0666822	total: 2m 19s	remaining: 30.1s
822:	learn: 0.0665693	total: 2m 19s	remaining: 30s
823:	learn: 0.0661176	total: 2m 19s	remaining: 29.8s
824:	learn: 0.0663435	total: 2m 19s	remaining: 29.7s
825:	learn: 0.0664564	total: 2m 19s	remaining: 29.5s
826:	learn: 0.0669080	total: 2m 20s	remaining: 29.3s
827:	learn: 0.0665655	total: 2m 20s	remaining: 29.2s
828:	learn: 0.0666783	total: 2m 20s	remaining: 29s
829:	learn: 0.0667912	total: 2m 20s	remaining: 28.8s
830:	learn: 0.0666783	total: 2m 21s	remaining: 28.7s
831:	learn: 0.0666783	total: 2m 21s	remaining: 28.5s
832:	learn: 0.0671258	total: 2m 21s	remaining: 28.4s
833:	learn: 0.0672387	total: 2m 21s	remaining: 28.2s
834:	learn: 0.0674682	total: 2m 21s	remaining: 28s
835:	learn: 0.0678065	total: 2m 22s	remaining: 27.9s
836:	learn: 0.0674643	total: 2m 22s	remaining: 27.7s
837:	learn: 0.0678025	total: 2m 22s	remaining: 27.5s
838:	learn: 0.0679153	total: 2m 22s	remaining: 27.4s
839:	learn: 0.0679153	total: 2m 22s	remaining: 27.2s
840:	learn: 0.0681407	total: 2m 23s	remaining: 27.1s
841:	learn: 0.0683621	total: 2m 23s	remaining: 26.9s
842:	learn: 0.0682455	total: 2m 23s	remaining: 26.7s
843:	learn: 0.0684708	total: 2m 23s	remaining: 26.6s
844:	learn: 0.0684708	total: 2m 23s	remaining: 26.4s
845:	learn: 0.0686961	total: 2m 24s	remaining: 26.2s
846:	learn: 0.0684708	total: 2m 24s	remaining: 26.1s
847:	learn: 0.0684748	total: 2m 24s	remaining: 25.9s
848:	learn: 0.0684748	total: 2m 24s	remaining: 25.8s
849:	learn: 0.0687001	total: 2m 24s	remaining: 25.6s
850:	learn: 0.0685834	total: 2m 25s	remaining: 25.4s
851:	learn: 0.0684708	total: 2m 25s	remaining: 25.3s
852:	learn: 0.0684748	total: 2m 25s	remaining: 25.1s
853:	learn: 0.0685874	total: 2m 25s	remaining: 24.9s
854:	learn: 0.0684748	total: 2m 26s	remaining: 24.8s
855:	learn: 0.0685874	total: 2m 26s	remaining: 24.6s
856:	learn: 0.0685874	total: 2m 26s	remaining: 24.5s
857:	learn: 0.0685874	total: 2m 26s	remaining: 24.3s
858:	learn: 0.0685914	total: 2m 27s	remaining: 24.1s
859:	learn: 0.0687041	total: 2m 27s	remaining: 24s
860:	learn: 0.0687041	total: 2m 27s	remaining: 23.8s
861:	learn: 0.0687041	total: 2m 27s	remaining: 23.7s
862:	learn: 0.0688127	total: 2m 28s	remaining: 23.5s
863:	learn: 0.0688127	total: 2m 28s	remaining: 23.4s
864:	learn: 0.0691505	total: 2m 28s	remaining: 23.2s
865:	learn: 0.0690379	total: 2m 28s	remaining: 23s
866:	learn: 0.0690379	total: 2m 29s	remaining: 22.9s
867:	learn: 0.0690379	total: 2m 29s	remaining: 22.7s
868:	learn: 0.0692631	total: 2m 29s	remaining: 22.5s
869:	learn: 0.0694882	total: 2m 29s	remaining: 22.4s
870:	learn: 0.0693756	total: 2m 29s	remaining: 22.2s
871:	learn: 0.0694922	total: 2m 30s	remaining: 22s
872:	learn: 0.0694922	total: 2m 30s	remaining: 21.9s
873:	learn: 0.0695926	total: 2m 30s	remaining: 21.7s
874:	learn: 0.0700425	total: 2m 30s	remaining: 21.5s
875:	learn: 0.0701550	total: 2m 30s	remaining: 21.4s
876:	learn: 0.0703799	total: 2m 31s	remaining: 21.2s
877:	learn: 0.0699301	total: 2m 31s	remaining: 21s
878:	learn: 0.0700425	total: 2m 31s	remaining: 20.9s
879:	learn: 0.0702674	total: 2m 31s	remaining: 20.7s
880:	learn: 0.0704923	total: 2m 31s	remaining: 20.5s
881:	learn: 0.0707171	total: 2m 32s	remaining: 20.4s
882:	learn: 0.0708295	total: 2m 32s	remaining: 20.2s
883:	learn: 0.0708295	total: 2m 32s	remaining: 20s
884:	learn: 0.0709459	total: 2m 32s	remaining: 19.9s
885:	learn: 0.0709459	total: 2m 33s	remaining: 19.7s
886:	learn: 0.0711706	total: 2m 33s	remaining: 19.5s
887:	learn: 0.0711665	total: 2m 33s	remaining: 19.4s
888:	learn: 0.0713870	total: 2m 33s	remaining: 19.2s
889:	learn: 0.0713870	total: 2m 33s	remaining: 19s
890:	learn: 0.0713870	total: 2m 34s	remaining: 18.9s
891:	learn: 0.0713870	total: 2m 34s	remaining: 18.7s
892:	learn: 0.0716116	total: 2m 34s	remaining: 18.5s
893:	learn: 0.0717238	total: 2m 34s	remaining: 18.4s
894:	learn: 0.0711624	total: 2m 35s	remaining: 18.2s
895:	learn: 0.0712747	total: 2m 35s	remaining: 18s
896:	learn: 0.0711624	total: 2m 35s	remaining: 17.9s
897:	learn: 0.0713870	total: 2m 35s	remaining: 17.7s
898:	learn: 0.0716116	total: 2m 35s	remaining: 17.5s
899:	learn: 0.0717238	total: 2m 36s	remaining: 17.3s
900:	learn: 0.0717238	total: 2m 36s	remaining: 17.2s
901:	learn: 0.0717238	total: 2m 36s	remaining: 17s
902:	learn: 0.0713995	total: 2m 36s	remaining: 16.8s
903:	learn: 0.0713995	total: 2m 36s	remaining: 16.7s
904:	learn: 0.0715118	total: 2m 37s	remaining: 16.5s
905:	learn: 0.0718486	total: 2m 37s	remaining: 16.3s
906:	learn: 0.0722976	total: 2m 37s	remaining: 16.2s
907:	learn: 0.0722976	total: 2m 37s	remaining: 16s
908:	learn: 0.0725178	total: 2m 38s	remaining: 15.8s
909:	learn: 0.0722934	total: 2m 38s	remaining: 15.7s
910:	learn: 0.0724056	total: 2m 38s	remaining: 15.5s
911:	learn: 0.0724056	total: 2m 38s	remaining: 15.3s
912:	learn: 0.0726299	total: 2m 39s	remaining: 15.2s
913:	learn: 0.0728542	total: 2m 39s	remaining: 15s
914:	learn: 0.0728585	total: 2m 39s	remaining: 14.8s
915:	learn: 0.0726299	total: 2m 39s	remaining: 14.6s
916:	learn: 0.0726299	total: 2m 39s	remaining: 14.5s
917:	learn: 0.0726299	total: 2m 40s	remaining: 14.3s
918:	learn: 0.0727421	total: 2m 40s	remaining: 14.1s
919:	learn: 0.0730785	total: 2m 40s	remaining: 14s
920:	learn: 0.0730785	total: 2m 40s	remaining: 13.8s
921:	learn: 0.0729664	total: 2m 40s	remaining: 13.6s
922:	learn: 0.0731991	total: 2m 41s	remaining: 13.4s
923:	learn: 0.0737595	total: 2m 41s	remaining: 13.3s
924:	learn: 0.0738716	total: 2m 41s	remaining: 13.1s
925:	learn: 0.0742076	total: 2m 41s	remaining: 12.9s
926:	learn: 0.0747674	total: 2m 41s	remaining: 12.8s
927:	learn: 0.0746555	total: 2m 42s	remaining: 12.6s
928:	learn: 0.0747674	total: 2m 42s	remaining: 12.4s
929:	learn: 0.0747631	total: 2m 42s	remaining: 12.2s
930:	learn: 0.0744273	total: 2m 42s	remaining: 12.1s
931:	learn: 0.0744273	total: 2m 43s	remaining: 11.9s
932:	learn: 0.0744273	total: 2m 43s	remaining: 11.7s
933:	learn: 0.0744229	total: 2m 43s	remaining: 11.6s
934:	learn: 0.0744186	total: 2m 43s	remaining: 11.4s
935:	learn: 0.0743110	total: 2m 44s	remaining: 11.2s
936:	learn: 0.0752020	total: 2m 44s	remaining: 11s
937:	learn: 0.0755375	total: 2m 44s	remaining: 10.9s

938:	learn: 0.0754256	total: 2m 44s	remaining: 10.7s
939:	learn: 0.0756493	total: 2m 44s	remaining: 10.5s
940:	learn: 0.0757655	total: 2m 45s	remaining: 10.3s
941:	learn: 0.0759847	total: 2m 45s	remaining: 10.2s
942:	learn: 0.0757611	total: 2m 45s	remaining: 10s
943:	learn: 0.0759847	total: 2m 45s	remaining: 9.83s
944:	learn: 0.0762126	total: 2m 45s	remaining: 9.66s
945:	learn: 0.0761053	total: 2m 46s	remaining: 9.48s
946:	learn: 0.0761053	total: 2m 46s	remaining: 9.31s
947:	learn: 0.0759979	total: 2m 46s	remaining: 9.13s
948:	learn: 0.0759891	total: 2m 46s	remaining: 8.96s
949:	learn: 0.0759847	total: 2m 46s	remaining: 8.79s
950:	learn: 0.0762082	total: 2m 47s	remaining: 8.61s
951:	learn: 0.0762082	total: 2m 47s	remaining: 8.44s
952:	learn: 0.0760964	total: 2m 47s	remaining: 8.27s
953:	learn: 0.0763243	total: 2m 47s	remaining: 8.09s
954:	learn: 0.0763243	total: 2m 48s	remaining: 7.92s
955:	learn: 0.0763243	total: 2m 48s	remaining: 7.74s
956:	learn: 0.0762126	total: 2m 48s	remaining: 7.57s
957:	learn: 0.0762126	total: 2m 48s	remaining: 7.39s
958:	learn: 0.0764361	total: 2m 48s	remaining: 7.22s
959:	learn: 0.0764361	total: 2m 49s	remaining: 7.04s
960:	learn: 0.0765478	total: 2m 49s	remaining: 6.87s
961:	learn: 0.0765478	total: 2m 49s	remaining: 6.69s
962:	learn: 0.0765478	total: 2m 49s	remaining: 6.52s
963:	learn: 0.0765478	total: 2m 49s	remaining: 6.34s
964:	learn: 0.0766551	total: 2m 50s	remaining: 6.17s
965:	learn: 0.0765434	total: 2m 50s	remaining: 5.99s
966:	learn: 0.0768784	total: 2m 50s	remaining: 5.82s
967:	learn: 0.0768784	total: 2m 50s	remaining: 5.64s
968:	learn: 0.0767667	total: 2m 50s	remaining: 5.47s
969:	learn: 0.0772134	total: 2m 51s	remaining: 5.29s
970:	learn: 0.0774366	total: 2m 51s	remaining: 5.12s
971:	learn: 0.0777713	total: 2m 51s	remaining: 4.94s
972:	learn: 0.0776598	total: 2m 51s	remaining: 4.76s
973:	learn: 0.0777713	total: 2m 51s	remaining: 4.59s
974:	learn: 0.0777713	total: 2m 52s	remaining: 4.41s
975:	learn: 0.0776598	total: 2m 52s	remaining: 4.24s
976:	learn: 0.0777713	total: 2m 52s	remaining: 4.06s
977:	learn: 0.0778829	total: 2m 52s	remaining: 3.88s
978:	learn: 0.0776598	total: 2m 52s	remaining: 3.71s
979:	learn: 0.0777668	total: 2m 53s	remaining: 3.53s
980:	learn: 0.0778784	total: 2m 53s	remaining: 3.35s
981:	learn: 0.0778784	total: 2m 53s	remaining: 3.18s
982:	learn: 0.0779944	total: 2m 53s	remaining: 3s
983:	learn: 0.0781014	total: 2m 53s	remaining: 2.83s
984:	learn: 0.0777668	total: 2m 54s	remaining: 2.65s
985:	learn: 0.0777668	total: 2m 54s	remaining: 2.47s
986:	learn: 0.0779944	total: 2m 54s	remaining: 2.3s
987:	learn: 0.0779899	total: 2m 54s	remaining: 2.12s
988:	learn: 0.0782220	total: 2m 54s	remaining: 1.95s
989:	learn: 0.0783426	total: 2m 55s	remaining: 1.77s
990:	learn: 0.0782266	total: 2m 55s	remaining: 1.59s
991:	learn: 0.0783381	total: 2m 55s	remaining: 1.41s
992:	learn: 0.0785611	total: 2m 55s	remaining: 1.24s
993:	learn: 0.0787932	total: 2m 55s	remaining: 1.06s
994:	learn: 0.0789046	total: 2m 55s	remaining: 884ms
995:	learn: 0.0791275	total: 2m 56s	remaining: 708ms
996:	learn: 0.0789046	total: 2m 56s	remaining: 531ms
997:	learn: 0.0789046	total: 2m 56s	remaining: 354ms
998:	learn: 0.0790115	total: 2m 56s	remaining: 177ms
999:	learn: 0.0790115	total: 2m 56s	remaining: 0us

In [42]:
df = pd.read_csv('Data_Test.csv')
df

,ID,Asst_Reg,GGGrade,Experience,Validation,Yearly Income,Home Status,Unpaid 2 years,Already Defaulted,Designation,...,Sub GGGrade,File Status,State,Account Open,Total Unpaid CL,Duration,Unpaid Amount,Reason,Claim Type,Due Fee
0,198980,1773284,II,2yrs,Source Verified,140800.00,OWN,0,0,processor,...,17,fully paid,California,23,33532.0,3 years,15755.94,major purchase,I,0.0
1,167688,5298273,II,>10yrs,Vfied,146080.00,MOR??AGE,0,0,Speech Language Pathologist,...,19,whole,Florida,17,149234.0,5 years,68237.55,debt consolidation,I,0.0
2,198768,189781,VI,>10yrs,Vfied,202222.24,MOR??AGE,0,0,Raytheon,...,37,whole,NM,15,70218.0,5 years,66272.76,debt consolidation,I,0.0
3,192564,1530906,II,>10yrs,Vfied,105600.00,MOR??AGE,1,0,Computer/Network Technician,...,19,fully paid,DE,18,79182.0,3 years,15595.20,credit card,I,0.0
4,151199,4410316,III,4yrs,Not Vfied,151360.00,MOR??AGE,0,0,NDE Tech,...,25,fully paid,Florida,7,13612.0,3 years,8850.96,debt consolidation,I,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37495,191405,5774816,IV,4yrs,Vfied,308000.00,MOR??AGE,1,0,Regional Manager,...,29,fully paid,California,19,132468.0,3 years,57683.43,debt consolidation,I,0.0
37496,164868,1423834,IV,8yrs,Source Verified,158400.00,MOR??AGE,0,0,Clinical Coordinator,...,28,fully paid,PA,14,51958.0,5 years,51395.76,credit card,I,0.0
37497,163156,1895531,V,>10yrs,Not Vfied,52800.00,OWN,0,0,administrative,...,33,fully paid,California,9,8466.0,3 years,2783.88,debt consolidation,I,0.0
37498,169610,2168910,VI,9yrs,Not Vfied,52800.00,OWN,5,0,ParaEducator,...,40,whole,TN,9,17264.0,3 years,NaN,home improvement,I,0.0
37499,175557,4140268,II,>10yrs,Source Verified,121440.00,MOR??AGE,0,0,School Teacher,...,19,fully paid,California,15,47310.0,3 years,29504.34,debt consolidation,I,0.0

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37500 entries, 0 to 37499
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   37500 non-null  int64
 1   Asst_Reg             37500 non-null  int64
 2   GGGrade              37500 non-null  object
 3   Experience           37500 non-null  object
 4   Validation           37500 non-null  object
 5   Yearly Income        35075 non-null  float64
 6   Home Status          37500 non-null  object
 7   Unpaid 2 years       37500 non-null  int64
 8   Already Defaulted    37500 non-null  int64
 9   Designation          36914 non-null  object
 10  Debt to Income       35989 non-null  float64
 11  Postal Code          36889 non-null  float64
 12  Lend Amount          37500 non-null  float64
 13  Deprecatory Records  37500 non-null  int64
 14  Interest Charged     37500 non-null  float64
 15  Usage Rate           37500 non-null  float64
 16  Inquiries            37500 non-null  int64
 17  Present Balance      37500 non-null  float64
 18  Gross Collection     37500 non-null  float64
 19  Sub GGGrade          37500 non-null  int64
 20  File Status          37500 non-null  object
 21  State                37500 non-null  object
 22  Account Open         37500 non-null  int64
 23  Total Unpaid CL      35686 non-null  float64
 24  Duration             37500 non-null  object
 25  Unpaid Amount        35431 non-null  float64
 26  Reason               37500 non-null  object
 27  Claim Type           37500 non-null  object
 28  Due Fee              37500 non-null  float64
dtypes: float64(11), int64(8), object(10)
memory usage: 8.3+ MB

In [44]:
df['GGGrade'].replace('VII','VI',inplace=True)
df['GGGrade'].replace('VI','V',inplace=True)

In [45]:
df['GGGrade'].value_counts(normalize=True)

III    0.284853
II     0.281040
I      0.163440
IV     0.156213
V      0.114453
Name: GGGrade, dtype: float64

In [46]:
df['Experience'].value_counts(normalize=True)

>10yrs    0.350907
2yrs      0.090987
3yrs      0.083413
<1yr      0.082720
1yrs      0.065147
5yrs      0.064320
4yrs      0.059707
8yrs      0.057173
7yrs      0.052507
6yrs      0.049520
9yrs      0.043600
Name: Experience, dtype: float64

In [47]:
df['Experience'].replace('<1yr','1-3',inplace=True)
df['Experience'].replace('1yrs','1-3',inplace=True)
df['Experience'].replace('2yrs','1-3',inplace=True)
df['Experience'].replace('3yrs','1-3',inplace=True)

In [48]:
df['Experience'].replace('4yrs','4-9',inplace=True)
df['Experience'].replace('5yrs','4-9',inplace=True)
df['Experience'].replace('6yrs','4-9',inplace=True)
df['Experience'].replace('7yrs','4-9',inplace=True)
df['Experience'].replace('8yrs','4-9',inplace=True)
df['Experience'].replace('9yrs','4-9',inplace=True)

In [49]:
df['Validation'].value_counts(normalize=True)

Source Verified    0.390560
Not Vfied          0.306347
Vfied              0.303093
Name: Validation, dtype: float64

In [50]:
df['Validation'].replace('Source Verified','Vfied',inplace=True)

In [51]:
df['Home Status'].value_counts(normalize=True)

MOR??AGE    0.504320
REN?        0.399787
OWN         0.095787
NONE        0.000053
OTHER       0.000053
Name: Home Status, dtype: float64

In [52]:
df['Home Status'].replace('NONE','MOR??AGE',inplace=True)
df['Home Status'].replace('OTHER','MOR??AGE',inplace=True)

In [53]:
df['Unpaid 2 years'] = df['Unpaid 2 years'].astype(str)
df

,ID,Asst_Reg,GGGrade,Experience,Validation,Yearly Income,Home Status,Unpaid 2 years,Already Defaulted,Designation,...,Sub GGGrade,File Status,State,Account Open,Total Unpaid CL,Duration,Unpaid Amount,Reason,Claim Type,Due Fee
0,198980,1773284,II,1-3,Vfied,140800.00,OWN,0,0,processor,...,17,fully paid,California,23,33532.0,3 years,15755.94,major purchase,I,0.0
1,167688,5298273,II,>10yrs,Vfied,146080.00,MOR??AGE,0,0,Speech Language Pathologist,...,19,whole,Florida,17,149234.0,5 years,68237.55,debt consolidation,I,0.0
2,198768,189781,V,>10yrs,Vfied,202222.24,MOR??AGE,0,0,Raytheon,...,37,whole,NM,15,70218.0,5 years,66272.76,debt consolidation,I,0.0
3,192564,1530906,II,>10yrs,Vfied,105600.00,MOR??AGE,1,0,Computer/Network Technician,...,19,fully paid,DE,18,79182.0,3 years,15595.20,credit card,I,0.0
4,151199,4410316,III,4-9,Not Vfied,151360.00,MOR??AGE,0,0,NDE Tech,...,25,fully paid,Florida,7,13612.0,3 years,8850.96,debt consolidation,I,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37495,191405,5774816,IV,4-9,Vfied,308000.00,MOR??AGE,1,0,Regional Manager,...,29,fully paid,California,19,132468.0,3 years,57683.43,debt consolidation,I,0.0
37496,164868,1423834,IV,4-9,Vfied,158400.00,MOR??AGE,0,0,Clinical Coordinator,...,28,fully paid,PA,14,51958.0,5 years,51395.76,credit card,I,0.0
37497,163156,1895531,V,>10yrs,Not Vfied,52800.00,OWN,0,0,administrative,...,33,fully paid,California,9,8466.0,3 years,2783.88,debt consolidation,I,0.0
37498,169610,2168910,V,4-9,Not Vfied,52800.00,OWN,5,0,ParaEducator,...,40,whole,TN,9,17264.0,3 years,NaN,home improvement,I,0.0
37499,175557,4140268,II,>10yrs,Vfied,121440.00,MOR??AGE,0,0,School Teacher,...,19,fully paid,California,15,47310.0,3 years,29504.34,debt consolidation,I,0.0

In [54]:
df['Unpaid 2 years'].value_counts(normalize=True)

0     0.797760
1     0.132427
2     0.040027
3     0.014453
4     0.007307
5     0.003307
6     0.002187
7     0.001147
8     0.000613
10    0.000213
9     0.000213
12    0.000107
13    0.000053
17    0.000053
11    0.000053
15    0.000027
14    0.000027
18    0.000027
Name: Unpaid 2 years, dtype: float64

In [55]:
for i in range(df.shape[0]):
    if (df.loc[i,'Unpaid 2 years'] != '0') and (df.loc[i,'Unpaid 2 years'] != '1') and (df.loc[i,'Unpaid 2 years'] != '2'):
        df.loc[i,'Unpaid 2 years'] = 3

In [56]:
df['Already Defaulted'] = df['Already Defaulted'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37500 entries, 0 to 37499
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   37500 non-null  int64
 1   Asst_Reg             37500 non-null  int64
 2   GGGrade              37500 non-null  object
 3   Experience           37500 non-null  object
 4   Validation           37500 non-null  object
 5   Yearly Income        35075 non-null  float64
 6   Home Status          37500 non-null  object
 7   Unpaid 2 years       37500 non-null  object
 8   Already Defaulted    37500 non-null  object
 9   Designation          36914 non-null  object
 10  Debt to Income       35989 non-null  float64
 11  Postal Code          36889 non-null  float64
 12  Lend Amount          37500 non-null  float64
 13  Deprecatory Records  37500 non-null  int64
 14  Interest Charged     37500 non-null  float64
 15  Usage Rate           37500 non-null  float64
 16  Inquiries            37500 non-null  int64
 17  Present Balance      37500 non-null  float64
 18  Gross Collection     37500 non-null  float64
 19  Sub GGGrade          37500 non-null  int64
 20  File Status          37500 non-null  object
 21  State                37500 non-null  object
 22  Account Open         37500 non-null  int64
 23  Total Unpaid CL      35686 non-null  float64
 24  Duration             37500 non-null  object
 25  Unpaid Amount        35431 non-null  float64
 26  Reason               37500 non-null  object
 27  Claim Type           37500 non-null  object
 28  Due Fee              37500 non-null  float64
dtypes: float64(11), int64(6), object(12)
memory usage: 8.3+ MB

In [57]:
df['Already Defaulted'].value_counts(normalize=True)

0    0.995013
1    0.004747
2    0.000160
3    0.000080
Name: Already Defaulted, dtype: float64

In [58]:
for i in range(df.shape[0]):
    if df.loc[i,'Already Defaulted'] != '0':
        df.loc[i,'Already Defaulted'] = '1'

In [59]:
df['Designation'].value_counts(normalize=True)

School Teacher                      0.018042
Super Lead                          0.016119
Nurse                               0.009156
RN                                  0.007585
Owner                               0.007260
                                      ...
License Consultant                  0.000027
Systems Administrator Supervisor    0.000027
At. Acct.                           0.000027
Senior Sales Engineer               0.000027
ParaEducator                        0.000027
Name: Designation, Length: 19510, dtype: float64

In [60]:
df['Postal Code'] = df['Postal Code'].astype(str)
df['Postal Code'].value_counts(normalize=True)

nan        0.016293
75000.0    0.011253
94500.0    0.010480
11200.0    0.009867
60600.0    0.009413
             ...
58400.0    0.000027
9000.0     0.000027
51300.0    0.000027
5200.0     0.000027
20400.0    0.000027
Name: Postal Code, Length: 850, dtype: float64

In [61]:
df['Deprecatory Records'] = df['Deprecatory Records'].astype(str)
df['Deprecatory Records'].value_counts(normalize=True)

0     0.841707
1     0.132853
2     0.016933
3     0.004880
4     0.001840
5     0.000853
6     0.000480
7     0.000187
8     0.000080
9     0.000053
21    0.000027
11    0.000027
12    0.000027
13    0.000027
10    0.000027
Name: Deprecatory Records, dtype: float64

In [62]:
for i in range(df.shape[0]):
    if (df.loc[i,'Deprecatory Records'] != '0') and (df.loc[i,'Deprecatory Records'] != '1'):
        df.loc[i,'Deprecatory Records'] = '2'

In [63]:
df['Inquiries'] = df['Inquiries'].astype(str)
df['Inquiries'].value_counts(normalize=True)

0    0.566640
1    0.271920
2    0.103067
3    0.041040
4    0.012213
5    0.004107
6    0.001013
Name: Inquiries, dtype: float64

In [64]:
for i in range(df.shape[0]):
    if (df.loc[i,'Inquiries'] != '0') and (df.loc[i,'Inquiries'] != '1') and (df.loc[i,'Inquiries'] != '2'):
        df.loc[i,'Inquiries'] = '3'

In [65]:
df['Reason'].value_counts(normalize=True)

debt  consolidation    0.599013
credit  card           0.241440
home  improvement      0.057520
other                  0.045173
major  purchase        0.016187
medical                0.008907
small  business        0.008107
car                    0.008027
moving                 0.005840
vacation               0.004507
house                  0.003627
wedding                0.001120
renewable  energy      0.000533
Name: Reason, dtype: float64

In [66]:
for i in range(df.shape[0]):
    if (df.loc[i,'Inquiries'] != 'debt  consolidation') and (df.loc[i,'Inquiries'] != 'credit  card') and (df.loc[i,'Inquiries'] != 'home  improvement') and (df.loc[i,'Inquiries'] != 'other'):
        df.loc[i,'Inquiries'] = 'other-1'

In [67]:
df.drop(['Designation','Asst_Reg','Postal Code','Claim Type'],axis=1,inplace=True)

In [68]:
df.drop(['Account Open', 'State', 'Sub GGGrade'],axis=1,inplace=True)

In [69]:
df.isnull().sum()

ID                        0
GGGrade                   0
Experience                0
Validation                0
Yearly Income          2425
Home Status               0
Unpaid 2 years            0
Already Defaulted         0
Debt to Income         1511
Lend Amount               0
Deprecatory Records       0
Interest Charged          0
Usage Rate                0
Inquiries                 0
Present Balance           0
Gross Collection          0
File Status               0
Total Unpaid CL        1814
Duration                  0
Unpaid Amount          2069
Reason                    0
Due Fee                   0
dtype: int64

In [71]:
#df['Postal Code'] = df['Postal Code'].astype("object")

In [72]:
df['Yearly Income'].fillna(df['Yearly Income'].mean(),inplace=True)
df['Debt to Income'].fillna(df['Debt to Income'].mean(),inplace=True)
df['Total Unpaid CL'].fillna(df['Total Unpaid CL'].mean(),inplace=True)
df['Unpaid Amount'].fillna(df['Unpaid Amount'].mean(),inplace=True)

#df['Postal Code'].fillna(df['Postal Code'].value_counts().index[0],inplace=True)
#df['Designation'].fillna(df['Designation'].value_counts().index[0],inplace=True)

KeyError: 'Postal Code'

In [74]:
df.isnull().sum()

ID                     0
GGGrade                0
Experience             0
Validation             0
Yearly Income          0
Home Status            0
Unpaid 2 years         0
Already Defaulted      0
Debt to Income         0
Lend Amount            0
Deprecatory Records    0
Interest Charged       0
Usage Rate             0
Inquiries              0
Present Balance        0
Gross Collection       0
File Status            0
Total Unpaid CL        0
Duration               0
Unpaid Amount          0
Reason                 0
Due Fee                0
dtype: int64

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37500 entries, 0 to 37499
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   37500 non-null  int64
 1   GGGrade              37500 non-null  object
 2   Experience           37500 non-null  object
 3   Validation           37500 non-null  object
 4   Yearly Income        37500 non-null  float64
 5   Home Status          37500 non-null  object
 6   Unpaid 2 years       37500 non-null  object
 7   Already Defaulted    37500 non-null  object
 8   Debt to Income       37500 non-null  float64
 9   Lend Amount          37500 non-null  float64
 10  Deprecatory Records  37500 non-null  object
 11  Interest Charged     37500 non-null  float64
 12  Usage Rate           37500 non-null  float64
 13  Inquiries            37500 non-null  object
 14  Present Balance      37500 non-null  float64
 15  Gross Collection     37500 non-null  float64
 16  File Status          37500 non-null  object
 17  Total Unpaid CL      37500 non-null  float64
 18  Duration             37500 non-null  object
 19  Unpaid Amount        37500 non-null  float64
 20  Reason               37500 non-null  object
 21  Due Fee              37500 non-null  float64
dtypes: float64(10), int64(1), object(11)
memory usage: 6.3+ MB

In [76]:
df

,ID,GGGrade,Experience,Validation,Yearly Income,Home Status,Unpaid 2 years,Already Defaulted,Debt to Income,Lend Amount,...,Usage Rate,Inquiries,Present Balance,Gross Collection,File Status,Total Unpaid CL,Duration,Unpaid Amount,Reason,Due Fee
0,198980,II,1-3,Vfied,140800.00,OWN,0,0,16.9176,17955.00,...,78.432,other-1,59769.30,0.0,fully paid,33532.0,3 years,15755.940000,major purchase,0.0
1,167688,II,>10yrs,Vfied,146080.00,MOR??AGE,0,0,28.6944,59850.00,...,76.368,other-1,532962.13,0.0,whole,149234.0,5 years,68237.550000,debt consolidation,0.0
2,198768,V,>10yrs,Vfied,202222.24,MOR??AGE,0,0,51.1560,59850.00,...,157.552,other-1,288816.48,0.0,whole,70218.0,5 years,66272.760000,debt consolidation,0.0
3,192564,II,>10yrs,Vfied,105600.00,MOR??AGE,1,0,27.0144,19323.00,...,32.852,other-1,424664.30,0.0,fully paid,79182.0,3 years,15595.200000,credit card,0.0
4,151199,III,4-9,Not Vfied,151360.00,MOR??AGE,0,0,10.3824,25350.75,...,108.532,other-1,251704.07,0.0,fully paid,13612.0,3 years,8850.960000,debt consolidation,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37495,191405,IV,4-9,Vfied,308000.00,MOR??AGE,1,0,29.4336,59850.00,...,52.116,other-1,848107.83,0.0,fully paid,132468.0,3 years,57683.430000,debt consolidation,0.0
37496,164868,IV,4-9,Vfied,158400.00,MOR??AGE,0,0,31.6008,28215.00,...,165.120,other-1,614710.30,0.0,fully paid,51958.0,5 years,51395.760000,credit card,0.0
37497,163156,V,>10yrs,Not Vfied,52800.00,OWN,0,0,46.9728,4916.25,...,54.868,other-1,47287.72,0.0,fully paid,8466.0,3 years,2783.880000,debt consolidation,0.0
37498,169610,V,4-9,Not Vfied,52800.00,OWN,3,0,48.0480,15390.00,...,137.772,other-1,107614.80,0.0,whole,17264.0,3 years,29280.658815,home improvement,0.0
37499,175557,II,>10yrs,Vfied,121440.00,MOR??AGE,0,0,27.2664,24624.00,...,104.060,other-1,783477.16,0.0,fully paid,47310.0,3 years,29504.340000,debt consolidation,0.0

In [77]:
df['Loan/No Loan'] = model.predict(df.drop('ID',axis=1))
df

,ID,GGGrade,Experience,Validation,Yearly Income,Home Status,Unpaid 2 years,Already Defaulted,Debt to Income,Lend Amount,...,Inquiries,Present Balance,Gross Collection,File Status,Total Unpaid CL,Duration,Unpaid Amount,Reason,Due Fee,Loan/No Loan
0,198980,II,1-3,Vfied,140800.00,OWN,0,0,16.9176,17955.00,...,other-1,59769.30,0.0,fully paid,33532.0,3 years,15755.940000,major purchase,0.0,0
1,167688,II,>10yrs,Vfied,146080.00,MOR??AGE,0,0,28.6944,59850.00,...,other-1,532962.13,0.0,whole,149234.0,5 years,68237.550000,debt consolidation,0.0,0
2,198768,V,>10yrs,Vfied,202222.24,MOR??AGE,0,0,51.1560,59850.00,...,other-1,288816.48,0.0,whole,70218.0,5 years,66272.760000,debt consolidation,0.0,0
3,192564,II,>10yrs,Vfied,105600.00,MOR??AGE,1,0,27.0144,19323.00,...,other-1,424664.30,0.0,fully paid,79182.0,3 years,15595.200000,credit card,0.0,0
4,151199,III,4-9,Not Vfied,151360.00,MOR??AGE,0,0,10.3824,25350.75,...,other-1,251704.07,0.0,fully paid,13612.0,3 years,8850.960000,debt consolidation,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37495,191405,IV,4-9,Vfied,308000.00,MOR??AGE,1,0,29.4336,59850.00,...,other-1,848107.83,0.0,fully paid,132468.0,3 years,57683.430000,debt consolidation,0.0,0
37496,164868,IV,4-9,Vfied,158400.00,MOR??AGE,0,0,31.6008,28215.00,...,other-1,614710.30,0.0,fully paid,51958.0,5 years,51395.760000,credit card,0.0,0
37497,163156,V,>10yrs,Not Vfied,52800.00,OWN,0,0,46.9728,4916.25,...,other-1,47287.72,0.0,fully paid,8466.0,3 years,2783.880000,debt consolidation,0.0,0
37498,169610,V,4-9,Not Vfied,52800.00,OWN,3,0,48.0480,15390.00,...,other-1,107614.80,0.0,whole,17264.0,3 years,29280.658815,home improvement,0.0,0
37499,175557,II,>10yrs,Vfied,121440.00,MOR??AGE,0,0,27.2664,24624.00,...,other-1,783477.16,0.0,fully paid,47310.0,3 years,29504.340000,debt consolidation,0.0,0

In [78]:
df2=df[['ID','Loan/No Loan']]
df2['ID'] = df2['ID'].astype('int64')
df2['Loan/No Loan'] = df2['Loan/No Loan'].astype('int64')
df2

C:\Users\cools\AppData\Local\Temp/ipykernel_14596/3842719934.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['ID'] = df2['ID'].astype('int64')
C:\Users\cools\AppData\Local\Temp/ipykernel_14596/3842719934.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Loan/No Loan'] = df2['Loan/No Loan'].astype('int64')

           ID  Loan/No Loan
0      198980             0
1      167688             0
2      198768             0
3      192564             0
4      151199             0
...       ...           ...
37495  191405             0
37496  164868             0
37497  163156             0
37498  169610             0
37499  175557             0

[37500 rows x 2 columns]

In [79]:
df = pd.read_csv('Data_Test.csv')
df

,ID,Asst_Reg,GGGrade,Experience,Validation,Yearly Income,Home Status,Unpaid 2 years,Already Defaulted,Designation,...,Sub GGGrade,File Status,State,Account Open,Total Unpaid CL,Duration,Unpaid Amount,Reason,Claim Type,Due Fee
0,198980,1773284,II,2yrs,Source Verified,140800.00,OWN,0,0,processor,...,17,fully paid,California,23,33532.0,3 years,15755.94,major purchase,I,0.0
1,167688,5298273,II,>10yrs,Vfied,146080.00,MOR??AGE,0,0,Speech Language Pathologist,...,19,whole,Florida,17,149234.0,5 years,68237.55,debt consolidation,I,0.0
2,198768,189781,VI,>10yrs,Vfied,202222.24,MOR??AGE,0,0,Raytheon,...,37,whole,NM,15,70218.0,5 years,66272.76,debt consolidation,I,0.0
3,192564,1530906,II,>10yrs,Vfied,105600.00,MOR??AGE,1,0,Computer/Network Technician,...,19,fully paid,DE,18,79182.0,3 years,15595.20,credit card,I,0.0
4,151199,4410316,III,4yrs,Not Vfied,151360.00,MOR??AGE,0,0,NDE Tech,...,25,fully paid,Florida,7,13612.0,3 years,8850.96,debt consolidation,I,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37495,191405,5774816,IV,4yrs,Vfied,308000.00,MOR??AGE,1,0,Regional Manager,...,29,fully paid,California,19,132468.0,3 years,57683.43,debt consolidation,I,0.0
37496,164868,1423834,IV,8yrs,Source Verified,158400.00,MOR??AGE,0,0,Clinical Coordinator,...,28,fully paid,PA,14,51958.0,5 years,51395.76,credit card,I,0.0
37497,163156,1895531,V,>10yrs,Not Vfied,52800.00,OWN,0,0,administrative,...,33,fully paid,California,9,8466.0,3 years,2783.88,debt consolidation,I,0.0
37498,169610,2168910,VI,9yrs,Not Vfied,52800.00,OWN,5,0,ParaEducator,...,40,whole,TN,9,17264.0,3 years,NaN,home improvement,I,0.0
37499,175557,4140268,II,>10yrs,Source Verified,121440.00,MOR??AGE,0,0,School Teacher,...,19,fully paid,California,15,47310.0,3 years,29504.34,debt consolidation,I,0.0

In [80]:
df2['ID'] = df['ID']
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37500 entries, 0 to 37499
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            37500 non-null  int64
 1   Loan/No Loan  37500 non-null  int64
dtypes: int64(2)
memory usage: 586.1 KB

C:\Users\cools\AppData\Local\Temp/ipykernel_14596/2065228058.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['ID'] = df['ID']

In [81]:
df2.to_csv('file1.csv',index=0)