In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Data_Train.csv')
df

,ID,Asst_Reg,GGGrade,Experience,Validation,Yearly Income,Home Status,Unpaid 2 years,Already Defaulted,Designation,...,File Status,State,Account Open,Total Unpaid CL,Duration,Unpaid Amount,Reason,Claim Type,Due Fee,Loan/No Loan
0,95074,421802,II,>10yrs,Vfied,633600.00,MOR??AGE,0,0,GLENDALE NISSAN,...,fully paid,California,17,58598.0,3 years,31216.05,debt consolidation,I,0.0,0
1,134131,3964312,IV,7yrs,Source Verified,85483.20,REN?,0,0,Business Teacher,...,whole,NC,15,18924.0,5 years,11660.49,debt consolidation,I,0.0,0
2,92602,4247560,III,<1yr,Source Verified,79200.00,REN?,0,0,driver,...,whole,Florida,7,15604.0,5 years,5637.87,major purchase,I,0.0,0
3,22591,197179,III,<1yr,Vfied,61600.00,REN?,0,0,AvePoint,...,fully paid,NewJersey,9,22410.0,3 years,15607.17,major purchase,I,0.0,1
4,125060,4646684,V,2yrs,Source Verified,68053.92,REN?,0,0,Lead Tester,...,fully paid,LA,10,36022.0,5 years,27472.86,debt consolidation,I,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87495,120884,4535984,II,>10yrs,Not Vfied,75680.00,REN?,0,0,Engineer Support II,...,whole,MI,12,32702.0,3 years,10012.05,debt consolidation,I,0.0,0
87496,33259,2624710,IV,3yrs,Source Verified,90423.52,REN?,0,0,Dental Hygienist,...,whole,MA,23,32204.0,5 years,24921.54,debt consolidation,I,0.0,0
87497,102153,5966919,II,>10yrs,Source Verified,91520.00,MOR??AGE,0,0,Interface Coordinator,...,fully paid,CT,8,29050.0,3 years,14517.90,debt consolidation,I,0.0,0
87498,115343,2630667,III,1yrs,Source Verified,61600.00,MOR??AGE,0,0,PARTS CLERK,...,whole,PA,11,24900.0,3 years,8454.24,debt consolidation,I,0.0,0
87499,104968,6637289,III,2yrs,Vfied,NaN,REN?,0,0,Outside sales rep,...,whole,California,7,21746.0,5 years,8717.58,debt consolidation,I,0.0,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87500 entries, 0 to 87499
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   87500 non-null  int64
 1   Asst_Reg             87500 non-null  int64
 2   GGGrade              87500 non-null  object
 3   Experience           87500 non-null  object
 4   Validation           87500 non-null  object
 5   Yearly Income        81925 non-null  float64
 6   Home Status          87500 non-null  object
 7   Unpaid 2 years       87500 non-null  int64
 8   Already Defaulted    87500 non-null  int64
 9   Designation          86086 non-null  object
 10  Debt to Income       84011 non-null  float64
 11  Postal Code          86111 non-null  float64
 12  Lend Amount          87500 non-null  float64
 13  Deprecatory Records  87500 non-null  int64
 14  Interest Charged     87500 non-null  float64
 15  Usage Rate           87500 non-null  float64
 16  Inquiries            87500 non-null  int64
 17  Present Balance      87500 non-null  float64
 18  Gross Collection     87500 non-null  float64
 19  Sub GGGrade          87500 non-null  int64
 20  File Status          87500 non-null  object
 21  State                87500 non-null  object
 22  Account Open         87500 non-null  int64
 23  Total Unpaid CL      83314 non-null  float64
 24  Duration             87500 non-null  object
 25  Unpaid Amount        82648 non-null  float64
 26  Reason               87500 non-null  object
 27  Claim Type           87500 non-null  object
 28  Due Fee              87500 non-null  float64
 29  Loan/No Loan         87500 non-null  int64
dtypes: float64(11), int64(9), object(10)
memory usage: 20.0+ MB

In [4]:
for feature in df.columns:
    print("--",feature,"--")
    print (df[feature].value_counts(normalize=True))
    print("\n\n")

-- ID --
95074     0.000011
102140    0.000011
102258    0.000011
80480     0.000011
39012     0.000011
            ...
79773     0.000011
40215     0.000011
61647     0.000011
76276     0.000011
104968    0.000011
Name: ID, Length: 87500, dtype: float64



-- Asst_Reg --
6238431    0.000034
7054989    0.000034
6428230    0.000034
4738693    0.000034
1195917    0.000034
             ...
6084772    0.000011
391671     0.000011
6095924    0.000011
4728725    0.000011
6637289    0.000011
Name: Asst_Reg, Length: 83966, dtype: float64



-- GGGrade --
II     0.285326
III    0.281737
I      0.161954
IV     0.158480
V      0.081760
VI     0.025051
VII    0.005691
Name: GGGrade, dtype: float64



-- Experience --
>10yrs    0.352560
2yrs      0.092160
3yrs      0.084000
<1yr      0.082389
1yrs      0.066891
5yrs      0.064263
4yrs      0.060846
7yrs      0.054423
8yrs      0.052617
6yrs      0.048629
9yrs      0.041223
Name: Experience, dtype: float64



-- Validation --
Source Verified    0.394331
Vfied              0.304480
Not Vfied          0.301189
Name: Validation, dtype: float64



-- Yearly Income --
105600.00    0.039194
88000.00     0.034898
114400.00    0.030381
123200.00    0.029417
70400.00     0.027904
               ...
108894.72    0.000012
179688.96    0.000012
62575.04     0.000012
168590.40    0.000012
90423.52     0.000012
Name: Yearly Income, Length: 6871, dtype: float64



-- Home Status --
MOR??AGE    0.504686
REN?        0.399017
OWN         0.096183
OTHER       0.000069
NONE        0.000046
Name: Home Status, dtype: float64



-- Unpaid 2 years --
0     0.797337
1     0.132617
2     0.041806
3     0.014560
4     0.006457
5     0.003143
6     0.001783
7     0.000766
8     0.000491
9     0.000297
10    0.000251
12    0.000171
11    0.000149
18    0.000046
14    0.000046
13    0.000034
16    0.000023
15    0.000023
Name: Unpaid 2 years, dtype: float64



-- Already Defaulted --
0    0.994686
1    0.005017
2    0.000251
6    0.000011
5    0.000011
4    0.000011
3    0.000011
Name: Already Defaulted, dtype: float64



-- Designation --
School Teacher                 0.018412
Super Lead                     0.015357
Nurse                          0.008631
RN                             0.007504
Owner                          0.007237
                                 ...
B.R. Amon and Sons             0.000012
Medical record technician      0.000012
Executive Field Assistant      0.000012
Speech language pathologist    0.000012
Outside sales rep              0.000012
Name: Designation, Length: 40354, dtype: float64



-- Debt to Income --
22.9824    0.000726
28.2240    0.000726
36.2880    0.000714
24.1920    0.000702
32.2560    0.000702
             ...
59.6736    0.000012
64.9152    0.000012
0.5880     0.000012
65.2344    0.000012
63.6888    0.000012
Name: Debt to Income, Length: 3964, dtype: float64



-- Postal Code --
75000.0    0.011346
94500.0    0.010742
11200.0    0.010486
60600.0    0.009778
33100.0    0.008988
             ...
4300.0     0.000012
90100.0    0.000012
50000.0    0.000012
96500.0    0.000012
83800.0    0.000012
Name: Postal Code, Length: 865, dtype: float64



-- Lend Amount --
17100.00    0.069909
20520.00    0.056514
34200.00    0.055749
25650.00    0.055269
59850.00    0.043794
              ...
56900.25    0.000011
55275.75    0.000011
1923.75     0.000011
45400.50    0.000011
52796.25    0.000011
Name: Lend Amount, Length: 1298, dtype: float64



-- Deprecatory Records --
0     0.843737
1     0.129760
2     0.016926
3     0.005314
4     0.002206
5     0.000971
6     0.000446
7     0.000274
8     0.000160
10    0.000080
9     0.000034
16    0.000023
12    0.000011
86    0.000011
11    0.000011
13    0.000011
22    0.000011
15    0.000011
Name: Deprecatory Records, dtype: float64



-- Interest Charged --
14.56    0.000857
15.69    0.000846
9.53     0.000846
23.65    0.000834
12.57    0.000834
           ...
13.00    0.000389
16.20    0.000377
8.00     0.000354
9.93     0.000354
25.00    0.000286
Name: Interest Charged, Length: 1701, dtype: float64



-- Usage Rate --
0.000      0.002697
113.520    0.002400
91.160     0.002354
99.760     0.002343
96.320     0.002103
             ...
194.360    0.000011
179.740    0.000011
193.672    0.000011
189.716    0.000011
222.740    0.000011
Name: Usage Rate, Length: 1088, dtype: float64



-- Inquiries --
0    0.569749
1    0.269726
2    0.103314
3    0.040423
4    0.012069
5    0.003600
6    0.001109
8    0.000011
Name: Inquiries, dtype: float64



-- Present Balance --
0.00         0.000160
39779.40     0.000069
22114.14     0.000069
40570.98     0.000069
43530.22     0.000069
               ...
262744.44    0.000011
191517.27    0.000011
114039.29    0.000011
913563.48    0.000011
10445.85     0.000011
Name: Present Balance, Length: 73819, dtype: float64



-- Gross Collection --
0.00        0.980743
2080.72     0.000023
11.90       0.000023
5437.55     0.000023
1200.00     0.000023
              ...
1054.22     0.000011
803.04      0.000011
2108.94     0.000011
13832.92    0.000011
691.56      0.000011
Name: Gross Collection, Length: 1678, dtype: float64



-- Sub GGGrade --
19    0.062331
18    0.061291
22    0.059600
21    0.059131
23    0.057863
24    0.056651
17    0.055371
20    0.054949
16    0.051383
15    0.049497
25    0.048491
26    0.041760
14    0.037600
27    0.033840
28    0.030034
29    0.028697
13    0.025954
11    0.025051
30    0.024149
12    0.023851
31    0.020777
32    0.019737
33    0.016880
34    0.013440
35    0.010926
36    0.007749
37    0.005509
38    0.004994
39    0.003749
40    0.003051
41    0.002023
42    0.001383
43    0.001040
45    0.000663
44    0.000583
Name: Sub GGGrade, dtype: float64



-- File Status --
whole         0.529143
fully paid    0.470857
Name: File Status, dtype: float64



-- State --
California    0.144286
Newyork       0.082400
TX            0.081486
Florida       0.066434
IL            0.040023
NewJersey     0.037177
PA            0.036217
Ohio          0.033931
GA            0.033417
VA            0.029086
NC            0.028800
MI            0.025749
Maryland      0.023691
AZ            0.023520
MA            0.023143
CO            0.021509
WA            0.021257
MN            0.019120
IN            0.016377
MO            0.016114
TN            0.015554
CT            0.015143
NV            0.013394
AL            0.013029
WI            0.012754
OR            0.012000
LA            0.011646
SC            0.011486
KY            0.009383
KS            0.009360
OK            0.008754
AR            0.007429
UT            0.007303
NM            0.005680
HI            0.005314
NH            0.004880
MS            0.004686
WV            0.004434
RI            0.004251
MT            0.002960
DE            0.002720
DC            0.002686
AK            0.002526
WY            0.002126
SD            0.002069
VT            0.002034
NE            0.001531
ND            0.000571
ME            0.000560
Name: State, dtype: float64



-- Account Open --
11    0.090594
10    0.089040
9     0.083783
12    0.082526
13    0.074354
8     0.072011
14    0.065566
7     0.060457
15    0.055371
16    0.046206
6     0.041520
17    0.038514
18    0.032514
19    0.026000
5     0.023943
20    0.021406
21    0.016926
22    0.014343
23    0.011783
24    0.009097
4     0.008331
25    0.006743
26    0.005611
27    0.004057
28    0.003486
29    0.002971
3     0.002240
30    0.002114
31    0.001760
32    0.001326
33    0.001097
34    0.000869
35    0.000594
36    0.000537
37    0.000469
39    0.000274
38    0.000263
2     0.000206
40    0.000149
43    0.000137
41    0.000137
42    0.000126
49    0.000080
45    0.000080
44    0.000069
46    0.000046
48    0.000046
51    0.000034
50    0.000034
54    0.000034
56    0.000023
52    0.000023
80    0.000011
83    0.000011
63    0.000011
68    0.000011
57    0.000011
65    0.000011
47    0.000011
Name: Account Open, dtype: float64



-- Total Unpaid CL --
24070.00     0.003457
14110.00     0.003385
24900.00     0.003373
19090.00     0.003373
27390.00     0.003253
               ...
274232.00    0.000012
30226.94     0.000012
12101.40     0.000012
103972.44    0.000012
105859.86    0.000012
Name: Total Unpaid CL, Length: 4385, dtype: float64



-- Duration --
3 years    0.686411
5 years    0.313589
Name: Duration, dtype: float64



-- Unpaid Amount --
0.00        0.002190
11407.41    0.000169
25915.05    0.000157
12763.44    0.000145
8864.64     0.000145
              ...
68526.54    0.000012
28683.54    0.000012
76825.17    0.000012
50424.48    0.000012
52676.55    0.000012
Name: Unpaid Amount, Length: 34679, dtype: float64



-- Reason --
debt  consolidation    0.600674
credit  card           0.241166
home  improvement      0.055840
other                  0.043131
major  purchase        0.017280
medical                0.009383
small  business        0.008583
car                    0.008114
moving                 0.005749
vacation               0.004846
house                  0.003554
wedding                0.001246
renewable  energy      0.000434
Name: Reason, dtype: float64



-- Claim Type --
I    0.999474
J    0.000526
Name: Claim Type, dtype: float64



-- Due Fee --
0.00     0.988697
15.00    0.003143
30.00    0.000320
20.50    0.000046
44.03    0.000046
           ...
84.92    0.000011
28.18    0.000011
15.21    0.000011
38.02    0.000011
18.06    0.000011
Name: Due Fee, Length: 608, dtype: float64



-- Loan/No Loan --
0    0.811291
1    0.188709
Name: Loan/No Loan, dtype: float64

In [5]:
df['GGGrade'].replace('VII','VI',inplace=True)
df['GGGrade'].replace('VI','V',inplace=True)

In [6]:
df['GGGrade'].value_counts(normalize=True)

II     0.285326
III    0.281737
I      0.161954
IV     0.158480
V      0.112503
Name: GGGrade, dtype: float64

In [7]:
df['Experience'].value_counts(normalize=True)

>10yrs    0.352560
2yrs      0.092160
3yrs      0.084000
<1yr      0.082389
1yrs      0.066891
5yrs      0.064263
4yrs      0.060846
7yrs      0.054423
8yrs      0.052617
6yrs      0.048629
9yrs      0.041223
Name: Experience, dtype: float64

In [8]:
df['Experience'].replace('<1yr','1-3',inplace=True)
df['Experience'].replace('1yrs','1-3',inplace=True)
df['Experience'].replace('2yrs','1-3',inplace=True)
df['Experience'].replace('3yrs','1-3',inplace=True)

In [9]:
df['Experience'].replace('4yrs','4-9',inplace=True)
df['Experience'].replace('5yrs','4-9',inplace=True)
df['Experience'].replace('6yrs','4-9',inplace=True)
df['Experience'].replace('7yrs','4-9',inplace=True)
df['Experience'].replace('8yrs','4-9',inplace=True)
df['Experience'].replace('9yrs','4-9',inplace=True)

In [10]:
df['Validation'].value_counts(normalize=True)

Source Verified    0.394331
Vfied              0.304480
Not Vfied          0.301189
Name: Validation, dtype: float64

In [11]:
df['Validation'].replace('Source Verified','Vfied',inplace=True)

In [12]:
df['Home Status'].value_counts(normalize=True)

MOR??AGE    0.504686
REN?        0.399017
OWN         0.096183
OTHER       0.000069
NONE        0.000046
Name: Home Status, dtype: float64

In [13]:
df['Home Status'].replace('NONE','MOR??AGE',inplace=True)
df['Home Status'].replace('OTHER','MOR??AGE',inplace=True)

In [14]:
df['Unpaid 2 years'] = df['Unpaid 2 years'].astype(str)
df

,ID,Asst_Reg,GGGrade,Experience,Validation,Yearly Income,Home Status,Unpaid 2 years,Already Defaulted,Designation,...,File Status,State,Account Open,Total Unpaid CL,Duration,Unpaid Amount,Reason,Claim Type,Due Fee,Loan/No Loan
0,95074,421802,II,>10yrs,Vfied,633600.00,MOR??AGE,0,0,GLENDALE NISSAN,...,fully paid,California,17,58598.0,3 years,31216.05,debt consolidation,I,0.0,0
1,134131,3964312,IV,4-9,Vfied,85483.20,REN?,0,0,Business Teacher,...,whole,NC,15,18924.0,5 years,11660.49,debt consolidation,I,0.0,0
2,92602,4247560,III,1-3,Vfied,79200.00,REN?,0,0,driver,...,whole,Florida,7,15604.0,5 years,5637.87,major purchase,I,0.0,0
3,22591,197179,III,1-3,Vfied,61600.00,REN?,0,0,AvePoint,...,fully paid,NewJersey,9,22410.0,3 years,15607.17,major purchase,I,0.0,1
4,125060,4646684,V,1-3,Vfied,68053.92,REN?,0,0,Lead Tester,...,fully paid,LA,10,36022.0,5 years,27472.86,debt consolidation,I,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87495,120884,4535984,II,>10yrs,Not Vfied,75680.00,REN?,0,0,Engineer Support II,...,whole,MI,12,32702.0,3 years,10012.05,debt consolidation,I,0.0,0
87496,33259,2624710,IV,1-3,Vfied,90423.52,REN?,0,0,Dental Hygienist,...,whole,MA,23,32204.0,5 years,24921.54,debt consolidation,I,0.0,0
87497,102153,5966919,II,>10yrs,Vfied,91520.00,MOR??AGE,0,0,Interface Coordinator,...,fully paid,CT,8,29050.0,3 years,14517.90,debt consolidation,I,0.0,0
87498,115343,2630667,III,1-3,Vfied,61600.00,MOR??AGE,0,0,PARTS CLERK,...,whole,PA,11,24900.0,3 years,8454.24,debt consolidation,I,0.0,0
87499,104968,6637289,III,1-3,Vfied,NaN,REN?,0,0,Outside sales rep,...,whole,California,7,21746.0,5 years,8717.58,debt consolidation,I,0.0,0

In [15]:
df['Unpaid 2 years'].value_counts(normalize=True)

0     0.797337
1     0.132617
2     0.041806
3     0.014560
4     0.006457
5     0.003143
6     0.001783
7     0.000766
8     0.000491
9     0.000297
10    0.000251
12    0.000171
11    0.000149
18    0.000046
14    0.000046
13    0.000034
16    0.000023
15    0.000023
Name: Unpaid 2 years, dtype: float64

In [16]:
for i in range(df.shape[0]):
    if (df.loc[i,'Unpaid 2 years'] != '0') and (df.loc[i,'Unpaid 2 years'] != '1') and (df.loc[i,'Unpaid 2 years'] != '2'):
        df.loc[i,'Unpaid 2 years'] = 3

In [17]:
df['Already Defaulted'] = df['Already Defaulted'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87500 entries, 0 to 87499
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   87500 non-null  int64
 1   Asst_Reg             87500 non-null  int64
 2   GGGrade              87500 non-null  object
 3   Experience           87500 non-null  object
 4   Validation           87500 non-null  object
 5   Yearly Income        81925 non-null  float64
 6   Home Status          87500 non-null  object
 7   Unpaid 2 years       87500 non-null  object
 8   Already Defaulted    87500 non-null  object
 9   Designation          86086 non-null  object
 10  Debt to Income       84011 non-null  float64
 11  Postal Code          86111 non-null  float64
 12  Lend Amount          87500 non-null  float64
 13  Deprecatory Records  87500 non-null  int64
 14  Interest Charged     87500 non-null  float64
 15  Usage Rate           87500 non-null  float64
 16  Inquiries            87500 non-null  int64
 17  Present Balance      87500 non-null  float64
 18  Gross Collection     87500 non-null  float64
 19  Sub GGGrade          87500 non-null  int64
 20  File Status          87500 non-null  object
 21  State                87500 non-null  object
 22  Account Open         87500 non-null  int64
 23  Total Unpaid CL      83314 non-null  float64
 24  Duration             87500 non-null  object
 25  Unpaid Amount        82648 non-null  float64
 26  Reason               87500 non-null  object
 27  Claim Type           87500 non-null  object
 28  Due Fee              87500 non-null  float64
 29  Loan/No Loan         87500 non-null  int64
dtypes: float64(11), int64(7), object(12)
memory usage: 20.0+ MB

In [18]:
df['Already Defaulted'].value_counts(normalize=True)

0    0.994686
1    0.005017
2    0.000251
6    0.000011
5    0.000011
4    0.000011
3    0.000011
Name: Already Defaulted, dtype: float64

In [19]:
for i in range(df.shape[0]):
    if df.loc[i,'Already Defaulted'] != '0':
        df.loc[i,'Already Defaulted'] = '1'

In [20]:
df['Designation'].value_counts(normalize=True)

School Teacher                 0.018412
Super Lead                     0.015357
Nurse                          0.008631
RN                             0.007504
Owner                          0.007237
                                 ...
B.R. Amon and Sons             0.000012
Medical record technician      0.000012
Executive Field Assistant      0.000012
Speech language pathologist    0.000012
Outside sales rep              0.000012
Name: Designation, Length: 40354, dtype: float64

In [21]:
df['Postal Code'] = df['Postal Code'].astype(str)
df['Postal Code'].value_counts(normalize=True)

nan        0.015874
75000.0    0.011166
94500.0    0.010571
11200.0    0.010320
60600.0    0.009623
             ...
4300.0     0.000011
90100.0    0.000011
50000.0    0.000011
96500.0    0.000011
83800.0    0.000011
Name: Postal Code, Length: 866, dtype: float64

In [22]:
df['Deprecatory Records'] = df['Deprecatory Records'].astype(str)
df['Deprecatory Records'].value_counts(normalize=True)

0     0.843737
1     0.129760
2     0.016926
3     0.005314
4     0.002206
5     0.000971
6     0.000446
7     0.000274
8     0.000160
10    0.000080
9     0.000034
16    0.000023
12    0.000011
86    0.000011
11    0.000011
13    0.000011
22    0.000011
15    0.000011
Name: Deprecatory Records, dtype: float64

In [23]:
for i in range(df.shape[0]):
    if (df.loc[i,'Deprecatory Records'] != '0') and (df.loc[i,'Deprecatory Records'] != '1'):
        df.loc[i,'Deprecatory Records'] = '2'

In [24]:
df['Inquiries'] = df['Inquiries'].astype(str)
df['Inquiries'].value_counts(normalize=True)

0    0.569749
1    0.269726
2    0.103314
3    0.040423
4    0.012069
5    0.003600
6    0.001109
8    0.000011
Name: Inquiries, dtype: float64

In [25]:
for i in range(df.shape[0]):
    if (df.loc[i,'Inquiries'] != '0') and (df.loc[i,'Inquiries'] != '1') and (df.loc[i,'Inquiries'] != '2'):
        df.loc[i,'Inquiries'] = '3'

In [26]:
df['Reason'].value_counts(normalize=True)

debt  consolidation    0.600674
credit  card           0.241166
home  improvement      0.055840
other                  0.043131
major  purchase        0.017280
medical                0.009383
small  business        0.008583
car                    0.008114
moving                 0.005749
vacation               0.004846
house                  0.003554
wedding                0.001246
renewable  energy      0.000434
Name: Reason, dtype: float64

In [27]:
for i in range(df.shape[0]):
    if (df.loc[i,'Inquiries'] != 'debt  consolidation') and (df.loc[i,'Inquiries'] != 'credit  card') and (df.loc[i,'Inquiries'] != 'home  improvement') and (df.loc[i,'Inquiries'] != 'other'):
        df.loc[i,'Inquiries'] = 'other-1'

In [28]:
df.drop(['Designation','Asst_Reg','Postal Code','Claim Type'],axis=1,inplace=True)

In [29]:
df.drop(['Account Open', 'State', 'Sub GGGrade'],axis=1,inplace=True)

In [30]:
df.drop('ID',axis=1,inplace=True)

In [31]:
df.isnull().sum()

GGGrade                   0
Experience                0
Validation                0
Yearly Income          5575
Home Status               0
Unpaid 2 years            0
Already Defaulted         0
Debt to Income         3489
Lend Amount               0
Deprecatory Records       0
Interest Charged          0
Usage Rate                0
Inquiries                 0
Present Balance           0
Gross Collection          0
File Status               0
Total Unpaid CL        4186
Duration                  0
Unpaid Amount          4852
Reason                    0
Due Fee                   0
Loan/No Loan              0
dtype: int64

In [32]:
df['Loan/No Loan'].value_counts()

0    70988
1    16512
Name: Loan/No Loan, dtype: int64

In [33]:
df['Loan/No Loan'].value_counts(normalize=True)

0    0.811291
1    0.188709
Name: Loan/No Loan, dtype: float64

In [35]:
df['Yearly Income'].fillna(df['Yearly Income'].mean(),inplace=True)
df['Debt to Income'].fillna(df['Debt to Income'].mean(),inplace=True)
df['Total Unpaid CL'].fillna(df['Total Unpaid CL'].mean(),inplace=True)
df['Unpaid Amount'].fillna(df['Unpaid Amount'].mean(),inplace=True)

#df['Postal Code'].fillna(df['Postal Code'].value_counts().index[0],inplace=True)
#df['Designation'].fillna(df['Designation'].value_counts().index[0],inplace=True)

In [36]:
df.isnull().sum()

GGGrade                0
Experience             0
Validation             0
Yearly Income          0
Home Status            0
Unpaid 2 years         0
Already Defaulted      0
Debt to Income         0
Lend Amount            0
Deprecatory Records    0
Interest Charged       0
Usage Rate             0
Inquiries              0
Present Balance        0
Gross Collection       0
File Status            0
Total Unpaid CL        0
Duration               0
Unpaid Amount          0
Reason                 0
Due Fee                0
Loan/No Loan           0
dtype: int64

In [37]:
df.dropna(inplace=True)
df

,GGGrade,Experience,Validation,Yearly Income,Home Status,Unpaid 2 years,Already Defaulted,Debt to Income,Lend Amount,Deprecatory Records,...,Inquiries,Present Balance,Gross Collection,File Status,Total Unpaid CL,Duration,Unpaid Amount,Reason,Due Fee,Loan/No Loan
0,II,>10yrs,Vfied,633600.00000,MOR??AGE,0,0,12.5496,42023.25,0,...,other-1,607161.90,0.0,fully paid,58598.0,3 years,31216.05,debt consolidation,0.0,0
1,IV,4-9,Vfied,85483.20000,REN?,0,0,9.0048,38133.00,0,...,other-1,269234.06,0.0,whole,18924.0,5 years,11660.49,debt consolidation,0.0,0
2,III,1-3,Vfied,79200.00000,REN?,0,0,24.9144,17100.00,0,...,other-1,22476.53,0.0,whole,15604.0,5 years,5637.87,major purchase,0.0,0
3,III,1-3,Vfied,61600.00000,REN?,0,0,16.5816,5130.00,0,...,other-1,15242.09,0.0,fully paid,22410.0,3 years,15607.17,major purchase,0.0,1
4,V,1-3,Vfied,68053.92000,REN?,0,0,40.0512,19665.00,0,...,other-1,65433.94,0.0,fully paid,36022.0,5 years,27472.86,debt consolidation,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87495,II,>10yrs,Not Vfied,75680.00000,REN?,0,0,19.3200,10260.00,0,...,other-1,15100.14,0.0,whole,32702.0,3 years,10012.05,debt consolidation,0.0,0
87496,IV,1-3,Vfied,90423.52000,REN?,0,0,48.8208,27360.00,0,...,other-1,102811.88,0.0,whole,32204.0,5 years,24921.54,debt consolidation,0.0,0
87497,II,>10yrs,Vfied,91520.00000,MOR??AGE,0,0,7.7952,8550.00,2,...,other-1,14584.11,0.0,fully paid,29050.0,3 years,14517.90,debt consolidation,0.0,0
87498,III,1-3,Vfied,61600.00000,MOR??AGE,0,0,8.2992,23769.00,1,...,other-1,59281.66,0.0,whole,24900.0,3 years,8454.24,debt consolidation,0.0,0
87499,III,1-3,Vfied,134859.62978,REN?,0,0,15.1872,28471.50,1,...,other-1,10445.85,0.0,whole,21746.0,5 years,8717.58,debt consolidation,0.0,0

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 87500 entries, 0 to 87499
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   GGGrade              87500 non-null  object
 1   Experience           87500 non-null  object
 2   Validation           87500 non-null  object
 3   Yearly Income        87500 non-null  float64
 4   Home Status          87500 non-null  object
 5   Unpaid 2 years       87500 non-null  object
 6   Already Defaulted    87500 non-null  object
 7   Debt to Income       87500 non-null  float64
 8   Lend Amount          87500 non-null  float64
 9   Deprecatory Records  87500 non-null  object
 10  Interest Charged     87500 non-null  float64
 11  Usage Rate           87500 non-null  float64
 12  Inquiries            87500 non-null  object
 13  Present Balance      87500 non-null  float64
 14  Gross Collection     87500 non-null  float64
 15  File Status          87500 non-null  object
 16  Total Unpaid CL      87500 non-null  float64
 17  Duration             87500 non-null  object
 18  Unpaid Amount        87500 non-null  float64
 19  Reason               87500 non-null  object
 20  Due Fee              87500 non-null  float64
 21  Loan/No Loan         87500 non-null  int64
dtypes: float64(10), int64(1), object(11)
memory usage: 15.4+ MB

In [39]:
X = df.drop('Loan/No Loan', axis=1)

y = df['Loan/No Loan']

In [40]:
categorical_features_indices = np.where(X.dtypes == "object")[0]
categorical_features_indices

array([ 0,  1,  2,  4,  5,  6,  9, 12, 15, 17, 19], dtype=int64)

In [41]:
from catboost import CatBoostClassifier
clf = CatBoostClassifier(random_state=1,cat_features=categorical_features_indices)
model=clf.fit(X,y)

Learning rate set to 0.06953
0:	learn: 0.6568237	total: 340ms	remaining: 5m 40s
1:	learn: 0.6269913	total: 547ms	remaining: 4m 32s
2:	learn: 0.6028202	total: 816ms	remaining: 4m 31s
3:	learn: 0.5831101	total: 940ms	remaining: 3m 54s
4:	learn: 0.5658001	total: 1.18s	remaining: 3m 54s
5:	learn: 0.5519598	total: 1.28s	remaining: 3m 31s
6:	learn: 0.5395492	total: 1.5s	remaining: 3m 32s
7:	learn: 0.5295022	total: 1.59s	remaining: 3m 16s
8:	learn: 0.5195106	total: 1.78s	remaining: 3m 16s
9:	learn: 0.5119601	total: 1.92s	remaining: 3m 10s
10:	learn: 0.5052759	total: 2.18s	remaining: 3m 15s
11:	learn: 0.4989564	total: 2.43s	remaining: 3m 19s
12:	learn: 0.4937948	total: 2.65s	remaining: 3m 20s
13:	learn: 0.4894151	total: 2.86s	remaining: 3m 21s
14:	learn: 0.4858423	total: 3.09s	remaining: 3m 22s
15:	learn: 0.4823402	total: 3.27s	remaining: 3m 21s
16:	learn: 0.4793219	total: 3.48s	remaining: 3m 21s
17:	learn: 0.4763117	total: 3.68s	remaining: 3m 20s
18:	learn: 0.4739828	total: 3.87s	remaining: 3m 19s
19:	learn: 0.4720856	total: 4.08s	remaining: 3m 19s
20:	learn: 0.4707179	total: 4.25s	remaining: 3m 18s
21:	learn: 0.4690630	total: 4.44s	remaining: 3m 17s
22:	learn: 0.4677707	total: 4.62s	remaining: 3m 16s
23:	learn: 0.4668430	total: 4.75s	remaining: 3m 13s
24:	learn: 0.4661136	total: 4.88s	remaining: 3m 10s
25:	learn: 0.4653214	total: 5s	remaining: 3m 7s
26:	learn: 0.4648319	total: 5.08s	remaining: 3m 3s
27:	learn: 0.4641779	total: 5.26s	remaining: 3m 2s
28:	learn: 0.4632626	total: 5.44s	remaining: 3m 2s
29:	learn: 0.4626748	total: 5.62s	remaining: 3m 1s
30:	learn: 0.4620541	total: 5.8s	remaining: 3m 1s
31:	learn: 0.4615518	total: 5.99s	remaining: 3m 1s
32:	learn: 0.4611451	total: 6.17s	remaining: 3m
33:	learn: 0.4608517	total: 6.35s	remaining: 3m
34:	learn: 0.4602246	total: 6.55s	remaining: 3m
35:	learn: 0.4599608	total: 6.73s	remaining: 3m
36:	learn: 0.4595351	total: 6.92s	remaining: 3m
37:	learn: 0.4592080	total: 7.1s	remaining: 2m 59s
38:	learn: 0.4588979	total: 7.39s	remaining: 3m 2s
39:	learn: 0.4585881	total: 7.59s	remaining: 3m 2s
40:	learn: 0.4581511	total: 7.83s	remaining: 3m 3s
41:	learn: 0.4578315	total: 8.07s	remaining: 3m 4s
42:	learn: 0.4576810	total: 8.28s	remaining: 3m 4s
43:	learn: 0.4573831	total: 8.46s	remaining: 3m 3s
44:	learn: 0.4571250	total: 8.66s	remaining: 3m 3s
45:	learn: 0.4569074	total: 8.88s	remaining: 3m 4s
46:	learn: 0.4566826	total: 9.08s	remaining: 3m 4s
47:	learn: 0.4565173	total: 9.27s	remaining: 3m 3s
48:	learn: 0.4562436	total: 9.46s	remaining: 3m 3s
49:	learn: 0.4561018	total: 9.65s	remaining: 3m 3s
50:	learn: 0.4559335	total: 9.87s	remaining: 3m 3s
51:	learn: 0.4558216	total: 10s	remaining: 3m 3s
52:	learn: 0.4557136	total: 10.2s	remaining: 3m 2s
53:	learn: 0.4555549	total: 10.4s	remaining: 3m 1s
54:	learn: 0.4554400	total: 10.6s	remaining: 3m 2s
55:	learn: 0.4552381	total: 10.8s	remaining: 3m 2s
56:	learn: 0.4551143	total: 11s	remaining: 3m 2s
57:	learn: 0.4549203	total: 11.2s	remaining: 3m 1s
58:	learn: 0.4547810	total: 11.4s	remaining: 3m 1s
59:	learn: 0.4547205	total: 11.6s	remaining: 3m 2s
60:	learn: 0.4545962	total: 11.8s	remaining: 3m 1s
61:	learn: 0.4544535	total: 12s	remaining: 3m 2s
62:	learn: 0.4543348	total: 12.2s	remaining: 3m 1s
63:	learn: 0.4542479	total: 12.4s	remaining: 3m 1s
64:	learn: 0.4541280	total: 12.6s	remaining: 3m 1s
65:	learn: 0.4540485	total: 12.8s	remaining: 3m 1s
66:	learn: 0.4539640	total: 13s	remaining: 3m 1s
67:	learn: 0.4539172	total: 13.2s	remaining: 3m 1s
68:	learn: 0.4538315	total: 13.4s	remaining: 3m
69:	learn: 0.4537480	total: 13.6s	remaining: 3m
70:	learn: 0.4536962	total: 13.8s	remaining: 2m 59s
71:	learn: 0.4536070	total: 13.9s	remaining: 2m 59s
72:	learn: 0.4534933	total: 14.1s	remaining: 2m 58s
73:	learn: 0.4533544	total: 14.3s	remaining: 2m 59s
74:	learn: 0.4532455	total: 14.5s	remaining: 2m 59s
75:	learn: 0.4531960	total: 14.7s	remaining: 2m 58s
76:	learn: 0.4531183	total: 14.9s	remaining: 2m 58s
77:	learn: 0.4529357	total: 15.1s	remaining: 2m 58s
78:	learn: 0.4528643	total: 15.3s	remaining: 2m 57s
79:	learn: 0.4528532	total: 15.3s	remaining: 2m 56s
80:	learn: 0.4527065	total: 15.5s	remaining: 2m 56s
81:	learn: 0.4526386	total: 15.7s	remaining: 2m 56s
82:	learn: 0.4525209	total: 16s	remaining: 2m 56s
83:	learn: 0.4524692	total: 16.2s	remaining: 2m 56s
84:	learn: 0.4523583	total: 16.3s	remaining: 2m 55s
85:	learn: 0.4523296	total: 16.5s	remaining: 2m 55s
86:	learn: 0.4522385	total: 16.7s	remaining: 2m 55s
87:	learn: 0.4521063	total: 16.9s	remaining: 2m 54s
88:	learn: 0.4520056	total: 17s	remaining: 2m 54s
89:	learn: 0.4518805	total: 17.2s	remaining: 2m 53s
90:	learn: 0.4518422	total: 17.4s	remaining: 2m 53s
91:	learn: 0.4517764	total: 17.6s	remaining: 2m 53s
92:	learn: 0.4516912	total: 17.7s	remaining: 2m 52s
93:	learn: 0.4516171	total: 17.9s	remaining: 2m 52s
94:	learn: 0.4515413	total: 18.1s	remaining: 2m 52s
95:	learn: 0.4514481	total: 18.2s	remaining: 2m 51s
96:	learn: 0.4513574	total: 18.4s	remaining: 2m 51s
97:	learn: 0.4513204	total: 18.6s	remaining: 2m 51s
98:	learn: 0.4512412	total: 18.9s	remaining: 2m 51s
99:	learn: 0.4511471	total: 19s	remaining: 2m 51s
100:	learn: 0.4510726	total: 19.3s	remaining: 2m 51s
101:	learn: 0.4509975	total: 19.5s	remaining: 2m 51s
102:	learn: 0.4509035	total: 19.7s	remaining: 2m 51s
103:	learn: 0.4508518	total: 19.9s	remaining: 2m 51s
104:	learn: 0.4506774	total: 20.1s	remaining: 2m 51s
105:	learn: 0.4505662	total: 20.3s	remaining: 2m 51s
106:	learn: 0.4505295	total: 20.5s	remaining: 2m 51s
107:	learn: 0.4504875	total: 20.7s	remaining: 2m 51s
108:	learn: 0.4504426	total: 20.9s	remaining: 2m 51s
109:	learn: 0.4504002	total: 21.1s	remaining: 2m 50s
110:	learn: 0.4502890	total: 21.3s	remaining: 2m 50s
111:	learn: 0.4502091	total: 21.5s	remaining: 2m 50s
112:	learn: 0.4501659	total: 21.7s	remaining: 2m 50s
113:	learn: 0.4500762	total: 21.9s	remaining: 2m 50s
114:	learn: 0.4499541	total: 22.1s	remaining: 2m 50s
115:	learn: 0.4498665	total: 22.3s	remaining: 2m 49s
116:	learn: 0.4498122	total: 22.6s	remaining: 2m 50s
117:	learn: 0.4497635	total: 22.8s	remaining: 2m 50s
118:	learn: 0.4496922	total: 23s	remaining: 2m 50s
119:	learn: 0.4496619	total: 23.2s	remaining: 2m 49s
120:	learn: 0.4496084	total: 23.4s	remaining: 2m 49s
121:	learn: 0.4495720	total: 23.5s	remaining: 2m 49s
122:	learn: 0.4494915	total: 23.7s	remaining: 2m 49s
123:	learn: 0.4493954	total: 23.9s	remaining: 2m 48s
124:	learn: 0.4493248	total: 24.1s	remaining: 2m 48s
125:	learn: 0.4492869	total: 24.4s	remaining: 2m 49s
126:	learn: 0.4492210	total: 24.6s	remaining: 2m 49s
127:	learn: 0.4491965	total: 24.9s	remaining: 2m 49s
128:	learn: 0.4491478	total: 25s	remaining: 2m 48s
129:	learn: 0.4490777	total: 25.2s	remaining: 2m 48s
130:	learn: 0.4489389	total: 25.4s	remaining: 2m 48s
131:	learn: 0.4488431	total: 25.6s	remaining: 2m 48s
132:	learn: 0.4488024	total: 25.7s	remaining: 2m 47s
133:	learn: 0.4487565	total: 25.9s	remaining: 2m 47s
134:	learn: 0.4486930	total: 26.1s	remaining: 2m 47s
135:	learn: 0.4486152	total: 26.3s	remaining: 2m 47s
136:	learn: 0.4486135	total: 26.4s	remaining: 2m 46s
137:	learn: 0.4485434	total: 26.6s	remaining: 2m 46s
138:	learn: 0.4484882	total: 26.8s	remaining: 2m 46s
139:	learn: 0.4484836	total: 26.9s	remaining: 2m 45s
140:	learn: 0.4484031	total: 27.1s	remaining: 2m 45s
141:	learn: 0.4483727	total: 27.3s	remaining: 2m 44s
142:	learn: 0.4483393	total: 27.6s	remaining: 2m 45s
143:	learn: 0.4482710	total: 27.9s	remaining: 2m 45s
144:	learn: 0.4481893	total: 28.2s	remaining: 2m 46s
145:	learn: 0.4481693	total: 28.4s	remaining: 2m 46s
146:	learn: 0.4481087	total: 28.7s	remaining: 2m 46s
147:	learn: 0.4480601	total: 29s	remaining: 2m 46s
148:	learn: 0.4480000	total: 29.2s	remaining: 2m 46s
149:	learn: 0.4479445	total: 29.4s	remaining: 2m 46s
150:	learn: 0.4478861	total: 29.6s	remaining: 2m 46s
151:	learn: 0.4478232	total: 29.8s	remaining: 2m 46s
152:	learn: 0.4477463	total: 30s	remaining: 2m 46s
153:	learn: 0.4476097	total: 30.2s	remaining: 2m 46s
154:	learn: 0.4475248	total: 30.5s	remaining: 2m 46s
155:	learn: 0.4474529	total: 30.7s	remaining: 2m 45s
156:	learn: 0.4474233	total: 30.9s	remaining: 2m 45s
157:	learn: 0.4473489	total: 31.1s	remaining: 2m 45s

158:	learn: 0.4473222	total: 31.4s	remaining: 2m 45s
159:	learn: 0.4472221	total: 31.5s	remaining: 2m 45s
160:	learn: 0.4471147	total: 31.8s	remaining: 2m 45s
161:	learn: 0.4470627	total: 32.1s	remaining: 2m 45s
162:	learn: 0.4469394	total: 32.3s	remaining: 2m 45s
163:	learn: 0.4468686	total: 32.5s	remaining: 2m 45s
164:	learn: 0.4467891	total: 32.7s	remaining: 2m 45s
165:	learn: 0.4467683	total: 33s	remaining: 2m 45s
166:	learn: 0.4467378	total: 33.2s	remaining: 2m 45s
167:	learn: 0.4466684	total: 33.4s	remaining: 2m 45s
168:	learn: 0.4466190	total: 33.7s	remaining: 2m 45s
169:	learn: 0.4465710	total: 33.9s	remaining: 2m 45s
170:	learn: 0.4465256	total: 34.1s	remaining: 2m 45s
171:	learn: 0.4465247	total: 34.2s	remaining: 2m 44s
172:	learn: 0.4464339	total: 34.4s	remaining: 2m 44s
173:	learn: 0.4463385	total: 34.6s	remaining: 2m 44s
174:	learn: 0.4462803	total: 34.8s	remaining: 2m 44s
175:	learn: 0.4462348	total: 35s	remaining: 2m 44s
176:	learn: 0.4461925	total: 35.2s	remaining: 2m 43s
177:	learn: 0.4461001	total: 35.5s	remaining: 2m 43s
178:	learn: 0.4460422	total: 35.7s	remaining: 2m 43s
179:	learn: 0.4459832	total: 35.9s	remaining: 2m 43s
180:	learn: 0.4458825	total: 36.1s	remaining: 2m 43s
181:	learn: 0.4458172	total: 36.3s	remaining: 2m 43s
182:	learn: 0.4457511	total: 36.5s	remaining: 2m 42s
183:	learn: 0.4456696	total: 36.7s	remaining: 2m 42s
184:	learn: 0.4456439	total: 36.9s	remaining: 2m 42s
185:	learn: 0.4455901	total: 37.1s	remaining: 2m 42s
186:	learn: 0.4455285	total: 37.3s	remaining: 2m 42s
187:	learn: 0.4454292	total: 37.5s	remaining: 2m 41s
188:	learn: 0.4453381	total: 37.7s	remaining: 2m 41s
189:	learn: 0.4453179	total: 37.9s	remaining: 2m 41s
190:	learn: 0.4452227	total: 38.1s	remaining: 2m 41s
191:	learn: 0.4451590	total: 38.3s	remaining: 2m 41s
192:	learn: 0.4450975	total: 38.5s	remaining: 2m 41s
193:	learn: 0.4450125	total: 38.8s	remaining: 2m 41s
194:	learn: 0.4449762	total: 39s	remaining: 2m 40s
195:	learn: 0.4449592	total: 39.2s	remaining: 2m 40s
196:	learn: 0.4448984	total: 39.4s	remaining: 2m 40s
197:	learn: 0.4448959	total: 39.6s	remaining: 2m 40s
198:	learn: 0.4448644	total: 39.9s	remaining: 2m 40s
199:	learn: 0.4447943	total: 40.2s	remaining: 2m 40s
200:	learn: 0.4447798	total: 40.4s	remaining: 2m 40s
201:	learn: 0.4446832	total: 40.6s	remaining: 2m 40s
202:	learn: 0.4446522	total: 40.9s	remaining: 2m 40s
203:	learn: 0.4445552	total: 41.1s	remaining: 2m 40s
204:	learn: 0.4444942	total: 41.4s	remaining: 2m 40s
205:	learn: 0.4444598	total: 41.6s	remaining: 2m 40s
206:	learn: 0.4443831	total: 41.8s	remaining: 2m 40s
207:	learn: 0.4443211	total: 42.1s	remaining: 2m 40s
208:	learn: 0.4442275	total: 42.3s	remaining: 2m 39s
209:	learn: 0.4441683	total: 42.5s	remaining: 2m 39s
210:	learn: 0.4440647	total: 42.7s	remaining: 2m 39s
211:	learn: 0.4439796	total: 42.9s	remaining: 2m 39s
212:	learn: 0.4439124	total: 43.1s	remaining: 2m 39s
213:	learn: 0.4438842	total: 43.3s	remaining: 2m 39s
214:	learn: 0.4438326	total: 43.5s	remaining: 2m 38s
215:	learn: 0.4438015	total: 43.7s	remaining: 2m 38s
216:	learn: 0.4437603	total: 44s	remaining: 2m 38s
217:	learn: 0.4437534	total: 44.2s	remaining: 2m 38s
218:	learn: 0.4437125	total: 44.4s	remaining: 2m 38s
219:	learn: 0.4436764	total: 44.6s	remaining: 2m 38s
220:	learn: 0.4435998	total: 44.8s	remaining: 2m 37s
221:	learn: 0.4435454	total: 45s	remaining: 2m 37s
222:	learn: 0.4435213	total: 45.3s	remaining: 2m 37s
223:	learn: 0.4434392	total: 45.5s	remaining: 2m 37s
224:	learn: 0.4433594	total: 45.7s	remaining: 2m 37s
225:	learn: 0.4433069	total: 45.9s	remaining: 2m 37s
226:	learn: 0.4432233	total: 46.1s	remaining: 2m 37s
227:	learn: 0.4432158	total: 46.4s	remaining: 2m 36s
228:	learn: 0.4431720	total: 46.6s	remaining: 2m 36s
229:	learn: 0.4431024	total: 46.8s	remaining: 2m 36s
230:	learn: 0.4430564	total: 47s	remaining: 2m 36s
231:	learn: 0.4429930	total: 47.2s	remaining: 2m 36s
232:	learn: 0.4429214	total: 47.4s	remaining: 2m 36s
233:	learn: 0.4428695	total: 47.6s	remaining: 2m 35s
234:	learn: 0.4427815	total: 47.8s	remaining: 2m 35s
235:	learn: 0.4426840	total: 48s	remaining: 2m 35s
236:	learn: 0.4426403	total: 48.2s	remaining: 2m 35s
237:	learn: 0.4426155	total: 48.4s	remaining: 2m 35s
238:	learn: 0.4425828	total: 48.6s	remaining: 2m 34s
239:	learn: 0.4425274	total: 48.8s	remaining: 2m 34s
240:	learn: 0.4424723	total: 49.1s	remaining: 2m 34s
241:	learn: 0.4424229	total: 49.3s	remaining: 2m 34s
242:	learn: 0.4423910	total: 49.5s	remaining: 2m 34s
243:	learn: 0.4423060	total: 49.7s	remaining: 2m 34s
244:	learn: 0.4422338	total: 50s	remaining: 2m 33s
245:	learn: 0.4421660	total: 50.2s	remaining: 2m 33s
246:	learn: 0.4421083	total: 50.4s	remaining: 2m 33s
247:	learn: 0.4420843	total: 50.7s	remaining: 2m 33s
248:	learn: 0.4420496	total: 50.9s	remaining: 2m 33s
249:	learn: 0.4420155	total: 51.1s	remaining: 2m 33s
250:	learn: 0.4419347	total: 51.3s	remaining: 2m 33s
251:	learn: 0.4418728	total: 51.5s	remaining: 2m 32s
252:	learn: 0.4418639	total: 51.8s	remaining: 2m 32s
253:	learn: 0.4418332	total: 52s	remaining: 2m 32s
254:	learn: 0.4418148	total: 52.2s	remaining: 2m 32s
255:	learn: 0.4417233	total: 52.4s	remaining: 2m 32s
256:	learn: 0.4417070	total: 52.6s	remaining: 2m 32s
257:	learn: 0.4416322	total: 52.8s	remaining: 2m 31s
258:	learn: 0.4415814	total: 53s	remaining: 2m 31s
259:	learn: 0.4415680	total: 53.2s	remaining: 2m 31s
260:	learn: 0.4414936	total: 53.5s	remaining: 2m 31s
261:	learn: 0.4414834	total: 53.7s	remaining: 2m 31s
262:	learn: 0.4414333	total: 53.9s	remaining: 2m 30s
263:	learn: 0.4414197	total: 54.1s	remaining: 2m 30s
264:	learn: 0.4413884	total: 54.3s	remaining: 2m 30s
265:	learn: 0.4413148	total: 54.5s	remaining: 2m 30s
266:	learn: 0.4413025	total: 54.7s	remaining: 2m 30s
267:	learn: 0.4412759	total: 54.9s	remaining: 2m 30s
268:	learn: 0.4412276	total: 55.2s	remaining: 2m 29s
269:	learn: 0.4412042	total: 55.4s	remaining: 2m 29s
270:	learn: 0.4410878	total: 55.6s	remaining: 2m 29s
271:	learn: 0.4410246	total: 55.8s	remaining: 2m 29s
272:	learn: 0.4410065	total: 56.1s	remaining: 2m 29s
273:	learn: 0.4409356	total: 56.3s	remaining: 2m 29s
274:	learn: 0.4409015	total: 56.6s	remaining: 2m 29s
275:	learn: 0.4407859	total: 56.8s	remaining: 2m 28s
276:	learn: 0.4407394	total: 57s	remaining: 2m 28s
277:	learn: 0.4406802	total: 57.3s	remaining: 2m 28s
278:	learn: 0.4406213	total: 57.5s	remaining: 2m 28s
279:	learn: 0.4405633	total: 57.7s	remaining: 2m 28s
280:	learn: 0.4404844	total: 57.9s	remaining: 2m 28s
281:	learn: 0.4404726	total: 58.1s	remaining: 2m 28s
282:	learn: 0.4404518	total: 58.4s	remaining: 2m 27s
283:	learn: 0.4404075	total: 58.5s	remaining: 2m 27s
284:	learn: 0.4403578	total: 58.8s	remaining: 2m 27s
285:	learn: 0.4403186	total: 59s	remaining: 2m 27s
286:	learn: 0.4402638	total: 59.3s	remaining: 2m 27s
287:	learn: 0.4402615	total: 59.5s	remaining: 2m 27s
288:	learn: 0.4402303	total: 59.7s	remaining: 2m 26s
289:	learn: 0.4402056	total: 59.9s	remaining: 2m 26s
290:	learn: 0.4401163	total: 1m	remaining: 2m 26s
291:	learn: 0.4400955	total: 1m	remaining: 2m 26s
292:	learn: 0.4400182	total: 1m	remaining: 2m 25s
293:	learn: 0.4399609	total: 1m	remaining: 2m 25s
294:	learn: 0.4399360	total: 1m	remaining: 2m 25s
295:	learn: 0.4399190	total: 1m 1s	remaining: 2m 25s
296:	learn: 0.4399093	total: 1m 1s	remaining: 2m 24s
297:	learn: 0.4398742	total: 1m 1s	remaining: 2m 24s
298:	learn: 0.4398293	total: 1m 1s	remaining: 2m 24s
299:	learn: 0.4397552	total: 1m 1s	remaining: 2m 24s
300:	learn: 0.4397033	total: 1m 2s	remaining: 2m 24s
301:	learn: 0.4395954	total: 1m 2s	remaining: 2m 23s
302:	learn: 0.4395737	total: 1m 2s	remaining: 2m 23s
303:	learn: 0.4395709	total: 1m 2s	remaining: 2m 23s
304:	learn: 0.4395004	total: 1m 2s	remaining: 2m 23s
305:	learn: 0.4394185	total: 1m 3s	remaining: 2m 23s
306:	learn: 0.4393717	total: 1m 3s	remaining: 2m 22s
307:	learn: 0.4392947	total: 1m 3s	remaining: 2m 22s
308:	learn: 0.4392503	total: 1m 3s	remaining: 2m 22s
309:	learn: 0.4392315	total: 1m 3s	remaining: 2m 22s
310:	learn: 0.4392062	total: 1m 4s	remaining: 2m 22s
311:	learn: 0.4391349	total: 1m 4s	remaining: 2m 22s
312:	learn: 0.4390550	total: 1m 4s	remaining: 2m 21s
313:	learn: 0.4389704	total: 1m 4s	remaining: 2m 21s
314:	learn: 0.4389074	total: 1m 5s	remaining: 2m 21s

315:	learn: 0.4388372	total: 1m 5s	remaining: 2m 21s
316:	learn: 0.4387713	total: 1m 5s	remaining: 2m 20s
317:	learn: 0.4387700	total: 1m 5s	remaining: 2m 20s
318:	learn: 0.4386927	total: 1m 5s	remaining: 2m 20s
319:	learn: 0.4386447	total: 1m 6s	remaining: 2m 20s
320:	learn: 0.4386425	total: 1m 6s	remaining: 2m 19s
321:	learn: 0.4386370	total: 1m 6s	remaining: 2m 19s
322:	learn: 0.4385407	total: 1m 6s	remaining: 2m 19s
323:	learn: 0.4384858	total: 1m 6s	remaining: 2m 19s
324:	learn: 0.4384385	total: 1m 6s	remaining: 2m 19s
325:	learn: 0.4384147	total: 1m 7s	remaining: 2m 18s
326:	learn: 0.4383623	total: 1m 7s	remaining: 2m 18s
327:	learn: 0.4383408	total: 1m 7s	remaining: 2m 18s
328:	learn: 0.4383045	total: 1m 7s	remaining: 2m 18s
329:	learn: 0.4382224	total: 1m 7s	remaining: 2m 18s
330:	learn: 0.4381666	total: 1m 8s	remaining: 2m 17s
331:	learn: 0.4381148	total: 1m 8s	remaining: 2m 17s
332:	learn: 0.4380481	total: 1m 8s	remaining: 2m 17s
333:	learn: 0.4379918	total: 1m 8s	remaining: 2m 17s
334:	learn: 0.4379530	total: 1m 8s	remaining: 2m 16s
335:	learn: 0.4379332	total: 1m 9s	remaining: 2m 16s
336:	learn: 0.4378652	total: 1m 9s	remaining: 2m 16s
337:	learn: 0.4378633	total: 1m 9s	remaining: 2m 16s
338:	learn: 0.4378208	total: 1m 9s	remaining: 2m 15s
339:	learn: 0.4377566	total: 1m 9s	remaining: 2m 15s
340:	learn: 0.4377342	total: 1m 10s	remaining: 2m 15s
341:	learn: 0.4376934	total: 1m 10s	remaining: 2m 15s
342:	learn: 0.4376694	total: 1m 10s	remaining: 2m 14s
343:	learn: 0.4375950	total: 1m 10s	remaining: 2m 14s
344:	learn: 0.4375926	total: 1m 10s	remaining: 2m 14s
345:	learn: 0.4375594	total: 1m 10s	remaining: 2m 14s
346:	learn: 0.4375019	total: 1m 11s	remaining: 2m 13s
347:	learn: 0.4374450	total: 1m 11s	remaining: 2m 13s
348:	learn: 0.4373751	total: 1m 11s	remaining: 2m 13s
349:	learn: 0.4373060	total: 1m 11s	remaining: 2m 12s
350:	learn: 0.4372714	total: 1m 11s	remaining: 2m 12s
351:	learn: 0.4372030	total: 1m 11s	remaining: 2m 12s
352:	learn: 0.4371537	total: 1m 12s	remaining: 2m 12s
353:	learn: 0.4370798	total: 1m 12s	remaining: 2m 11s
354:	learn: 0.4370082	total: 1m 12s	remaining: 2m 11s
355:	learn: 0.4369588	total: 1m 12s	remaining: 2m 11s
356:	learn: 0.4369055	total: 1m 12s	remaining: 2m 10s
357:	learn: 0.4368662	total: 1m 12s	remaining: 2m 10s
358:	learn: 0.4368368	total: 1m 13s	remaining: 2m 10s
359:	learn: 0.4367732	total: 1m 13s	remaining: 2m 10s
360:	learn: 0.4367196	total: 1m 13s	remaining: 2m 9s
361:	learn: 0.4367140	total: 1m 13s	remaining: 2m 9s
362:	learn: 0.4366796	total: 1m 13s	remaining: 2m 9s
363:	learn: 0.4366286	total: 1m 13s	remaining: 2m 9s
364:	learn: 0.4365900	total: 1m 14s	remaining: 2m 8s
365:	learn: 0.4365439	total: 1m 14s	remaining: 2m 8s
366:	learn: 0.4364822	total: 1m 14s	remaining: 2m 8s
367:	learn: 0.4364648	total: 1m 14s	remaining: 2m 8s
368:	learn: 0.4364203	total: 1m 14s	remaining: 2m 7s
369:	learn: 0.4363725	total: 1m 14s	remaining: 2m 7s
370:	learn: 0.4363480	total: 1m 15s	remaining: 2m 7s
371:	learn: 0.4363097	total: 1m 15s	remaining: 2m 7s
372:	learn: 0.4362601	total: 1m 15s	remaining: 2m 6s
373:	learn: 0.4362112	total: 1m 15s	remaining: 2m 6s
374:	learn: 0.4361335	total: 1m 15s	remaining: 2m 6s
375:	learn: 0.4360874	total: 1m 15s	remaining: 2m 5s
376:	learn: 0.4360746	total: 1m 16s	remaining: 2m 5s
377:	learn: 0.4360149	total: 1m 16s	remaining: 2m 5s
378:	learn: 0.4359740	total: 1m 16s	remaining: 2m 5s
379:	learn: 0.4359542	total: 1m 16s	remaining: 2m 4s
380:	learn: 0.4359247	total: 1m 16s	remaining: 2m 4s
381:	learn: 0.4358927	total: 1m 16s	remaining: 2m 4s
382:	learn: 0.4358046	total: 1m 17s	remaining: 2m 4s
383:	learn: 0.4357612	total: 1m 17s	remaining: 2m 3s
384:	learn: 0.4357470	total: 1m 17s	remaining: 2m 3s
385:	learn: 0.4357249	total: 1m 17s	remaining: 2m 3s
386:	learn: 0.4356721	total: 1m 17s	remaining: 2m 3s
387:	learn: 0.4355961	total: 1m 17s	remaining: 2m 2s
388:	learn: 0.4355484	total: 1m 18s	remaining: 2m 2s
389:	learn: 0.4355090	total: 1m 18s	remaining: 2m 2s
390:	learn: 0.4355036	total: 1m 18s	remaining: 2m 2s
391:	learn: 0.4354932	total: 1m 18s	remaining: 2m 2s
392:	learn: 0.4354729	total: 1m 18s	remaining: 2m 1s
393:	learn: 0.4354369	total: 1m 19s	remaining: 2m 1s
394:	learn: 0.4353734	total: 1m 19s	remaining: 2m 1s
395:	learn: 0.4353117	total: 1m 19s	remaining: 2m 1s
396:	learn: 0.4352507	total: 1m 19s	remaining: 2m
397:	learn: 0.4352262	total: 1m 19s	remaining: 2m
398:	learn: 0.4352012	total: 1m 19s	remaining: 2m
399:	learn: 0.4351464	total: 1m 20s	remaining: 2m
400:	learn: 0.4351383	total: 1m 20s	remaining: 1m 59s
401:	learn: 0.4350906	total: 1m 20s	remaining: 1m 59s
402:	learn: 0.4350234	total: 1m 20s	remaining: 1m 59s
403:	learn: 0.4349635	total: 1m 20s	remaining: 1m 59s
404:	learn: 0.4349332	total: 1m 20s	remaining: 1m 58s
405:	learn: 0.4349031	total: 1m 21s	remaining: 1m 58s
406:	learn: 0.4348341	total: 1m 21s	remaining: 1m 58s
407:	learn: 0.4347981	total: 1m 21s	remaining: 1m 58s
408:	learn: 0.4347419	total: 1m 21s	remaining: 1m 57s
409:	learn: 0.4346799	total: 1m 21s	remaining: 1m 57s
410:	learn: 0.4346666	total: 1m 21s	remaining: 1m 57s
411:	learn: 0.4346297	total: 1m 22s	remaining: 1m 57s
412:	learn: 0.4346059	total: 1m 22s	remaining: 1m 57s
413:	learn: 0.4345991	total: 1m 22s	remaining: 1m 56s
414:	learn: 0.4345446	total: 1m 22s	remaining: 1m 56s
415:	learn: 0.4345179	total: 1m 22s	remaining: 1m 56s
416:	learn: 0.4345077	total: 1m 23s	remaining: 1m 56s
417:	learn: 0.4344988	total: 1m 23s	remaining: 1m 55s
418:	learn: 0.4344061	total: 1m 23s	remaining: 1m 55s
419:	learn: 0.4343231	total: 1m 23s	remaining: 1m 55s
420:	learn: 0.4342477	total: 1m 23s	remaining: 1m 55s
421:	learn: 0.4341860	total: 1m 24s	remaining: 1m 55s
422:	learn: 0.4341332	total: 1m 24s	remaining: 1m 54s
423:	learn: 0.4341067	total: 1m 24s	remaining: 1m 54s
424:	learn: 0.4340971	total: 1m 24s	remaining: 1m 54s
425:	learn: 0.4340270	total: 1m 24s	remaining: 1m 54s
426:	learn: 0.4340030	total: 1m 24s	remaining: 1m 53s
427:	learn: 0.4339211	total: 1m 25s	remaining: 1m 53s
428:	learn: 0.4338877	total: 1m 25s	remaining: 1m 53s
429:	learn: 0.4338437	total: 1m 25s	remaining: 1m 53s
430:	learn: 0.4338057	total: 1m 25s	remaining: 1m 52s
431:	learn: 0.4337570	total: 1m 25s	remaining: 1m 52s
432:	learn: 0.4337128	total: 1m 25s	remaining: 1m 52s
433:	learn: 0.4336646	total: 1m 26s	remaining: 1m 52s
434:	learn: 0.4336105	total: 1m 26s	remaining: 1m 51s
435:	learn: 0.4335588	total: 1m 26s	remaining: 1m 51s
436:	learn: 0.4335459	total: 1m 26s	remaining: 1m 51s
437:	learn: 0.4334870	total: 1m 26s	remaining: 1m 51s
438:	learn: 0.4334295	total: 1m 26s	remaining: 1m 51s
439:	learn: 0.4333782	total: 1m 27s	remaining: 1m 50s
440:	learn: 0.4333358	total: 1m 27s	remaining: 1m 50s
441:	learn: 0.4332825	total: 1m 27s	remaining: 1m 50s
442:	learn: 0.4332727	total: 1m 27s	remaining: 1m 50s
443:	learn: 0.4332568	total: 1m 27s	remaining: 1m 49s
444:	learn: 0.4331894	total: 1m 27s	remaining: 1m 49s
445:	learn: 0.4331605	total: 1m 28s	remaining: 1m 49s
446:	learn: 0.4330926	total: 1m 28s	remaining: 1m 49s
447:	learn: 0.4330291	total: 1m 28s	remaining: 1m 48s
448:	learn: 0.4329679	total: 1m 28s	remaining: 1m 48s
449:	learn: 0.4329581	total: 1m 28s	remaining: 1m 48s
450:	learn: 0.4329147	total: 1m 28s	remaining: 1m 48s
451:	learn: 0.4328676	total: 1m 28s	remaining: 1m 47s
452:	learn: 0.4328177	total: 1m 29s	remaining: 1m 47s
453:	learn: 0.4328154	total: 1m 29s	remaining: 1m 47s
454:	learn: 0.4328064	total: 1m 29s	remaining: 1m 47s
455:	learn: 0.4327400	total: 1m 29s	remaining: 1m 46s
456:	learn: 0.4327259	total: 1m 29s	remaining: 1m 46s
457:	learn: 0.4326894	total: 1m 29s	remaining: 1m 46s
458:	learn: 0.4326644	total: 1m 30s	remaining: 1m 46s
459:	learn: 0.4326034	total: 1m 30s	remaining: 1m 45s
460:	learn: 0.4325422	total: 1m 30s	remaining: 1m 45s
461:	learn: 0.4324761	total: 1m 30s	remaining: 1m 45s
462:	learn: 0.4324429	total: 1m 30s	remaining: 1m 45s
463:	learn: 0.4323817	total: 1m 30s	remaining: 1m 44s
464:	learn: 0.4323654	total: 1m 31s	remaining: 1m 44s
465:	learn: 0.4323564	total: 1m 31s	remaining: 1m 44s
466:	learn: 0.4323386	total: 1m 31s	remaining: 1m 44s
467:	learn: 0.4323210	total: 1m 31s	remaining: 1m 43s
468:	learn: 0.4322587	total: 1m 31s	remaining: 1m 43s

469:	learn: 0.4322418	total: 1m 31s	remaining: 1m 43s
470:	learn: 0.4321802	total: 1m 31s	remaining: 1m 43s
471:	learn: 0.4321582	total: 1m 32s	remaining: 1m 42s
472:	learn: 0.4321509	total: 1m 32s	remaining: 1m 42s
473:	learn: 0.4321421	total: 1m 32s	remaining: 1m 42s
474:	learn: 0.4321394	total: 1m 32s	remaining: 1m 42s
475:	learn: 0.4321219	total: 1m 32s	remaining: 1m 41s
476:	learn: 0.4320683	total: 1m 32s	remaining: 1m 41s
477:	learn: 0.4320568	total: 1m 32s	remaining: 1m 41s
478:	learn: 0.4320282	total: 1m 33s	remaining: 1m 41s
479:	learn: 0.4320029	total: 1m 33s	remaining: 1m 40s
480:	learn: 0.4319723	total: 1m 33s	remaining: 1m 40s
481:	learn: 0.4319354	total: 1m 33s	remaining: 1m 40s
482:	learn: 0.4319291	total: 1m 33s	remaining: 1m 40s
483:	learn: 0.4319044	total: 1m 33s	remaining: 1m 40s
484:	learn: 0.4318631	total: 1m 33s	remaining: 1m 39s
485:	learn: 0.4318287	total: 1m 34s	remaining: 1m 39s
486:	learn: 0.4317781	total: 1m 34s	remaining: 1m 39s
487:	learn: 0.4317356	total: 1m 34s	remaining: 1m 39s
488:	learn: 0.4317010	total: 1m 34s	remaining: 1m 38s
489:	learn: 0.4316195	total: 1m 34s	remaining: 1m 38s
490:	learn: 0.4316013	total: 1m 34s	remaining: 1m 38s
491:	learn: 0.4315783	total: 1m 35s	remaining: 1m 38s
492:	learn: 0.4315495	total: 1m 35s	remaining: 1m 37s
493:	learn: 0.4315271	total: 1m 35s	remaining: 1m 37s
494:	learn: 0.4314815	total: 1m 35s	remaining: 1m 37s
495:	learn: 0.4314355	total: 1m 35s	remaining: 1m 37s
496:	learn: 0.4313543	total: 1m 35s	remaining: 1m 36s
497:	learn: 0.4313353	total: 1m 35s	remaining: 1m 36s
498:	learn: 0.4313157	total: 1m 36s	remaining: 1m 36s
499:	learn: 0.4313018	total: 1m 36s	remaining: 1m 36s
500:	learn: 0.4312645	total: 1m 36s	remaining: 1m 36s
501:	learn: 0.4312507	total: 1m 36s	remaining: 1m 35s
502:	learn: 0.4312226	total: 1m 36s	remaining: 1m 35s
503:	learn: 0.4311465	total: 1m 36s	remaining: 1m 35s
504:	learn: 0.4310660	total: 1m 37s	remaining: 1m 35s
505:	learn: 0.4310299	total: 1m 37s	remaining: 1m 34s
506:	learn: 0.4310214	total: 1m 37s	remaining: 1m 34s
507:	learn: 0.4310020	total: 1m 37s	remaining: 1m 34s
508:	learn: 0.4309518	total: 1m 37s	remaining: 1m 34s
509:	learn: 0.4309111	total: 1m 37s	remaining: 1m 34s
510:	learn: 0.4308491	total: 1m 38s	remaining: 1m 33s
511:	learn: 0.4307848	total: 1m 38s	remaining: 1m 33s
512:	learn: 0.4307312	total: 1m 38s	remaining: 1m 33s
513:	learn: 0.4307037	total: 1m 38s	remaining: 1m 33s
514:	learn: 0.4306645	total: 1m 38s	remaining: 1m 32s
515:	learn: 0.4306256	total: 1m 38s	remaining: 1m 32s
516:	learn: 0.4305805	total: 1m 38s	remaining: 1m 32s
517:	learn: 0.4305490	total: 1m 39s	remaining: 1m 32s
518:	learn: 0.4304994	total: 1m 39s	remaining: 1m 31s
519:	learn: 0.4304340	total: 1m 39s	remaining: 1m 31s
520:	learn: 0.4304214	total: 1m 39s	remaining: 1m 31s
521:	learn: 0.4304042	total: 1m 39s	remaining: 1m 31s
522:	learn: 0.4304001	total: 1m 39s	remaining: 1m 30s
523:	learn: 0.4303743	total: 1m 39s	remaining: 1m 30s
524:	learn: 0.4303651	total: 1m 40s	remaining: 1m 30s
525:	learn: 0.4303024	total: 1m 40s	remaining: 1m 30s
526:	learn: 0.4302519	total: 1m 40s	remaining: 1m 30s
527:	learn: 0.4302186	total: 1m 40s	remaining: 1m 29s
528:	learn: 0.4302178	total: 1m 40s	remaining: 1m 29s
529:	learn: 0.4301706	total: 1m 40s	remaining: 1m 29s
530:	learn: 0.4301306	total: 1m 41s	remaining: 1m 29s
531:	learn: 0.4300854	total: 1m 41s	remaining: 1m 28s
532:	learn: 0.4300489	total: 1m 41s	remaining: 1m 28s
533:	learn: 0.4300269	total: 1m 41s	remaining: 1m 28s
534:	learn: 0.4299903	total: 1m 41s	remaining: 1m 28s
535:	learn: 0.4299399	total: 1m 41s	remaining: 1m 28s
536:	learn: 0.4299249	total: 1m 41s	remaining: 1m 27s
537:	learn: 0.4298583	total: 1m 42s	remaining: 1m 27s
538:	learn: 0.4297994	total: 1m 42s	remaining: 1m 27s
539:	learn: 0.4297943	total: 1m 42s	remaining: 1m 27s
540:	learn: 0.4297874	total: 1m 42s	remaining: 1m 26s
541:	learn: 0.4297533	total: 1m 42s	remaining: 1m 26s
542:	learn: 0.4297045	total: 1m 42s	remaining: 1m 26s
543:	learn: 0.4296519	total: 1m 43s	remaining: 1m 26s
544:	learn: 0.4295890	total: 1m 43s	remaining: 1m 26s
545:	learn: 0.4295682	total: 1m 43s	remaining: 1m 25s
546:	learn: 0.4295427	total: 1m 43s	remaining: 1m 25s
547:	learn: 0.4294975	total: 1m 43s	remaining: 1m 25s
548:	learn: 0.4294649	total: 1m 43s	remaining: 1m 25s
549:	learn: 0.4294023	total: 1m 43s	remaining: 1m 25s
550:	learn: 0.4293699	total: 1m 44s	remaining: 1m 24s
551:	learn: 0.4293138	total: 1m 44s	remaining: 1m 24s
552:	learn: 0.4292519	total: 1m 44s	remaining: 1m 24s
553:	learn: 0.4292424	total: 1m 44s	remaining: 1m 24s
554:	learn: 0.4292069	total: 1m 44s	remaining: 1m 23s
555:	learn: 0.4291785	total: 1m 44s	remaining: 1m 23s
556:	learn: 0.4291350	total: 1m 44s	remaining: 1m 23s
557:	learn: 0.4291262	total: 1m 45s	remaining: 1m 23s
558:	learn: 0.4290621	total: 1m 45s	remaining: 1m 23s
559:	learn: 0.4290580	total: 1m 45s	remaining: 1m 22s
560:	learn: 0.4290076	total: 1m 45s	remaining: 1m 22s
561:	learn: 0.4289847	total: 1m 45s	remaining: 1m 22s
562:	learn: 0.4289483	total: 1m 45s	remaining: 1m 22s
563:	learn: 0.4289048	total: 1m 45s	remaining: 1m 21s
564:	learn: 0.4288642	total: 1m 46s	remaining: 1m 21s
565:	learn: 0.4288334	total: 1m 46s	remaining: 1m 21s
566:	learn: 0.4288014	total: 1m 46s	remaining: 1m 21s
567:	learn: 0.4287637	total: 1m 46s	remaining: 1m 21s
568:	learn: 0.4287221	total: 1m 46s	remaining: 1m 20s
569:	learn: 0.4286723	total: 1m 46s	remaining: 1m 20s
570:	learn: 0.4286592	total: 1m 47s	remaining: 1m 20s
571:	learn: 0.4286272	total: 1m 47s	remaining: 1m 20s
572:	learn: 0.4286267	total: 1m 47s	remaining: 1m 20s
573:	learn: 0.4285902	total: 1m 47s	remaining: 1m 19s
574:	learn: 0.4285572	total: 1m 47s	remaining: 1m 19s
575:	learn: 0.4285264	total: 1m 47s	remaining: 1m 19s
576:	learn: 0.4285080	total: 1m 48s	remaining: 1m 19s
577:	learn: 0.4285046	total: 1m 48s	remaining: 1m 18s
578:	learn: 0.4284454	total: 1m 48s	remaining: 1m 18s
579:	learn: 0.4284235	total: 1m 48s	remaining: 1m 18s
580:	learn: 0.4283808	total: 1m 48s	remaining: 1m 18s
581:	learn: 0.4283339	total: 1m 48s	remaining: 1m 18s
582:	learn: 0.4283296	total: 1m 48s	remaining: 1m 17s
583:	learn: 0.4282969	total: 1m 49s	remaining: 1m 17s
584:	learn: 0.4282774	total: 1m 49s	remaining: 1m 17s
585:	learn: 0.4282364	total: 1m 49s	remaining: 1m 17s
586:	learn: 0.4281922	total: 1m 49s	remaining: 1m 17s
587:	learn: 0.4281473	total: 1m 49s	remaining: 1m 16s
588:	learn: 0.4281347	total: 1m 49s	remaining: 1m 16s
589:	learn: 0.4280800	total: 1m 50s	remaining: 1m 16s
590:	learn: 0.4280792	total: 1m 50s	remaining: 1m 16s
591:	learn: 0.4280340	total: 1m 50s	remaining: 1m 16s
592:	learn: 0.4279833	total: 1m 50s	remaining: 1m 15s
593:	learn: 0.4279315	total: 1m 50s	remaining: 1m 15s
594:	learn: 0.4279230	total: 1m 50s	remaining: 1m 15s
595:	learn: 0.4279118	total: 1m 51s	remaining: 1m 15s
596:	learn: 0.4278889	total: 1m 51s	remaining: 1m 15s
597:	learn: 0.4278575	total: 1m 51s	remaining: 1m 14s
598:	learn: 0.4278297	total: 1m 51s	remaining: 1m 14s
599:	learn: 0.4277984	total: 1m 51s	remaining: 1m 14s
600:	learn: 0.4277658	total: 1m 51s	remaining: 1m 14s
601:	learn: 0.4277528	total: 1m 52s	remaining: 1m 14s
602:	learn: 0.4277392	total: 1m 52s	remaining: 1m 13s
603:	learn: 0.4277103	total: 1m 52s	remaining: 1m 13s
604:	learn: 0.4277052	total: 1m 52s	remaining: 1m 13s
605:	learn: 0.4276412	total: 1m 52s	remaining: 1m 13s
606:	learn: 0.4275999	total: 1m 52s	remaining: 1m 13s
607:	learn: 0.4275722	total: 1m 53s	remaining: 1m 12s
608:	learn: 0.4275240	total: 1m 53s	remaining: 1m 12s
609:	learn: 0.4274583	total: 1m 53s	remaining: 1m 12s
610:	learn: 0.4274129	total: 1m 53s	remaining: 1m 12s
611:	learn: 0.4273836	total: 1m 53s	remaining: 1m 12s
612:	learn: 0.4273423	total: 1m 53s	remaining: 1m 11s
613:	learn: 0.4273061	total: 1m 53s	remaining: 1m 11s
614:	learn: 0.4272489	total: 1m 54s	remaining: 1m 11s
615:	learn: 0.4272110	total: 1m 54s	remaining: 1m 11s
616:	learn: 0.4271551	total: 1m 54s	remaining: 1m 10s
617:	learn: 0.4271225	total: 1m 54s	remaining: 1m 10s
618:	learn: 0.4270712	total: 1m 54s	remaining: 1m 10s
619:	learn: 0.4270342	total: 1m 54s	remaining: 1m 10s
620:	learn: 0.4269797	total: 1m 54s	remaining: 1m 10s

621:	learn: 0.4269601	total: 1m 55s	remaining: 1m 9s
622:	learn: 0.4269028	total: 1m 55s	remaining: 1m 9s
623:	learn: 0.4268670	total: 1m 55s	remaining: 1m 9s
624:	learn: 0.4268149	total: 1m 55s	remaining: 1m 9s
625:	learn: 0.4267875	total: 1m 55s	remaining: 1m 9s
626:	learn: 0.4267646	total: 1m 55s	remaining: 1m 8s
627:	learn: 0.4267313	total: 1m 56s	remaining: 1m 8s
628:	learn: 0.4267129	total: 1m 56s	remaining: 1m 8s
629:	learn: 0.4266690	total: 1m 56s	remaining: 1m 8s
630:	learn: 0.4266543	total: 1m 56s	remaining: 1m 8s
631:	learn: 0.4266070	total: 1m 56s	remaining: 1m 7s
632:	learn: 0.4265509	total: 1m 56s	remaining: 1m 7s
633:	learn: 0.4265425	total: 1m 56s	remaining: 1m 7s
634:	learn: 0.4265396	total: 1m 57s	remaining: 1m 7s
635:	learn: 0.4265085	total: 1m 57s	remaining: 1m 7s
636:	learn: 0.4264996	total: 1m 57s	remaining: 1m 6s
637:	learn: 0.4264755	total: 1m 57s	remaining: 1m 6s
638:	learn: 0.4264512	total: 1m 57s	remaining: 1m 6s
639:	learn: 0.4264091	total: 1m 57s	remaining: 1m 6s
640:	learn: 0.4263766	total: 1m 57s	remaining: 1m 6s
641:	learn: 0.4263650	total: 1m 58s	remaining: 1m 5s
642:	learn: 0.4263551	total: 1m 58s	remaining: 1m 5s
643:	learn: 0.4263225	total: 1m 58s	remaining: 1m 5s
644:	learn: 0.4262842	total: 1m 58s	remaining: 1m 5s
645:	learn: 0.4262470	total: 1m 58s	remaining: 1m 5s
646:	learn: 0.4262182	total: 1m 58s	remaining: 1m 4s
647:	learn: 0.4261990	total: 1m 58s	remaining: 1m 4s
648:	learn: 0.4261817	total: 1m 59s	remaining: 1m 4s
649:	learn: 0.4261429	total: 1m 59s	remaining: 1m 4s
650:	learn: 0.4261215	total: 1m 59s	remaining: 1m 4s
651:	learn: 0.4260628	total: 1m 59s	remaining: 1m 3s
652:	learn: 0.4260223	total: 1m 59s	remaining: 1m 3s
653:	learn: 0.4259867	total: 1m 59s	remaining: 1m 3s
654:	learn: 0.4259755	total: 2m	remaining: 1m 3s
655:	learn: 0.4259524	total: 2m	remaining: 1m 3s
656:	learn: 0.4259228	total: 2m	remaining: 1m 2s
657:	learn: 0.4258659	total: 2m	remaining: 1m 2s
658:	learn: 0.4258051	total: 2m	remaining: 1m 2s
659:	learn: 0.4257375	total: 2m	remaining: 1m 2s
660:	learn: 0.4257190	total: 2m	remaining: 1m 2s
661:	learn: 0.4256852	total: 2m 1s	remaining: 1m 1s
662:	learn: 0.4256688	total: 2m 1s	remaining: 1m 1s
663:	learn: 0.4256552	total: 2m 1s	remaining: 1m 1s
664:	learn: 0.4256243	total: 2m 1s	remaining: 1m 1s
665:	learn: 0.4255771	total: 2m 1s	remaining: 1m
666:	learn: 0.4255297	total: 2m 1s	remaining: 1m
667:	learn: 0.4255161	total: 2m 1s	remaining: 1m
668:	learn: 0.4254695	total: 2m 2s	remaining: 1m
669:	learn: 0.4254596	total: 2m 2s	remaining: 1m
670:	learn: 0.4254171	total: 2m 2s	remaining: 60s
671:	learn: 0.4253486	total: 2m 2s	remaining: 59.8s
672:	learn: 0.4252943	total: 2m 2s	remaining: 59.6s
673:	learn: 0.4252628	total: 2m 2s	remaining: 59.4s
674:	learn: 0.4252142	total: 2m 2s	remaining: 59.2s
675:	learn: 0.4251754	total: 2m 3s	remaining: 59s
676:	learn: 0.4251271	total: 2m 3s	remaining: 58.8s
677:	learn: 0.4250867	total: 2m 3s	remaining: 58.6s
678:	learn: 0.4250291	total: 2m 3s	remaining: 58.4s
679:	learn: 0.4249768	total: 2m 3s	remaining: 58.2s
680:	learn: 0.4249280	total: 2m 3s	remaining: 58s
681:	learn: 0.4248806	total: 2m 4s	remaining: 57.9s
682:	learn: 0.4248350	total: 2m 4s	remaining: 57.7s
683:	learn: 0.4248223	total: 2m 4s	remaining: 57.5s
684:	learn: 0.4248118	total: 2m 4s	remaining: 57.3s
685:	learn: 0.4247822	total: 2m 4s	remaining: 57.1s
686:	learn: 0.4247788	total: 2m 4s	remaining: 56.9s
687:	learn: 0.4247428	total: 2m 5s	remaining: 56.7s
688:	learn: 0.4246981	total: 2m 5s	remaining: 56.5s
689:	learn: 0.4246775	total: 2m 5s	remaining: 56.3s
690:	learn: 0.4246567	total: 2m 5s	remaining: 56.1s
691:	learn: 0.4246084	total: 2m 5s	remaining: 55.9s
692:	learn: 0.4245664	total: 2m 5s	remaining: 55.7s
693:	learn: 0.4245595	total: 2m 5s	remaining: 55.5s
694:	learn: 0.4245187	total: 2m 6s	remaining: 55.3s
695:	learn: 0.4244802	total: 2m 6s	remaining: 55.1s
696:	learn: 0.4244754	total: 2m 6s	remaining: 54.9s
697:	learn: 0.4244700	total: 2m 6s	remaining: 54.7s
698:	learn: 0.4244420	total: 2m 6s	remaining: 54.6s
699:	learn: 0.4243999	total: 2m 6s	remaining: 54.4s
700:	learn: 0.4243736	total: 2m 6s	remaining: 54.2s
701:	learn: 0.4243419	total: 2m 7s	remaining: 54s
702:	learn: 0.4242808	total: 2m 7s	remaining: 53.8s
703:	learn: 0.4242635	total: 2m 7s	remaining: 53.6s
704:	learn: 0.4242066	total: 2m 7s	remaining: 53.4s
705:	learn: 0.4241721	total: 2m 7s	remaining: 53.2s
706:	learn: 0.4241297	total: 2m 7s	remaining: 53s
707:	learn: 0.4240986	total: 2m 8s	remaining: 52.9s
708:	learn: 0.4240452	total: 2m 8s	remaining: 52.6s
709:	learn: 0.4240160	total: 2m 8s	remaining: 52.5s
710:	learn: 0.4239821	total: 2m 8s	remaining: 52.3s
711:	learn: 0.4239654	total: 2m 8s	remaining: 52.1s
712:	learn: 0.4239167	total: 2m 8s	remaining: 51.9s
713:	learn: 0.4238709	total: 2m 9s	remaining: 51.7s
714:	learn: 0.4238148	total: 2m 9s	remaining: 51.5s
715:	learn: 0.4237983	total: 2m 9s	remaining: 51.3s
716:	learn: 0.4237893	total: 2m 9s	remaining: 51.1s
717:	learn: 0.4237630	total: 2m 9s	remaining: 51s
718:	learn: 0.4237181	total: 2m 9s	remaining: 50.8s
719:	learn: 0.4236795	total: 2m 10s	remaining: 50.6s
720:	learn: 0.4236533	total: 2m 10s	remaining: 50.4s
721:	learn: 0.4236247	total: 2m 10s	remaining: 50.2s
722:	learn: 0.4236132	total: 2m 10s	remaining: 50s
723:	learn: 0.4236030	total: 2m 10s	remaining: 49.8s
724:	learn: 0.4235724	total: 2m 10s	remaining: 49.6s
725:	learn: 0.4235138	total: 2m 10s	remaining: 49.4s
726:	learn: 0.4234509	total: 2m 11s	remaining: 49.2s
727:	learn: 0.4234165	total: 2m 11s	remaining: 49s
728:	learn: 0.4233568	total: 2m 11s	remaining: 48.8s
729:	learn: 0.4233334	total: 2m 11s	remaining: 48.6s
730:	learn: 0.4232747	total: 2m 11s	remaining: 48.4s
731:	learn: 0.4232664	total: 2m 11s	remaining: 48.2s
732:	learn: 0.4232571	total: 2m 11s	remaining: 48s
733:	learn: 0.4232130	total: 2m 12s	remaining: 47.9s
734:	learn: 0.4231733	total: 2m 12s	remaining: 47.6s
735:	learn: 0.4231677	total: 2m 12s	remaining: 47.5s
736:	learn: 0.4231098	total: 2m 12s	remaining: 47.3s
737:	learn: 0.4230726	total: 2m 12s	remaining: 47.1s
738:	learn: 0.4230234	total: 2m 12s	remaining: 46.9s
739:	learn: 0.4229870	total: 2m 12s	remaining: 46.7s
740:	learn: 0.4229597	total: 2m 13s	remaining: 46.5s
741:	learn: 0.4228996	total: 2m 13s	remaining: 46.3s
742:	learn: 0.4228629	total: 2m 13s	remaining: 46.1s
743:	learn: 0.4228222	total: 2m 13s	remaining: 45.9s
744:	learn: 0.4227975	total: 2m 13s	remaining: 45.7s
745:	learn: 0.4227569	total: 2m 13s	remaining: 45.6s
746:	learn: 0.4227367	total: 2m 13s	remaining: 45.4s
747:	learn: 0.4227150	total: 2m 14s	remaining: 45.2s
748:	learn: 0.4226940	total: 2m 14s	remaining: 45s
749:	learn: 0.4226802	total: 2m 14s	remaining: 44.8s
750:	learn: 0.4226480	total: 2m 14s	remaining: 44.6s
751:	learn: 0.4226265	total: 2m 14s	remaining: 44.4s
752:	learn: 0.4225928	total: 2m 14s	remaining: 44.2s
753:	learn: 0.4225352	total: 2m 14s	remaining: 44s
754:	learn: 0.4225032	total: 2m 14s	remaining: 43.8s
755:	learn: 0.4224284	total: 2m 14s	remaining: 43.6s
756:	learn: 0.4223868	total: 2m 15s	remaining: 43.4s
757:	learn: 0.4223358	total: 2m 15s	remaining: 43.2s
758:	learn: 0.4223093	total: 2m 15s	remaining: 43s
759:	learn: 0.4222517	total: 2m 15s	remaining: 42.8s
760:	learn: 0.4222263	total: 2m 15s	remaining: 42.6s
761:	learn: 0.4221881	total: 2m 15s	remaining: 42.4s
762:	learn: 0.4221646	total: 2m 15s	remaining: 42.2s
763:	learn: 0.4221274	total: 2m 15s	remaining: 42s
764:	learn: 0.4220596	total: 2m 16s	remaining: 41.8s
765:	learn: 0.4220549	total: 2m 16s	remaining: 41.6s
766:	learn: 0.4220329	total: 2m 16s	remaining: 41.4s
767:	learn: 0.4219989	total: 2m 16s	remaining: 41.2s
768:	learn: 0.4219584	total: 2m 16s	remaining: 41s
769:	learn: 0.4219274	total: 2m 16s	remaining: 40.9s
770:	learn: 0.4218852	total: 2m 16s	remaining: 40.7s
771:	learn: 0.4218817	total: 2m 16s	remaining: 40.5s
772:	learn: 0.4218752	total: 2m 17s	remaining: 40.3s
773:	learn: 0.4218442	total: 2m 17s	remaining: 40.1s
774:	learn: 0.4218258	total: 2m 17s	remaining: 39.9s
775:	learn: 0.4217834	total: 2m 17s	remaining: 39.7s
776:	learn: 0.4217476	total: 2m 17s	remaining: 39.5s
777:	learn: 0.4216817	total: 2m 17s	remaining: 39.3s
778:	learn: 0.4216218	total: 2m 17s	remaining: 39.1s
779:	learn: 0.4215822	total: 2m 17s	remaining: 38.9s

780:	learn: 0.4215513	total: 2m 18s	remaining: 38.7s
781:	learn: 0.4215040	total: 2m 18s	remaining: 38.6s
782:	learn: 0.4214946	total: 2m 18s	remaining: 38.4s
783:	learn: 0.4214773	total: 2m 18s	remaining: 38.2s
784:	learn: 0.4214358	total: 2m 18s	remaining: 38s
785:	learn: 0.4214000	total: 2m 18s	remaining: 37.8s
786:	learn: 0.4213816	total: 2m 18s	remaining: 37.6s
787:	learn: 0.4213486	total: 2m 19s	remaining: 37.4s
788:	learn: 0.4213334	total: 2m 19s	remaining: 37.2s
789:	learn: 0.4213189	total: 2m 19s	remaining: 37s
790:	learn: 0.4212915	total: 2m 19s	remaining: 36.9s
791:	learn: 0.4212845	total: 2m 19s	remaining: 36.7s
792:	learn: 0.4212673	total: 2m 19s	remaining: 36.5s
793:	learn: 0.4212427	total: 2m 19s	remaining: 36.3s
794:	learn: 0.4212204	total: 2m 20s	remaining: 36.1s
795:	learn: 0.4211773	total: 2m 20s	remaining: 35.9s
796:	learn: 0.4211345	total: 2m 20s	remaining: 35.7s
797:	learn: 0.4211137	total: 2m 20s	remaining: 35.6s
798:	learn: 0.4210743	total: 2m 20s	remaining: 35.4s
799:	learn: 0.4210534	total: 2m 20s	remaining: 35.2s
800:	learn: 0.4210365	total: 2m 20s	remaining: 35s
801:	learn: 0.4210096	total: 2m 20s	remaining: 34.8s
802:	learn: 0.4210000	total: 2m 21s	remaining: 34.6s
803:	learn: 0.4209800	total: 2m 21s	remaining: 34.4s
804:	learn: 0.4209467	total: 2m 21s	remaining: 34.2s
805:	learn: 0.4209349	total: 2m 21s	remaining: 34s
806:	learn: 0.4209160	total: 2m 21s	remaining: 33.9s
807:	learn: 0.4208642	total: 2m 21s	remaining: 33.7s
808:	learn: 0.4208463	total: 2m 21s	remaining: 33.5s
809:	learn: 0.4208422	total: 2m 21s	remaining: 33.3s
810:	learn: 0.4207989	total: 2m 22s	remaining: 33.1s
811:	learn: 0.4207580	total: 2m 22s	remaining: 32.9s
812:	learn: 0.4207031	total: 2m 22s	remaining: 32.8s
813:	learn: 0.4206815	total: 2m 22s	remaining: 32.6s
814:	learn: 0.4206683	total: 2m 22s	remaining: 32.4s
815:	learn: 0.4206547	total: 2m 22s	remaining: 32.2s
816:	learn: 0.4206329	total: 2m 22s	remaining: 32s
817:	learn: 0.4206093	total: 2m 23s	remaining: 31.8s
818:	learn: 0.4205987	total: 2m 23s	remaining: 31.6s
819:	learn: 0.4205940	total: 2m 23s	remaining: 31.5s
820:	learn: 0.4205715	total: 2m 23s	remaining: 31.3s
821:	learn: 0.4205546	total: 2m 23s	remaining: 31.1s
822:	learn: 0.4204998	total: 2m 23s	remaining: 30.9s
823:	learn: 0.4204564	total: 2m 23s	remaining: 30.7s
824:	learn: 0.4204324	total: 2m 24s	remaining: 30.6s
825:	learn: 0.4203933	total: 2m 24s	remaining: 30.4s
826:	learn: 0.4203742	total: 2m 24s	remaining: 30.2s
827:	learn: 0.4203329	total: 2m 24s	remaining: 30s
828:	learn: 0.4203158	total: 2m 24s	remaining: 29.8s
829:	learn: 0.4203023	total: 2m 24s	remaining: 29.7s
830:	learn: 0.4202620	total: 2m 24s	remaining: 29.5s
831:	learn: 0.4202533	total: 2m 25s	remaining: 29.3s
832:	learn: 0.4201844	total: 2m 25s	remaining: 29.1s
833:	learn: 0.4201645	total: 2m 25s	remaining: 28.9s
834:	learn: 0.4201020	total: 2m 25s	remaining: 28.8s
835:	learn: 0.4200861	total: 2m 25s	remaining: 28.6s
836:	learn: 0.4200319	total: 2m 25s	remaining: 28.4s
837:	learn: 0.4199589	total: 2m 25s	remaining: 28.2s
838:	learn: 0.4199333	total: 2m 26s	remaining: 28s
839:	learn: 0.4199239	total: 2m 26s	remaining: 27.8s
840:	learn: 0.4199033	total: 2m 26s	remaining: 27.7s
841:	learn: 0.4198818	total: 2m 26s	remaining: 27.5s
842:	learn: 0.4198445	total: 2m 26s	remaining: 27.3s
843:	learn: 0.4198322	total: 2m 26s	remaining: 27.1s
844:	learn: 0.4198295	total: 2m 26s	remaining: 26.9s
845:	learn: 0.4197939	total: 2m 26s	remaining: 26.7s
846:	learn: 0.4197635	total: 2m 27s	remaining: 26.6s
847:	learn: 0.4197541	total: 2m 27s	remaining: 26.4s
848:	learn: 0.4197487	total: 2m 27s	remaining: 26.2s
849:	learn: 0.4197378	total: 2m 27s	remaining: 26.1s
850:	learn: 0.4196558	total: 2m 27s	remaining: 25.9s
851:	learn: 0.4196204	total: 2m 27s	remaining: 25.7s
852:	learn: 0.4195839	total: 2m 28s	remaining: 25.5s
853:	learn: 0.4195730	total: 2m 28s	remaining: 25.3s
854:	learn: 0.4195424	total: 2m 28s	remaining: 25.2s
855:	learn: 0.4194993	total: 2m 28s	remaining: 25s
856:	learn: 0.4194910	total: 2m 28s	remaining: 24.8s
857:	learn: 0.4194435	total: 2m 28s	remaining: 24.6s
858:	learn: 0.4194111	total: 2m 28s	remaining: 24.4s
859:	learn: 0.4193721	total: 2m 29s	remaining: 24.3s
860:	learn: 0.4193674	total: 2m 29s	remaining: 24.1s
861:	learn: 0.4193350	total: 2m 29s	remaining: 23.9s
862:	learn: 0.4192913	total: 2m 29s	remaining: 23.7s
863:	learn: 0.4192785	total: 2m 29s	remaining: 23.6s
864:	learn: 0.4192429	total: 2m 29s	remaining: 23.4s
865:	learn: 0.4192061	total: 2m 29s	remaining: 23.2s
866:	learn: 0.4191501	total: 2m 30s	remaining: 23s
867:	learn: 0.4191358	total: 2m 30s	remaining: 22.8s
868:	learn: 0.4191147	total: 2m 30s	remaining: 22.7s
869:	learn: 0.4190988	total: 2m 30s	remaining: 22.5s
870:	learn: 0.4190934	total: 2m 30s	remaining: 22.3s
871:	learn: 0.4190424	total: 2m 30s	remaining: 22.1s
872:	learn: 0.4190307	total: 2m 30s	remaining: 21.9s
873:	learn: 0.4189653	total: 2m 30s	remaining: 21.8s
874:	learn: 0.4189327	total: 2m 31s	remaining: 21.6s
875:	learn: 0.4189052	total: 2m 31s	remaining: 21.4s
876:	learn: 0.4188762	total: 2m 31s	remaining: 21.2s
877:	learn: 0.4188380	total: 2m 31s	remaining: 21s
878:	learn: 0.4187759	total: 2m 31s	remaining: 20.9s
879:	learn: 0.4187457	total: 2m 31s	remaining: 20.7s
880:	learn: 0.4186956	total: 2m 31s	remaining: 20.5s
881:	learn: 0.4186640	total: 2m 32s	remaining: 20.3s
882:	learn: 0.4186581	total: 2m 32s	remaining: 20.2s
883:	learn: 0.4186524	total: 2m 32s	remaining: 20s
884:	learn: 0.4185921	total: 2m 32s	remaining: 19.8s
885:	learn: 0.4185573	total: 2m 32s	remaining: 19.6s
886:	learn: 0.4185025	total: 2m 32s	remaining: 19.4s
887:	learn: 0.4184791	total: 2m 32s	remaining: 19.3s
888:	learn: 0.4184446	total: 2m 32s	remaining: 19.1s
889:	learn: 0.4184196	total: 2m 33s	remaining: 18.9s
890:	learn: 0.4183877	total: 2m 33s	remaining: 18.7s
891:	learn: 0.4183842	total: 2m 33s	remaining: 18.6s
892:	learn: 0.4183521	total: 2m 33s	remaining: 18.4s
893:	learn: 0.4183378	total: 2m 33s	remaining: 18.2s
894:	learn: 0.4182846	total: 2m 33s	remaining: 18s
895:	learn: 0.4182757	total: 2m 33s	remaining: 17.9s
896:	learn: 0.4182512	total: 2m 34s	remaining: 17.7s
897:	learn: 0.4181988	total: 2m 34s	remaining: 17.5s
898:	learn: 0.4181663	total: 2m 34s	remaining: 17.3s
899:	learn: 0.4181378	total: 2m 34s	remaining: 17.2s
900:	learn: 0.4181054	total: 2m 34s	remaining: 17s
901:	learn: 0.4180972	total: 2m 34s	remaining: 16.8s
902:	learn: 0.4180588	total: 2m 34s	remaining: 16.6s
903:	learn: 0.4180515	total: 2m 34s	remaining: 16.5s
904:	learn: 0.4180142	total: 2m 35s	remaining: 16.3s
905:	learn: 0.4179696	total: 2m 35s	remaining: 16.1s
906:	learn: 0.4179116	total: 2m 35s	remaining: 15.9s
907:	learn: 0.4178958	total: 2m 35s	remaining: 15.8s
908:	learn: 0.4178589	total: 2m 35s	remaining: 15.6s
909:	learn: 0.4178077	total: 2m 35s	remaining: 15.4s
910:	learn: 0.4178034	total: 2m 35s	remaining: 15.2s
911:	learn: 0.4177965	total: 2m 36s	remaining: 15.1s
912:	learn: 0.4177901	total: 2m 36s	remaining: 14.9s
913:	learn: 0.4177558	total: 2m 36s	remaining: 14.7s
914:	learn: 0.4177393	total: 2m 36s	remaining: 14.5s
915:	learn: 0.4176773	total: 2m 36s	remaining: 14.4s
916:	learn: 0.4176668	total: 2m 36s	remaining: 14.2s
917:	learn: 0.4176352	total: 2m 36s	remaining: 14s
918:	learn: 0.4176250	total: 2m 36s	remaining: 13.8s
919:	learn: 0.4175865	total: 2m 37s	remaining: 13.7s
920:	learn: 0.4175811	total: 2m 37s	remaining: 13.5s
921:	learn: 0.4175508	total: 2m 37s	remaining: 13.3s
922:	learn: 0.4174938	total: 2m 37s	remaining: 13.1s
923:	learn: 0.4174492	total: 2m 37s	remaining: 13s
924:	learn: 0.4174314	total: 2m 37s	remaining: 12.8s
925:	learn: 0.4173959	total: 2m 37s	remaining: 12.6s
926:	learn: 0.4173421	total: 2m 37s	remaining: 12.4s
927:	learn: 0.4173087	total: 2m 38s	remaining: 12.3s
928:	learn: 0.4172986	total: 2m 38s	remaining: 12.1s
929:	learn: 0.4172497	total: 2m 38s	remaining: 11.9s
930:	learn: 0.4172284	total: 2m 38s	remaining: 11.7s
931:	learn: 0.4172186	total: 2m 38s	remaining: 11.6s
932:	learn: 0.4172167	total: 2m 38s	remaining: 11.4s
933:	learn: 0.4171794	total: 2m 38s	remaining: 11.2s
934:	learn: 0.4171599	total: 2m 38s	remaining: 11s
935:	learn: 0.4171280	total: 2m 39s	remaining: 10.9s
936:	learn: 0.4170655	total: 2m 39s	remaining: 10.7s

937:	learn: 0.4170275	total: 2m 39s	remaining: 10.5s
938:	learn: 0.4170013	total: 2m 39s	remaining: 10.4s
939:	learn: 0.4169735	total: 2m 39s	remaining: 10.2s
940:	learn: 0.4169387	total: 2m 39s	remaining: 10s
941:	learn: 0.4168852	total: 2m 39s	remaining: 9.84s
942:	learn: 0.4168613	total: 2m 39s	remaining: 9.67s
943:	learn: 0.4168532	total: 2m 40s	remaining: 9.5s
944:	learn: 0.4168228	total: 2m 40s	remaining: 9.32s
945:	learn: 0.4167927	total: 2m 40s	remaining: 9.15s
946:	learn: 0.4167837	total: 2m 40s	remaining: 8.98s
947:	learn: 0.4167782	total: 2m 40s	remaining: 8.81s
948:	learn: 0.4167486	total: 2m 40s	remaining: 8.64s
949:	learn: 0.4167355	total: 2m 40s	remaining: 8.47s
950:	learn: 0.4166927	total: 2m 40s	remaining: 8.29s
951:	learn: 0.4166695	total: 2m 41s	remaining: 8.12s
952:	learn: 0.4166283	total: 2m 41s	remaining: 7.95s
953:	learn: 0.4166122	total: 2m 41s	remaining: 7.78s
954:	learn: 0.4165632	total: 2m 41s	remaining: 7.61s
955:	learn: 0.4165478	total: 2m 41s	remaining: 7.44s
956:	learn: 0.4165054	total: 2m 41s	remaining: 7.27s
957:	learn: 0.4164989	total: 2m 41s	remaining: 7.1s
958:	learn: 0.4164448	total: 2m 42s	remaining: 6.93s
959:	learn: 0.4164233	total: 2m 42s	remaining: 6.76s
960:	learn: 0.4164051	total: 2m 42s	remaining: 6.58s
961:	learn: 0.4163837	total: 2m 42s	remaining: 6.41s
962:	learn: 0.4163465	total: 2m 42s	remaining: 6.24s
963:	learn: 0.4163208	total: 2m 42s	remaining: 6.07s
964:	learn: 0.4162820	total: 2m 42s	remaining: 5.91s
965:	learn: 0.4162256	total: 2m 42s	remaining: 5.74s
966:	learn: 0.4161837	total: 2m 43s	remaining: 5.56s
967:	learn: 0.4161794	total: 2m 43s	remaining: 5.39s
968:	learn: 0.4161573	total: 2m 43s	remaining: 5.23s
969:	learn: 0.4161042	total: 2m 43s	remaining: 5.06s
970:	learn: 0.4160878	total: 2m 43s	remaining: 4.89s
971:	learn: 0.4160416	total: 2m 43s	remaining: 4.72s
972:	learn: 0.4160333	total: 2m 43s	remaining: 4.55s
973:	learn: 0.4160245	total: 2m 44s	remaining: 4.38s
974:	learn: 0.4160115	total: 2m 44s	remaining: 4.21s
975:	learn: 0.4159607	total: 2m 44s	remaining: 4.04s
976:	learn: 0.4159529	total: 2m 44s	remaining: 3.87s
977:	learn: 0.4159068	total: 2m 44s	remaining: 3.7s
978:	learn: 0.4158695	total: 2m 44s	remaining: 3.53s
979:	learn: 0.4158340	total: 2m 44s	remaining: 3.36s
980:	learn: 0.4158221	total: 2m 44s	remaining: 3.19s
981:	learn: 0.4158056	total: 2m 44s	remaining: 3.02s
982:	learn: 0.4157843	total: 2m 45s	remaining: 2.85s
983:	learn: 0.4157673	total: 2m 45s	remaining: 2.69s
984:	learn: 0.4157124	total: 2m 45s	remaining: 2.52s
985:	learn: 0.4156901	total: 2m 45s	remaining: 2.35s
986:	learn: 0.4156627	total: 2m 45s	remaining: 2.18s
987:	learn: 0.4156209	total: 2m 45s	remaining: 2.01s
988:	learn: 0.4155616	total: 2m 45s	remaining: 1.84s
989:	learn: 0.4155257	total: 2m 45s	remaining: 1.68s
990:	learn: 0.4155241	total: 2m 46s	remaining: 1.51s
991:	learn: 0.4155016	total: 2m 46s	remaining: 1.34s
992:	learn: 0.4154599	total: 2m 46s	remaining: 1.17s
993:	learn: 0.4154377	total: 2m 46s	remaining: 1s
994:	learn: 0.4154170	total: 2m 46s	remaining: 837ms
995:	learn: 0.4153995	total: 2m 46s	remaining: 670ms
996:	learn: 0.4153784	total: 2m 46s	remaining: 502ms
997:	learn: 0.4153601	total: 2m 46s	remaining: 335ms
998:	learn: 0.4153124	total: 2m 47s	remaining: 167ms
999:	learn: 0.4152704	total: 2m 47s	remaining: 0us

In [42]:
df = pd.read_csv('Data_Test.csv')
df

,ID,Asst_Reg,GGGrade,Experience,Validation,Yearly Income,Home Status,Unpaid 2 years,Already Defaulted,Designation,...,Sub GGGrade,File Status,State,Account Open,Total Unpaid CL,Duration,Unpaid Amount,Reason,Claim Type,Due Fee
0,198980,1773284,II,2yrs,Source Verified,140800.00,OWN,0,0,processor,...,17,fully paid,California,23,33532.0,3 years,15755.94,major purchase,I,0.0
1,167688,5298273,II,>10yrs,Vfied,146080.00,MOR??AGE,0,0,Speech Language Pathologist,...,19,whole,Florida,17,149234.0,5 years,68237.55,debt consolidation,I,0.0
2,198768,189781,VI,>10yrs,Vfied,202222.24,MOR??AGE,0,0,Raytheon,...,37,whole,NM,15,70218.0,5 years,66272.76,debt consolidation,I,0.0
3,192564,1530906,II,>10yrs,Vfied,105600.00,MOR??AGE,1,0,Computer/Network Technician,...,19,fully paid,DE,18,79182.0,3 years,15595.20,credit card,I,0.0
4,151199,4410316,III,4yrs,Not Vfied,151360.00,MOR??AGE,0,0,NDE Tech,...,25,fully paid,Florida,7,13612.0,3 years,8850.96,debt consolidation,I,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37495,191405,5774816,IV,4yrs,Vfied,308000.00,MOR??AGE,1,0,Regional Manager,...,29,fully paid,California,19,132468.0,3 years,57683.43,debt consolidation,I,0.0
37496,164868,1423834,IV,8yrs,Source Verified,158400.00,MOR??AGE,0,0,Clinical Coordinator,...,28,fully paid,PA,14,51958.0,5 years,51395.76,credit card,I,0.0
37497,163156,1895531,V,>10yrs,Not Vfied,52800.00,OWN,0,0,administrative,...,33,fully paid,California,9,8466.0,3 years,2783.88,debt consolidation,I,0.0
37498,169610,2168910,VI,9yrs,Not Vfied,52800.00,OWN,5,0,ParaEducator,...,40,whole,TN,9,17264.0,3 years,NaN,home improvement,I,0.0
37499,175557,4140268,II,>10yrs,Source Verified,121440.00,MOR??AGE,0,0,School Teacher,...,19,fully paid,California,15,47310.0,3 years,29504.34,debt consolidation,I,0.0

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37500 entries, 0 to 37499
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   37500 non-null  int64
 1   Asst_Reg             37500 non-null  int64
 2   GGGrade              37500 non-null  object
 3   Experience           37500 non-null  object
 4   Validation           37500 non-null  object
 5   Yearly Income        35075 non-null  float64
 6   Home Status          37500 non-null  object
 7   Unpaid 2 years       37500 non-null  int64
 8   Already Defaulted    37500 non-null  int64
 9   Designation          36914 non-null  object
 10  Debt to Income       35989 non-null  float64
 11  Postal Code          36889 non-null  float64
 12  Lend Amount          37500 non-null  float64
 13  Deprecatory Records  37500 non-null  int64
 14  Interest Charged     37500 non-null  float64
 15  Usage Rate           37500 non-null  float64
 16  Inquiries            37500 non-null  int64
 17  Present Balance      37500 non-null  float64
 18  Gross Collection     37500 non-null  float64
 19  Sub GGGrade          37500 non-null  int64
 20  File Status          37500 non-null  object
 21  State                37500 non-null  object
 22  Account Open         37500 non-null  int64
 23  Total Unpaid CL      35686 non-null  float64
 24  Duration             37500 non-null  object
 25  Unpaid Amount        35431 non-null  float64
 26  Reason               37500 non-null  object
 27  Claim Type           37500 non-null  object
 28  Due Fee              37500 non-null  float64
dtypes: float64(11), int64(8), object(10)
memory usage: 8.3+ MB

In [44]:
df['GGGrade'].replace('VII','VI',inplace=True)
df['GGGrade'].replace('VI','V',inplace=True)

In [45]:
df['GGGrade'].value_counts(normalize=True)

III    0.284853
II     0.281040
I      0.163440
IV     0.156213
V      0.114453
Name: GGGrade, dtype: float64

In [46]:
df['Experience'].value_counts(normalize=True)

>10yrs    0.350907
2yrs      0.090987
3yrs      0.083413
<1yr      0.082720
1yrs      0.065147
5yrs      0.064320
4yrs      0.059707
8yrs      0.057173
7yrs      0.052507
6yrs      0.049520
9yrs      0.043600
Name: Experience, dtype: float64

In [47]:
df['Experience'].replace('<1yr','1-3',inplace=True)
df['Experience'].replace('1yrs','1-3',inplace=True)
df['Experience'].replace('2yrs','1-3',inplace=True)
df['Experience'].replace('3yrs','1-3',inplace=True)

In [48]:
df['Experience'].replace('4yrs','4-9',inplace=True)
df['Experience'].replace('5yrs','4-9',inplace=True)
df['Experience'].replace('6yrs','4-9',inplace=True)
df['Experience'].replace('7yrs','4-9',inplace=True)
df['Experience'].replace('8yrs','4-9',inplace=True)
df['Experience'].replace('9yrs','4-9',inplace=True)

In [49]:
df['Validation'].value_counts(normalize=True)

Source Verified    0.390560
Not Vfied          0.306347
Vfied              0.303093
Name: Validation, dtype: float64

In [50]:
df['Validation'].replace('Source Verified','Vfied',inplace=True)

In [51]:
df['Home Status'].value_counts(normalize=True)

MOR??AGE    0.504320
REN?        0.399787
OWN         0.095787
NONE        0.000053
OTHER       0.000053
Name: Home Status, dtype: float64

In [52]:
df['Home Status'].replace('NONE','MOR??AGE',inplace=True)
df['Home Status'].replace('OTHER','MOR??AGE',inplace=True)

In [53]:
df['Unpaid 2 years'] = df['Unpaid 2 years'].astype(str)
df

,ID,Asst_Reg,GGGrade,Experience,Validation,Yearly Income,Home Status,Unpaid 2 years,Already Defaulted,Designation,...,Sub GGGrade,File Status,State,Account Open,Total Unpaid CL,Duration,Unpaid Amount,Reason,Claim Type,Due Fee
0,198980,1773284,II,1-3,Vfied,140800.00,OWN,0,0,processor,...,17,fully paid,California,23,33532.0,3 years,15755.94,major purchase,I,0.0
1,167688,5298273,II,>10yrs,Vfied,146080.00,MOR??AGE,0,0,Speech Language Pathologist,...,19,whole,Florida,17,149234.0,5 years,68237.55,debt consolidation,I,0.0
2,198768,189781,V,>10yrs,Vfied,202222.24,MOR??AGE,0,0,Raytheon,...,37,whole,NM,15,70218.0,5 years,66272.76,debt consolidation,I,0.0
3,192564,1530906,II,>10yrs,Vfied,105600.00,MOR??AGE,1,0,Computer/Network Technician,...,19,fully paid,DE,18,79182.0,3 years,15595.20,credit card,I,0.0
4,151199,4410316,III,4-9,Not Vfied,151360.00,MOR??AGE,0,0,NDE Tech,...,25,fully paid,Florida,7,13612.0,3 years,8850.96,debt consolidation,I,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37495,191405,5774816,IV,4-9,Vfied,308000.00,MOR??AGE,1,0,Regional Manager,...,29,fully paid,California,19,132468.0,3 years,57683.43,debt consolidation,I,0.0
37496,164868,1423834,IV,4-9,Vfied,158400.00,MOR??AGE,0,0,Clinical Coordinator,...,28,fully paid,PA,14,51958.0,5 years,51395.76,credit card,I,0.0
37497,163156,1895531,V,>10yrs,Not Vfied,52800.00,OWN,0,0,administrative,...,33,fully paid,California,9,8466.0,3 years,2783.88,debt consolidation,I,0.0
37498,169610,2168910,V,4-9,Not Vfied,52800.00,OWN,5,0,ParaEducator,...,40,whole,TN,9,17264.0,3 years,NaN,home improvement,I,0.0
37499,175557,4140268,II,>10yrs,Vfied,121440.00,MOR??AGE,0,0,School Teacher,...,19,fully paid,California,15,47310.0,3 years,29504.34,debt consolidation,I,0.0

In [54]:
df['Unpaid 2 years'].value_counts(normalize=True)

0     0.797760
1     0.132427
2     0.040027
3     0.014453
4     0.007307
5     0.003307
6     0.002187
7     0.001147
8     0.000613
10    0.000213
9     0.000213
12    0.000107
13    0.000053
17    0.000053
11    0.000053
15    0.000027
14    0.000027
18    0.000027
Name: Unpaid 2 years, dtype: float64

In [55]:
for i in range(df.shape[0]):
    if (df.loc[i,'Unpaid 2 years'] != '0') and (df.loc[i,'Unpaid 2 years'] != '1') and (df.loc[i,'Unpaid 2 years'] != '2'):
        df.loc[i,'Unpaid 2 years'] = 3

In [56]:
df['Already Defaulted'] = df['Already Defaulted'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37500 entries, 0 to 37499
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   37500 non-null  int64
 1   Asst_Reg             37500 non-null  int64
 2   GGGrade              37500 non-null  object
 3   Experience           37500 non-null  object
 4   Validation           37500 non-null  object
 5   Yearly Income        35075 non-null  float64
 6   Home Status          37500 non-null  object
 7   Unpaid 2 years       37500 non-null  object
 8   Already Defaulted    37500 non-null  object
 9   Designation          36914 non-null  object
 10  Debt to Income       35989 non-null  float64
 11  Postal Code          36889 non-null  float64
 12  Lend Amount          37500 non-null  float64
 13  Deprecatory Records  37500 non-null  int64
 14  Interest Charged     37500 non-null  float64
 15  Usage Rate           37500 non-null  float64
 16  Inquiries            37500 non-null  int64
 17  Present Balance      37500 non-null  float64
 18  Gross Collection     37500 non-null  float64
 19  Sub GGGrade          37500 non-null  int64
 20  File Status          37500 non-null  object
 21  State                37500 non-null  object
 22  Account Open         37500 non-null  int64
 23  Total Unpaid CL      35686 non-null  float64
 24  Duration             37500 non-null  object
 25  Unpaid Amount        35431 non-null  float64
 26  Reason               37500 non-null  object
 27  Claim Type           37500 non-null  object
 28  Due Fee              37500 non-null  float64
dtypes: float64(11), int64(6), object(12)
memory usage: 8.3+ MB

In [57]:
df['Already Defaulted'].value_counts(normalize=True)

0    0.995013
1    0.004747
2    0.000160
3    0.000080
Name: Already Defaulted, dtype: float64

In [58]:
for i in range(df.shape[0]):
    if df.loc[i,'Already Defaulted'] != '0':
        df.loc[i,'Already Defaulted'] = '1'

In [59]:
df['Designation'].value_counts(normalize=True)

School Teacher                      0.018042
Super Lead                          0.016119
Nurse                               0.009156
RN                                  0.007585
Owner                               0.007260
                                      ...
License Consultant                  0.000027
Systems Administrator Supervisor    0.000027
At. Acct.                           0.000027
Senior Sales Engineer               0.000027
ParaEducator                        0.000027
Name: Designation, Length: 19510, dtype: float64

In [60]:
df['Postal Code'] = df['Postal Code'].astype(str)
df['Postal Code'].value_counts(normalize=True)

nan        0.016293
75000.0    0.011253
94500.0    0.010480
11200.0    0.009867
60600.0    0.009413
             ...
58400.0    0.000027
9000.0     0.000027
51300.0    0.000027
5200.0     0.000027
20400.0    0.000027
Name: Postal Code, Length: 850, dtype: float64

In [61]:
df['Deprecatory Records'] = df['Deprecatory Records'].astype(str)
df['Deprecatory Records'].value_counts(normalize=True)

0     0.841707
1     0.132853
2     0.016933
3     0.004880
4     0.001840
5     0.000853
6     0.000480
7     0.000187
8     0.000080
9     0.000053
21    0.000027
11    0.000027
12    0.000027
13    0.000027
10    0.000027
Name: Deprecatory Records, dtype: float64

In [62]:
for i in range(df.shape[0]):
    if (df.loc[i,'Deprecatory Records'] != '0') and (df.loc[i,'Deprecatory Records'] != '1'):
        df.loc[i,'Deprecatory Records'] = '2'

In [63]:
df['Inquiries'] = df['Inquiries'].astype(str)
df['Inquiries'].value_counts(normalize=True)

0    0.566640
1    0.271920
2    0.103067
3    0.041040
4    0.012213
5    0.004107
6    0.001013
Name: Inquiries, dtype: float64

In [64]:
for i in range(df.shape[0]):
    if (df.loc[i,'Inquiries'] != '0') and (df.loc[i,'Inquiries'] != '1') and (df.loc[i,'Inquiries'] != '2'):
        df.loc[i,'Inquiries'] = '3'

In [65]:
df['Reason'].value_counts(normalize=True)

debt  consolidation    0.599013
credit  card           0.241440
home  improvement      0.057520
other                  0.045173
major  purchase        0.016187
medical                0.008907
small  business        0.008107
car                    0.008027
moving                 0.005840
vacation               0.004507
house                  0.003627
wedding                0.001120
renewable  energy      0.000533
Name: Reason, dtype: float64

In [66]:
for i in range(df.shape[0]):
    if (df.loc[i,'Inquiries'] != 'debt  consolidation') and (df.loc[i,'Inquiries'] != 'credit  card') and (df.loc[i,'Inquiries'] != 'home  improvement') and (df.loc[i,'Inquiries'] != 'other'):
        df.loc[i,'Inquiries'] = 'other-1'

In [67]:
df.drop(['Designation','Asst_Reg','Postal Code','Claim Type'],axis=1,inplace=True)

In [68]:
df.drop(['Account Open', 'State', 'Sub GGGrade'],axis=1,inplace=True)

In [69]:
df.isnull().sum()

ID                        0
GGGrade                   0
Experience                0
Validation                0
Yearly Income          2425
Home Status               0
Unpaid 2 years            0
Already Defaulted         0
Debt to Income         1511
Lend Amount               0
Deprecatory Records       0
Interest Charged          0
Usage Rate                0
Inquiries                 0
Present Balance           0
Gross Collection          0
File Status               0
Total Unpaid CL        1814
Duration                  0
Unpaid Amount          2069
Reason                    0
Due Fee                   0
dtype: int64

In [71]:
#df['Postal Code'] = df['Postal Code'].astype("object")

In [72]:
df['Yearly Income'].fillna(df['Yearly Income'].mean(),inplace=True)
df['Debt to Income'].fillna(df['Debt to Income'].mean(),inplace=True)
df['Total Unpaid CL'].fillna(df['Total Unpaid CL'].mean(),inplace=True)
df['Unpaid Amount'].fillna(df['Unpaid Amount'].mean(),inplace=True)

#df['Postal Code'].fillna(df['Postal Code'].value_counts().index[0],inplace=True)
#df['Designation'].fillna(df['Designation'].value_counts().index[0],inplace=True)

In [73]:
df.isnull().sum()

ID                     0
GGGrade                0
Experience             0
Validation             0
Yearly Income          0
Home Status            0
Unpaid 2 years         0
Already Defaulted      0
Debt to Income         0
Lend Amount            0
Deprecatory Records    0
Interest Charged       0
Usage Rate             0
Inquiries              0
Present Balance        0
Gross Collection       0
File Status            0
Total Unpaid CL        0
Duration               0
Unpaid Amount          0
Reason                 0
Due Fee                0
dtype: int64

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37500 entries, 0 to 37499
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   37500 non-null  int64
 1   GGGrade              37500 non-null  object
 2   Experience           37500 non-null  object
 3   Validation           37500 non-null  object
 4   Yearly Income        37500 non-null  float64
 5   Home Status          37500 non-null  object
 6   Unpaid 2 years       37500 non-null  object
 7   Already Defaulted    37500 non-null  object
 8   Debt to Income       37500 non-null  float64
 9   Lend Amount          37500 non-null  float64
 10  Deprecatory Records  37500 non-null  object
 11  Interest Charged     37500 non-null  float64
 12  Usage Rate           37500 non-null  float64
 13  Inquiries            37500 non-null  object
 14  Present Balance      37500 non-null  float64
 15  Gross Collection     37500 non-null  float64
 16  File Status          37500 non-null  object
 17  Total Unpaid CL      37500 non-null  float64
 18  Duration             37500 non-null  object
 19  Unpaid Amount        37500 non-null  float64
 20  Reason               37500 non-null  object
 21  Due Fee              37500 non-null  float64
dtypes: float64(10), int64(1), object(11)
memory usage: 6.3+ MB

In [75]:
df

,ID,GGGrade,Experience,Validation,Yearly Income,Home Status,Unpaid 2 years,Already Defaulted,Debt to Income,Lend Amount,...,Usage Rate,Inquiries,Present Balance,Gross Collection,File Status,Total Unpaid CL,Duration,Unpaid Amount,Reason,Due Fee
0,198980,II,1-3,Vfied,140800.00,OWN,0,0,16.9176,17955.00,...,78.432,other-1,59769.30,0.0,fully paid,33532.0,3 years,15755.940000,major purchase,0.0
1,167688,II,>10yrs,Vfied,146080.00,MOR??AGE,0,0,28.6944,59850.00,...,76.368,other-1,532962.13,0.0,whole,149234.0,5 years,68237.550000,debt consolidation,0.0
2,198768,V,>10yrs,Vfied,202222.24,MOR??AGE,0,0,51.1560,59850.00,...,157.552,other-1,288816.48,0.0,whole,70218.0,5 years,66272.760000,debt consolidation,0.0
3,192564,II,>10yrs,Vfied,105600.00,MOR??AGE,1,0,27.0144,19323.00,...,32.852,other-1,424664.30,0.0,fully paid,79182.0,3 years,15595.200000,credit card,0.0
4,151199,III,4-9,Not Vfied,151360.00,MOR??AGE,0,0,10.3824,25350.75,...,108.532,other-1,251704.07,0.0,fully paid,13612.0,3 years,8850.960000,debt consolidation,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37495,191405,IV,4-9,Vfied,308000.00,MOR??AGE,1,0,29.4336,59850.00,...,52.116,other-1,848107.83,0.0,fully paid,132468.0,3 years,57683.430000,debt consolidation,0.0
37496,164868,IV,4-9,Vfied,158400.00,MOR??AGE,0,0,31.6008,28215.00,...,165.120,other-1,614710.30,0.0,fully paid,51958.0,5 years,51395.760000,credit card,0.0
37497,163156,V,>10yrs,Not Vfied,52800.00,OWN,0,0,46.9728,4916.25,...,54.868,other-1,47287.72,0.0,fully paid,8466.0,3 years,2783.880000,debt consolidation,0.0
37498,169610,V,4-9,Not Vfied,52800.00,OWN,3,0,48.0480,15390.00,...,137.772,other-1,107614.80,0.0,whole,17264.0,3 years,29280.658815,home improvement,0.0
37499,175557,II,>10yrs,Vfied,121440.00,MOR??AGE,0,0,27.2664,24624.00,...,104.060,other-1,783477.16,0.0,fully paid,47310.0,3 years,29504.340000,debt consolidation,0.0

In [76]:
df['Loan/No Loan'] = model.predict(df.drop('ID',axis=1))
df

,ID,GGGrade,Experience,Validation,Yearly Income,Home Status,Unpaid 2 years,Already Defaulted,Debt to Income,Lend Amount,...,Inquiries,Present Balance,Gross Collection,File Status,Total Unpaid CL,Duration,Unpaid Amount,Reason,Due Fee,Loan/No Loan
0,198980,II,1-3,Vfied,140800.00,OWN,0,0,16.9176,17955.00,...,other-1,59769.30,0.0,fully paid,33532.0,3 years,15755.940000,major purchase,0.0,0
1,167688,II,>10yrs,Vfied,146080.00,MOR??AGE,0,0,28.6944,59850.00,...,other-1,532962.13,0.0,whole,149234.0,5 years,68237.550000,debt consolidation,0.0,0
2,198768,V,>10yrs,Vfied,202222.24,MOR??AGE,0,0,51.1560,59850.00,...,other-1,288816.48,0.0,whole,70218.0,5 years,66272.760000,debt consolidation,0.0,0
3,192564,II,>10yrs,Vfied,105600.00,MOR??AGE,1,0,27.0144,19323.00,...,other-1,424664.30,0.0,fully paid,79182.0,3 years,15595.200000,credit card,0.0,0
4,151199,III,4-9,Not Vfied,151360.00,MOR??AGE,0,0,10.3824,25350.75,...,other-1,251704.07,0.0,fully paid,13612.0,3 years,8850.960000,debt consolidation,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37495,191405,IV,4-9,Vfied,308000.00,MOR??AGE,1,0,29.4336,59850.00,...,other-1,848107.83,0.0,fully paid,132468.0,3 years,57683.430000,debt consolidation,0.0,0
37496,164868,IV,4-9,Vfied,158400.00,MOR??AGE,0,0,31.6008,28215.00,...,other-1,614710.30,0.0,fully paid,51958.0,5 years,51395.760000,credit card,0.0,0
37497,163156,V,>10yrs,Not Vfied,52800.00,OWN,0,0,46.9728,4916.25,...,other-1,47287.72,0.0,fully paid,8466.0,3 years,2783.880000,debt consolidation,0.0,0
37498,169610,V,4-9,Not Vfied,52800.00,OWN,3,0,48.0480,15390.00,...,other-1,107614.80,0.0,whole,17264.0,3 years,29280.658815,home improvement,0.0,0
37499,175557,II,>10yrs,Vfied,121440.00,MOR??AGE,0,0,27.2664,24624.00,...,other-1,783477.16,0.0,fully paid,47310.0,3 years,29504.340000,debt consolidation,0.0,0

In [77]:
df2=df[['ID','Loan/No Loan']]
df2['ID'] = df2['ID'].astype('int64')
df2['Loan/No Loan'] = df2['Loan/No Loan'].astype('int64')
df2

C:\Users\cools\AppData\Local\Temp/ipykernel_3240/3842719934.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['ID'] = df2['ID'].astype('int64')
C:\Users\cools\AppData\Local\Temp/ipykernel_3240/3842719934.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Loan/No Loan'] = df2['Loan/No Loan'].astype('int64')

           ID  Loan/No Loan
0      198980             0
1      167688             0
2      198768             0
3      192564             0
4      151199             0
...       ...           ...
37495  191405             0
37496  164868             0
37497  163156             0
37498  169610             0
37499  175557             0

[37500 rows x 2 columns]

In [78]:
df = pd.read_csv('Data_Test.csv')
df

,ID,Asst_Reg,GGGrade,Experience,Validation,Yearly Income,Home Status,Unpaid 2 years,Already Defaulted,Designation,...,Sub GGGrade,File Status,State,Account Open,Total Unpaid CL,Duration,Unpaid Amount,Reason,Claim Type,Due Fee
0,198980,1773284,II,2yrs,Source Verified,140800.00,OWN,0,0,processor,...,17,fully paid,California,23,33532.0,3 years,15755.94,major purchase,I,0.0
1,167688,5298273,II,>10yrs,Vfied,146080.00,MOR??AGE,0,0,Speech Language Pathologist,...,19,whole,Florida,17,149234.0,5 years,68237.55,debt consolidation,I,0.0
2,198768,189781,VI,>10yrs,Vfied,202222.24,MOR??AGE,0,0,Raytheon,...,37,whole,NM,15,70218.0,5 years,66272.76,debt consolidation,I,0.0
3,192564,1530906,II,>10yrs,Vfied,105600.00,MOR??AGE,1,0,Computer/Network Technician,...,19,fully paid,DE,18,79182.0,3 years,15595.20,credit card,I,0.0
4,151199,4410316,III,4yrs,Not Vfied,151360.00,MOR??AGE,0,0,NDE Tech,...,25,fully paid,Florida,7,13612.0,3 years,8850.96,debt consolidation,I,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37495,191405,5774816,IV,4yrs,Vfied,308000.00,MOR??AGE,1,0,Regional Manager,...,29,fully paid,California,19,132468.0,3 years,57683.43,debt consolidation,I,0.0
37496,164868,1423834,IV,8yrs,Source Verified,158400.00,MOR??AGE,0,0,Clinical Coordinator,...,28,fully paid,PA,14,51958.0,5 years,51395.76,credit card,I,0.0
37497,163156,1895531,V,>10yrs,Not Vfied,52800.00,OWN,0,0,administrative,...,33,fully paid,California,9,8466.0,3 years,2783.88,debt consolidation,I,0.0
37498,169610,2168910,VI,9yrs,Not Vfied,52800.00,OWN,5,0,ParaEducator,...,40,whole,TN,9,17264.0,3 years,NaN,home improvement,I,0.0
37499,175557,4140268,II,>10yrs,Source Verified,121440.00,MOR??AGE,0,0,School Teacher,...,19,fully paid,California,15,47310.0,3 years,29504.34,debt consolidation,I,0.0

In [79]:
df2['ID'] = df['ID']
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37500 entries, 0 to 37499
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            37500 non-null  int64
 1   Loan/No Loan  37500 non-null  int64
dtypes: int64(2)
memory usage: 586.1 KB

C:\Users\cools\AppData\Local\Temp/ipykernel_3240/2065228058.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['ID'] = df['ID']

In [80]:
df2.to_csv('file9.csv',index=0)