In [23]:
import pandas as pd
import numpy as np

In [24]:
df = pd.read_csv('Train_Dataset.csv')
df

,EmployeeID,Attrition,Age,TravelProfile,Department,HomeToWork,EducationField,Gender,HourlnWeek,Involvement,...,JobSatisfaction,ESOPs,NumCompaniesWorked,OverTime,SalaryHikelastYear,WorkExperience,LastPromotion,CurrentProfile,MaritalStatus,MonthlyIncome
0,5110001.0,0.0,35.0,Rarely,Analytics,5.0,CA,Male,69.0,1.0,...,1.0,1.0,1.0,1.0,20.0,7.0,2.0,NaN,M,18932.0
1,5110002.0,1.0,32.0,Yes,Sales,5.0,Statistics,Female,62.0,4.0,...,2.0,0.0,8.0,0.0,20.0,4.0,1.0,NaN,Single,18785.0
2,5110003.0,0.0,31.0,Rarely,Analytics,5.0,Statistics,F,45.0,5.0,...,2.0,1.0,3.0,0.0,26.0,12.0,1.0,3.0,Single,22091.0
3,5110004.0,0.0,34.0,Yes,Sales,10.0,Statistics,Female,32.0,3.0,...,4.0,1.0,1.0,0.0,23.0,5.0,1.0,3.0,Divorsed,20302.0
4,5110005.0,0.0,37.0,No,Analytics,27.0,Statistics,Female,49.0,3.0,...,4.0,1.0,8.0,0.0,21.0,12.0,1.0,9.0,Divorsed,21674.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7807,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7809,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df.drop('EmployeeID',axis=1,inplace=True)

In [26]:
df.isnull().sum()

Attrition             2630
Age                   2946
TravelProfile         2630
Department            2754
HomeToWork            2885
EducationField        2630
Gender                2676
HourlnWeek            2917
Involvement           2630
WorkLifeBalance       2630
Designation           2668
JobSatisfaction       2630
ESOPs                 2630
NumCompaniesWorked    2630
OverTime              2630
SalaryHikelastYear    2799
WorkExperience        2817
LastPromotion         2700
CurrentProfile        2941
MaritalStatus         2630
MonthlyIncome         2723
dtype: int64

In [27]:
df['HourlnWeek'].fillna(df['HourlnWeek'].mean(),inplace=True)
df['HomeToWork'].fillna(df['HomeToWork'].mean(),inplace=True)
df['Involvement'].fillna(df['Involvement'].mean(),inplace=True)
df['WorkLifeBalance'].fillna(df['WorkLifeBalance'].mean(),inplace=True)
df['JobSatisfaction'].fillna(df['JobSatisfaction'].mean(),inplace=True)
df['ESOPs'].fillna(df['ESOPs'].mean(),inplace=True)
df['NumCompaniesWorked'].fillna(df['NumCompaniesWorked'].mean(),inplace=True)
df['OverTime'].fillna(df['OverTime'].mean(),inplace=True)

df['Age'].fillna(df['Age'].mean(),inplace=True)
df['HomeToWork'].fillna(df['HomeToWork'].mean(),inplace=True)
df['HourlnWeek'].fillna(df['HourlnWeek'].mean(),inplace=True)
df['SalaryHikelastYear'].fillna(df['SalaryHikelastYear'].mean(),inplace=True)
df['WorkExperience'].fillna(df['WorkExperience'].mean(),inplace=True)
df['LastPromotion'].fillna(df['LastPromotion'].mean(),inplace=True)
df['CurrentProfile'].fillna(df['CurrentProfile'].mean(),inplace=True)
df['MonthlyIncome'].fillna(df['MonthlyIncome'].mean(),inplace=True)

df['Department'].fillna(df['Department'].value_counts().index[0],inplace=True)
df['Gender'].fillna(df['Gender'].value_counts().index[0],inplace=True)
df['Designation'].fillna(df['Designation'].value_counts().index[0],inplace=True)
df['TravelProfile'].fillna(df['TravelProfile'].value_counts().index[0],inplace=True)
df['EducationField'].fillna(df['EducationField'].value_counts().index[0],inplace=True)
df['MaritalStatus'].fillna(df['MaritalStatus'].value_counts().index[0],inplace=True)

In [28]:
df.isnull().sum()

Attrition             2630
Age                      0
TravelProfile            0
Department               0
HomeToWork               0
EducationField           0
Gender                   0
HourlnWeek               0
Involvement              0
WorkLifeBalance          0
Designation              0
JobSatisfaction          0
ESOPs                    0
NumCompaniesWorked       0
OverTime                 0
SalaryHikelastYear       0
WorkExperience           0
LastPromotion            0
CurrentProfile           0
MaritalStatus            0
MonthlyIncome            0
dtype: int64

In [29]:
df.dropna(inplace=True)
df

,Attrition,Age,TravelProfile,Department,HomeToWork,EducationField,Gender,HourlnWeek,Involvement,WorkLifeBalance,...,JobSatisfaction,ESOPs,NumCompaniesWorked,OverTime,SalaryHikelastYear,WorkExperience,LastPromotion,CurrentProfile,MaritalStatus,MonthlyIncome
0,0.0,35.000000,Rarely,Analytics,5.000000,CA,Male,69.0,1.0,1.0,...,1.0,1.0,1.0,1.0,20.0,7.0,2.0,4.385295,M,18932.0
1,1.0,32.000000,Yes,Sales,5.000000,Statistics,Female,62.0,4.0,3.0,...,2.0,0.0,8.0,0.0,20.0,4.0,1.0,4.385295,Single,18785.0
2,0.0,31.000000,Rarely,Analytics,5.000000,Statistics,F,45.0,5.0,3.0,...,2.0,1.0,3.0,0.0,26.0,12.0,1.0,3.000000,Single,22091.0
3,0.0,34.000000,Yes,Sales,10.000000,Statistics,Female,32.0,3.0,2.0,...,4.0,1.0,1.0,0.0,23.0,5.0,1.0,3.000000,Divorsed,20302.0
4,0.0,37.000000,No,Analytics,27.000000,Statistics,Female,49.0,3.0,4.0,...,4.0,1.0,8.0,0.0,21.0,12.0,1.0,9.000000,Divorsed,21674.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5175,0.0,36.000000,Rarely,Analytics,13.000000,CA,F,53.0,3.0,3.0,...,3.0,0.0,4.0,1.0,22.0,11.0,1.0,5.000000,Single,22142.0
5176,0.0,37.108553,Rarely,Marketing,9.000000,CA,Female,66.0,1.0,4.0,...,4.0,1.0,9.0,0.0,23.0,8.0,0.0,2.000000,Single,17109.0
5177,0.0,29.000000,Rarely,Analytics,11.107411,CA,Female,62.0,4.0,2.0,...,1.0,1.0,6.0,0.0,19.0,8.0,0.0,3.000000,M,17532.0
5178,0.0,26.000000,Rarely,Marketing,26.000000,Statistics,Female,61.0,3.0,4.0,...,3.0,0.0,1.0,0.0,28.0,8.0,5.0,7.000000,Divorsed,17942.0
5179,1.0,37.108553,Yes,Sales,13.000000,Statistics,Male,74.0,4.0,3.0,...,5.0,1.0,1.0,0.0,23.0,1.0,0.0,0.000000,Divorsed,17033.0

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5180 entries, 0 to 5179
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Attrition           5180 non-null   float64
 1   Age                 5180 non-null   float64
 2   TravelProfile       5180 non-null   object
 3   Department          5180 non-null   object
 4   HomeToWork          5180 non-null   float64
 5   EducationField      5180 non-null   object
 6   Gender              5180 non-null   object
 7   HourlnWeek          5180 non-null   float64
 8   Involvement         5180 non-null   float64
 9   WorkLifeBalance     5180 non-null   float64
 10  Designation         5180 non-null   object
 11  JobSatisfaction     5180 non-null   float64
 12  ESOPs               5180 non-null   float64
 13  NumCompaniesWorked  5180 non-null   float64
 14  OverTime            5180 non-null   float64
 15  SalaryHikelastYear  5180 non-null   float64
 16  WorkExperience      5180 non-null   float64
 17  LastPromotion       5180 non-null   float64
 18  CurrentProfile      5180 non-null   float64
 19  MaritalStatus       5180 non-null   object
 20  MonthlyIncome       5180 non-null   float64
dtypes: float64(15), object(6)
memory usage: 890.3+ KB

In [31]:
df = pd.get_dummies(df,drop_first=True)
X = df.drop('Attrition', axis=1)

y = df['Attrition']

In [32]:
from catboost import CatBoostClassifier
clf = CatBoostClassifier(random_state=1,learning_rate=0.38,max_depth=10)   # learning_rate= 0.36, 0.37 give same result
model=clf.fit(X,y)

0:	learn: 0.4813157	total: 166ms	remaining: 2m 45s
1:	learn: 0.3202351	total: 189ms	remaining: 1m 34s
2:	learn: 0.2433489	total: 211ms	remaining: 1m 10s
3:	learn: 0.1922268	total: 235ms	remaining: 58.5s
4:	learn: 0.1663976	total: 260ms	remaining: 51.7s
5:	learn: 0.1477739	total: 282ms	remaining: 46.7s
6:	learn: 0.1169411	total: 307ms	remaining: 43.5s
7:	learn: 0.1029498	total: 330ms	remaining: 40.9s
8:	learn: 0.0937267	total: 353ms	remaining: 38.8s
9:	learn: 0.0828730	total: 380ms	remaining: 37.6s
10:	learn: 0.0751766	total: 405ms	remaining: 36.4s
11:	learn: 0.0677601	total: 427ms	remaining: 35.2s
12:	learn: 0.0615638	total: 451ms	remaining: 34.2s
13:	learn: 0.0557820	total: 473ms	remaining: 33.3s
14:	learn: 0.0508344	total: 495ms	remaining: 32.5s
15:	learn: 0.0479229	total: 518ms	remaining: 31.8s
16:	learn: 0.0421956	total: 541ms	remaining: 31.3s
17:	learn: 0.0387488	total: 563ms	remaining: 30.7s
18:	learn: 0.0371099	total: 587ms	remaining: 30.3s
19:	learn: 0.0344476	total: 612ms	remaining: 30s
20:	learn: 0.0317528	total: 636ms	remaining: 29.7s
21:	learn: 0.0298349	total: 660ms	remaining: 29.3s
22:	learn: 0.0275566	total: 682ms	remaining: 29s
23:	learn: 0.0254337	total: 705ms	remaining: 28.7s
24:	learn: 0.0239990	total: 728ms	remaining: 28.4s
25:	learn: 0.0232293	total: 750ms	remaining: 28.1s
26:	learn: 0.0219285	total: 774ms	remaining: 27.9s
27:	learn: 0.0205556	total: 799ms	remaining: 27.7s
28:	learn: 0.0188123	total: 826ms	remaining: 27.7s
29:	learn: 0.0175308	total: 851ms	remaining: 27.5s
30:	learn: 0.0163888	total: 875ms	remaining: 27.3s
31:	learn: 0.0152605	total: 899ms	remaining: 27.2s
32:	learn: 0.0143685	total: 921ms	remaining: 27s
33:	learn: 0.0134306	total: 945ms	remaining: 26.8s
34:	learn: 0.0127290	total: 968ms	remaining: 26.7s
35:	learn: 0.0121524	total: 990ms	remaining: 26.5s
36:	learn: 0.0117038	total: 1.01s	remaining: 26.3s
37:	learn: 0.0110504	total: 1.04s	remaining: 26.3s
38:	learn: 0.0105284	total: 1.06s	remaining: 26.1s
39:	learn: 0.0101490	total: 1.08s	remaining: 26s
40:	learn: 0.0097490	total: 1.1s	remaining: 25.8s
41:	learn: 0.0093197	total: 1.13s	remaining: 25.7s
42:	learn: 0.0090200	total: 1.15s	remaining: 25.6s
43:	learn: 0.0086896	total: 1.17s	remaining: 25.5s
44:	learn: 0.0082221	total: 1.2s	remaining: 25.4s
45:	learn: 0.0079442	total: 1.22s	remaining: 25.3s
46:	learn: 0.0075439	total: 1.25s	remaining: 25.3s
47:	learn: 0.0073195	total: 1.27s	remaining: 25.2s
48:	learn: 0.0070986	total: 1.29s	remaining: 25.1s
49:	learn: 0.0068365	total: 1.32s	remaining: 25s
50:	learn: 0.0066240	total: 1.34s	remaining: 24.9s
51:	learn: 0.0063822	total: 1.36s	remaining: 24.8s
52:	learn: 0.0062048	total: 1.39s	remaining: 24.8s
53:	learn: 0.0060342	total: 1.41s	remaining: 24.7s
54:	learn: 0.0058903	total: 1.43s	remaining: 24.6s
55:	learn: 0.0056992	total: 1.46s	remaining: 24.6s
56:	learn: 0.0055820	total: 1.48s	remaining: 24.6s
57:	learn: 0.0054160	total: 1.51s	remaining: 24.5s
58:	learn: 0.0052248	total: 1.53s	remaining: 24.4s
59:	learn: 0.0050802	total: 1.55s	remaining: 24.3s
60:	learn: 0.0049425	total: 1.58s	remaining: 24.3s
61:	learn: 0.0048088	total: 1.6s	remaining: 24.2s
62:	learn: 0.0047150	total: 1.62s	remaining: 24.1s
63:	learn: 0.0046051	total: 1.64s	remaining: 24.1s
64:	learn: 0.0044864	total: 1.67s	remaining: 24s
65:	learn: 0.0043818	total: 1.69s	remaining: 24s
66:	learn: 0.0043137	total: 1.72s	remaining: 23.9s
67:	learn: 0.0042286	total: 1.74s	remaining: 23.8s
68:	learn: 0.0041304	total: 1.76s	remaining: 23.7s
69:	learn: 0.0040333	total: 1.78s	remaining: 23.7s
70:	learn: 0.0039865	total: 1.8s	remaining: 23.6s
71:	learn: 0.0039027	total: 1.83s	remaining: 23.5s
72:	learn: 0.0038408	total: 1.85s	remaining: 23.5s
73:	learn: 0.0037504	total: 1.88s	remaining: 23.5s
74:	learn: 0.0036885	total: 1.9s	remaining: 23.4s
75:	learn: 0.0036207	total: 1.92s	remaining: 23.4s
76:	learn: 0.0035366	total: 1.94s	remaining: 23.3s
77:	learn: 0.0034742	total: 1.97s	remaining: 23.2s
78:	learn: 0.0034056	total: 1.99s	remaining: 23.2s
79:	learn: 0.0033382	total: 2.01s	remaining: 23.1s
80:	learn: 0.0032673	total: 2.03s	remaining: 23s
81:	learn: 0.0032238	total: 2.05s	remaining: 23s
82:	learn: 0.0031683	total: 2.08s	remaining: 22.9s
83:	learn: 0.0031312	total: 2.1s	remaining: 22.9s
84:	learn: 0.0030654	total: 2.12s	remaining: 22.8s
85:	learn: 0.0030102	total: 2.14s	remaining: 22.8s
86:	learn: 0.0029575	total: 2.17s	remaining: 22.7s
87:	learn: 0.0028989	total: 2.19s	remaining: 22.7s
88:	learn: 0.0028425	total: 2.21s	remaining: 22.6s
89:	learn: 0.0027893	total: 2.23s	remaining: 22.6s
90:	learn: 0.0027385	total: 2.26s	remaining: 22.5s
91:	learn: 0.0027077	total: 2.28s	remaining: 22.5s
92:	learn: 0.0026506	total: 2.3s	remaining: 22.5s
93:	learn: 0.0026047	total: 2.33s	remaining: 22.4s
94:	learn: 0.0025719	total: 2.35s	remaining: 22.4s
95:	learn: 0.0025282	total: 2.38s	remaining: 22.4s
96:	learn: 0.0024944	total: 2.4s	remaining: 22.4s
97:	learn: 0.0024579	total: 2.42s	remaining: 22.3s
98:	learn: 0.0024259	total: 2.45s	remaining: 22.3s
99:	learn: 0.0023882	total: 2.47s	remaining: 22.2s
100:	learn: 0.0023628	total: 2.49s	remaining: 22.2s
101:	learn: 0.0023284	total: 2.51s	remaining: 22.1s
102:	learn: 0.0022991	total: 2.54s	remaining: 22.1s
103:	learn: 0.0022667	total: 2.56s	remaining: 22s
104:	learn: 0.0022353	total: 2.58s	remaining: 22s
105:	learn: 0.0021974	total: 2.61s	remaining: 22s
106:	learn: 0.0021638	total: 2.63s	remaining: 22s
107:	learn: 0.0021339	total: 2.65s	remaining: 21.9s
108:	learn: 0.0021110	total: 2.68s	remaining: 21.9s
109:	learn: 0.0020824	total: 2.7s	remaining: 21.8s
110:	learn: 0.0020636	total: 2.72s	remaining: 21.8s
111:	learn: 0.0020427	total: 2.74s	remaining: 21.8s
112:	learn: 0.0020199	total: 2.77s	remaining: 21.7s
113:	learn: 0.0019914	total: 2.79s	remaining: 21.7s
114:	learn: 0.0019685	total: 2.82s	remaining: 21.7s
115:	learn: 0.0019624	total: 2.84s	remaining: 21.7s
116:	learn: 0.0019373	total: 2.87s	remaining: 21.6s
117:	learn: 0.0019174	total: 2.89s	remaining: 21.6s
118:	learn: 0.0018943	total: 2.91s	remaining: 21.6s
119:	learn: 0.0018690	total: 2.94s	remaining: 21.5s
120:	learn: 0.0018461	total: 2.96s	remaining: 21.5s
121:	learn: 0.0018244	total: 2.98s	remaining: 21.4s
122:	learn: 0.0018098	total: 3s	remaining: 21.4s
123:	learn: 0.0017882	total: 3.02s	remaining: 21.3s
124:	learn: 0.0017676	total: 3.05s	remaining: 21.3s
125:	learn: 0.0017489	total: 3.07s	remaining: 21.3s
126:	learn: 0.0017283	total: 3.09s	remaining: 21.3s
127:	learn: 0.0017068	total: 3.12s	remaining: 21.2s
128:	learn: 0.0016848	total: 3.14s	remaining: 21.2s
129:	learn: 0.0016807	total: 3.16s	remaining: 21.1s
130:	learn: 0.0016807	total: 3.18s	remaining: 21.1s
131:	learn: 0.0016644	total: 3.2s	remaining: 21.1s
132:	learn: 0.0016471	total: 3.22s	remaining: 21s
133:	learn: 0.0016268	total: 3.25s	remaining: 21s
134:	learn: 0.0016138	total: 3.27s	remaining: 21s
135:	learn: 0.0015969	total: 3.29s	remaining: 20.9s
136:	learn: 0.0015785	total: 3.32s	remaining: 20.9s
137:	learn: 0.0015649	total: 3.34s	remaining: 20.9s
138:	learn: 0.0015610	total: 3.36s	remaining: 20.8s
139:	learn: 0.0015463	total: 3.38s	remaining: 20.8s
140:	learn: 0.0015463	total: 3.41s	remaining: 20.8s
141:	learn: 0.0015463	total: 3.43s	remaining: 20.7s
142:	learn: 0.0015324	total: 3.45s	remaining: 20.7s
143:	learn: 0.0015142	total: 3.48s	remaining: 20.7s
144:	learn: 0.0014974	total: 3.5s	remaining: 20.7s
145:	learn: 0.0014974	total: 3.53s	remaining: 20.6s
146:	learn: 0.0014820	total: 3.55s	remaining: 20.6s
147:	learn: 0.0014695	total: 3.58s	remaining: 20.6s
148:	learn: 0.0014630	total: 3.6s	remaining: 20.5s
149:	learn: 0.0014630	total: 3.62s	remaining: 20.5s
150:	learn: 0.0014630	total: 3.64s	remaining: 20.5s
151:	learn: 0.0014468	total: 3.67s	remaining: 20.5s
152:	learn: 0.0014325	total: 3.69s	remaining: 20.4s
153:	learn: 0.0014325	total: 3.71s	remaining: 20.4s
154:	learn: 0.0014181	total: 3.74s	remaining: 20.4s
155:	learn: 0.0014181	total: 3.76s	remaining: 20.3s
156:	learn: 0.0014180	total: 3.78s	remaining: 20.3s
157:	learn: 0.0014180	total: 3.8s	remaining: 20.2s
158:	learn: 0.0014180	total: 3.82s	remaining: 20.2s
159:	learn: 0.0014180	total: 3.84s	remaining: 20.2s
160:	learn: 0.0014180	total: 3.87s	remaining: 20.1s
161:	learn: 0.0014046	total: 3.89s	remaining: 20.1s

162:	learn: 0.0014046	total: 3.91s	remaining: 20.1s
163:	learn: 0.0013880	total: 3.94s	remaining: 20.1s
164:	learn: 0.0013730	total: 3.96s	remaining: 20s
165:	learn: 0.0013602	total: 3.98s	remaining: 20s
166:	learn: 0.0013486	total: 4s	remaining: 20s
167:	learn: 0.0013486	total: 4.02s	remaining: 19.9s
168:	learn: 0.0013485	total: 4.04s	remaining: 19.9s
169:	learn: 0.0013485	total: 4.06s	remaining: 19.8s
170:	learn: 0.0013485	total: 4.08s	remaining: 19.8s
171:	learn: 0.0013485	total: 4.11s	remaining: 19.8s
172:	learn: 0.0013485	total: 4.13s	remaining: 19.7s
173:	learn: 0.0013485	total: 4.15s	remaining: 19.7s
174:	learn: 0.0013485	total: 4.17s	remaining: 19.7s
175:	learn: 0.0013485	total: 4.19s	remaining: 19.6s
176:	learn: 0.0013485	total: 4.21s	remaining: 19.6s
177:	learn: 0.0013485	total: 4.24s	remaining: 19.6s
178:	learn: 0.0013485	total: 4.26s	remaining: 19.5s
179:	learn: 0.0013484	total: 4.28s	remaining: 19.5s
180:	learn: 0.0013484	total: 4.3s	remaining: 19.5s
181:	learn: 0.0013484	total: 4.32s	remaining: 19.4s
182:	learn: 0.0013484	total: 4.34s	remaining: 19.4s
183:	learn: 0.0013484	total: 4.37s	remaining: 19.4s
184:	learn: 0.0013484	total: 4.39s	remaining: 19.3s
185:	learn: 0.0013484	total: 4.41s	remaining: 19.3s
186:	learn: 0.0013484	total: 4.43s	remaining: 19.3s
187:	learn: 0.0013484	total: 4.45s	remaining: 19.2s
188:	learn: 0.0013484	total: 4.48s	remaining: 19.2s
189:	learn: 0.0013484	total: 4.5s	remaining: 19.2s
190:	learn: 0.0013484	total: 4.52s	remaining: 19.1s
191:	learn: 0.0013483	total: 4.54s	remaining: 19.1s
192:	learn: 0.0013483	total: 4.57s	remaining: 19.1s
193:	learn: 0.0013483	total: 4.59s	remaining: 19.1s
194:	learn: 0.0013482	total: 4.61s	remaining: 19s
195:	learn: 0.0013482	total: 4.63s	remaining: 19s
196:	learn: 0.0013449	total: 4.65s	remaining: 19s
197:	learn: 0.0013449	total: 4.67s	remaining: 18.9s
198:	learn: 0.0013449	total: 4.69s	remaining: 18.9s
199:	learn: 0.0013449	total: 4.71s	remaining: 18.9s
200:	learn: 0.0013449	total: 4.74s	remaining: 18.8s
201:	learn: 0.0013340	total: 4.76s	remaining: 18.8s
202:	learn: 0.0013340	total: 4.78s	remaining: 18.8s
203:	learn: 0.0013340	total: 4.8s	remaining: 18.8s
204:	learn: 0.0013217	total: 4.83s	remaining: 18.7s
205:	learn: 0.0013217	total: 4.85s	remaining: 18.7s
206:	learn: 0.0013106	total: 4.87s	remaining: 18.7s
207:	learn: 0.0012995	total: 4.89s	remaining: 18.6s
208:	learn: 0.0012860	total: 4.92s	remaining: 18.6s
209:	learn: 0.0012860	total: 4.94s	remaining: 18.6s
210:	learn: 0.0012860	total: 4.96s	remaining: 18.5s
211:	learn: 0.0012860	total: 4.98s	remaining: 18.5s
212:	learn: 0.0012860	total: 5s	remaining: 18.5s
213:	learn: 0.0012859	total: 5.02s	remaining: 18.4s
214:	learn: 0.0012859	total: 5.04s	remaining: 18.4s
215:	learn: 0.0012859	total: 5.06s	remaining: 18.4s
216:	learn: 0.0012859	total: 5.08s	remaining: 18.3s
217:	learn: 0.0012859	total: 5.1s	remaining: 18.3s
218:	learn: 0.0012859	total: 5.12s	remaining: 18.3s
219:	learn: 0.0012859	total: 5.14s	remaining: 18.2s
220:	learn: 0.0012859	total: 5.17s	remaining: 18.2s
221:	learn: 0.0012859	total: 5.19s	remaining: 18.2s
222:	learn: 0.0012859	total: 5.21s	remaining: 18.2s
223:	learn: 0.0012859	total: 5.24s	remaining: 18.1s
224:	learn: 0.0012859	total: 5.26s	remaining: 18.1s
225:	learn: 0.0012859	total: 5.28s	remaining: 18.1s
226:	learn: 0.0012859	total: 5.3s	remaining: 18s
227:	learn: 0.0012859	total: 5.32s	remaining: 18s
228:	learn: 0.0012859	total: 5.34s	remaining: 18s
229:	learn: 0.0012858	total: 5.36s	remaining: 18s
230:	learn: 0.0012858	total: 5.38s	remaining: 17.9s
231:	learn: 0.0012858	total: 5.41s	remaining: 17.9s
232:	learn: 0.0012858	total: 5.43s	remaining: 17.9s
233:	learn: 0.0012858	total: 5.45s	remaining: 17.8s
234:	learn: 0.0012858	total: 5.47s	remaining: 17.8s
235:	learn: 0.0012858	total: 5.5s	remaining: 17.8s
236:	learn: 0.0012857	total: 5.52s	remaining: 17.8s
237:	learn: 0.0012857	total: 5.54s	remaining: 17.7s
238:	learn: 0.0012857	total: 5.56s	remaining: 17.7s
239:	learn: 0.0012857	total: 5.58s	remaining: 17.7s
240:	learn: 0.0012857	total: 5.6s	remaining: 17.6s
241:	learn: 0.0012857	total: 5.62s	remaining: 17.6s
242:	learn: 0.0012857	total: 5.64s	remaining: 17.6s
243:	learn: 0.0012857	total: 5.66s	remaining: 17.5s
244:	learn: 0.0012857	total: 5.68s	remaining: 17.5s
245:	learn: 0.0012814	total: 5.71s	remaining: 17.5s
246:	learn: 0.0012814	total: 5.73s	remaining: 17.5s
247:	learn: 0.0012813	total: 5.75s	remaining: 17.4s
248:	learn: 0.0012813	total: 5.77s	remaining: 17.4s
249:	learn: 0.0012812	total: 5.79s	remaining: 17.4s
250:	learn: 0.0012812	total: 5.82s	remaining: 17.4s
251:	learn: 0.0012812	total: 5.84s	remaining: 17.3s
252:	learn: 0.0012812	total: 5.86s	remaining: 17.3s
253:	learn: 0.0012811	total: 5.88s	remaining: 17.3s
254:	learn: 0.0012811	total: 5.9s	remaining: 17.2s
255:	learn: 0.0012811	total: 5.92s	remaining: 17.2s
256:	learn: 0.0012811	total: 5.94s	remaining: 17.2s
257:	learn: 0.0012699	total: 5.97s	remaining: 17.2s
258:	learn: 0.0012646	total: 5.99s	remaining: 17.1s
259:	learn: 0.0012569	total: 6.01s	remaining: 17.1s
260:	learn: 0.0012446	total: 6.03s	remaining: 17.1s
261:	learn: 0.0012335	total: 6.06s	remaining: 17.1s
262:	learn: 0.0012335	total: 6.08s	remaining: 17s
263:	learn: 0.0012335	total: 6.1s	remaining: 17s
264:	learn: 0.0012335	total: 6.12s	remaining: 17s
265:	learn: 0.0012334	total: 6.14s	remaining: 17s
266:	learn: 0.0012334	total: 6.17s	remaining: 16.9s
267:	learn: 0.0012333	total: 6.19s	remaining: 16.9s
268:	learn: 0.0012332	total: 6.21s	remaining: 16.9s
269:	learn: 0.0012332	total: 6.23s	remaining: 16.8s
270:	learn: 0.0012220	total: 6.25s	remaining: 16.8s
271:	learn: 0.0012133	total: 6.28s	remaining: 16.8s
272:	learn: 0.0012132	total: 6.3s	remaining: 16.8s
273:	learn: 0.0012132	total: 6.32s	remaining: 16.7s
274:	learn: 0.0012131	total: 6.34s	remaining: 16.7s
275:	learn: 0.0012131	total: 6.36s	remaining: 16.7s
276:	learn: 0.0012130	total: 6.39s	remaining: 16.7s
277:	learn: 0.0012130	total: 6.41s	remaining: 16.6s
278:	learn: 0.0012130	total: 6.43s	remaining: 16.6s
279:	learn: 0.0012130	total: 6.45s	remaining: 16.6s
280:	learn: 0.0012130	total: 6.47s	remaining: 16.6s
281:	learn: 0.0012130	total: 6.49s	remaining: 16.5s
282:	learn: 0.0012130	total: 6.51s	remaining: 16.5s
283:	learn: 0.0012130	total: 6.54s	remaining: 16.5s
284:	learn: 0.0012130	total: 6.56s	remaining: 16.4s
285:	learn: 0.0012130	total: 6.58s	remaining: 16.4s
286:	learn: 0.0012130	total: 6.6s	remaining: 16.4s
287:	learn: 0.0012130	total: 6.62s	remaining: 16.4s
288:	learn: 0.0012130	total: 6.64s	remaining: 16.3s
289:	learn: 0.0012130	total: 6.66s	remaining: 16.3s
290:	learn: 0.0012130	total: 6.68s	remaining: 16.3s
291:	learn: 0.0012129	total: 6.71s	remaining: 16.3s
292:	learn: 0.0012129	total: 6.73s	remaining: 16.2s
293:	learn: 0.0012129	total: 6.75s	remaining: 16.2s
294:	learn: 0.0012129	total: 6.77s	remaining: 16.2s
295:	learn: 0.0012128	total: 6.79s	remaining: 16.2s
296:	learn: 0.0012128	total: 6.81s	remaining: 16.1s
297:	learn: 0.0012128	total: 6.84s	remaining: 16.1s
298:	learn: 0.0012128	total: 6.86s	remaining: 16.1s
299:	learn: 0.0012128	total: 6.89s	remaining: 16.1s
300:	learn: 0.0012128	total: 6.91s	remaining: 16s
301:	learn: 0.0012128	total: 6.93s	remaining: 16s
302:	learn: 0.0012128	total: 6.95s	remaining: 16s
303:	learn: 0.0012127	total: 6.97s	remaining: 16s
304:	learn: 0.0012127	total: 6.99s	remaining: 15.9s
305:	learn: 0.0012127	total: 7.01s	remaining: 15.9s
306:	learn: 0.0012127	total: 7.04s	remaining: 15.9s
307:	learn: 0.0012127	total: 7.05s	remaining: 15.9s
308:	learn: 0.0012127	total: 7.08s	remaining: 15.8s
309:	learn: 0.0012127	total: 7.1s	remaining: 15.8s
310:	learn: 0.0012127	total: 7.12s	remaining: 15.8s
311:	learn: 0.0012125	total: 7.14s	remaining: 15.7s
312:	learn: 0.0012125	total: 7.16s	remaining: 15.7s
313:	learn: 0.0012124	total: 7.18s	remaining: 15.7s
314:	learn: 0.0012124	total: 7.2s	remaining: 15.7s
315:	learn: 0.0012124	total: 7.22s	remaining: 15.6s
316:	learn: 0.0012124	total: 7.25s	remaining: 15.6s
317:	learn: 0.0012124	total: 7.27s	remaining: 15.6s
318:	learn: 0.0012124	total: 7.29s	remaining: 15.6s
319:	learn: 0.0012124	total: 7.31s	remaining: 15.5s
320:	learn: 0.0012123	total: 7.33s	remaining: 15.5s
321:	learn: 0.0012123	total: 7.36s	remaining: 15.5s
322:	learn: 0.0012123	total: 7.38s	remaining: 15.5s
323:	learn: 0.0012123	total: 7.4s	remaining: 15.4s
324:	learn: 0.0012123	total: 7.42s	remaining: 15.4s
325:	learn: 0.0012123	total: 7.45s	remaining: 15.4s
326:	learn: 0.0012123	total: 7.47s	remaining: 15.4s
327:	learn: 0.0012123	total: 7.49s	remaining: 15.3s
328:	learn: 0.0012123	total: 7.51s	remaining: 15.3s

329:	learn: 0.0012122	total: 7.53s	remaining: 15.3s
330:	learn: 0.0012122	total: 7.55s	remaining: 15.3s
331:	learn: 0.0012122	total: 7.57s	remaining: 15.2s
332:	learn: 0.0012122	total: 7.59s	remaining: 15.2s
333:	learn: 0.0012122	total: 7.62s	remaining: 15.2s
334:	learn: 0.0012121	total: 7.64s	remaining: 15.2s
335:	learn: 0.0012121	total: 7.66s	remaining: 15.1s
336:	learn: 0.0012121	total: 7.68s	remaining: 15.1s
337:	learn: 0.0012121	total: 7.7s	remaining: 15.1s
338:	learn: 0.0012121	total: 7.72s	remaining: 15.1s
339:	learn: 0.0012121	total: 7.74s	remaining: 15s
340:	learn: 0.0012121	total: 7.76s	remaining: 15s
341:	learn: 0.0012121	total: 7.78s	remaining: 15s
342:	learn: 0.0012121	total: 7.8s	remaining: 15s
343:	learn: 0.0012121	total: 7.83s	remaining: 14.9s
344:	learn: 0.0012121	total: 7.85s	remaining: 14.9s
345:	learn: 0.0012121	total: 7.87s	remaining: 14.9s
346:	learn: 0.0012121	total: 7.89s	remaining: 14.8s
347:	learn: 0.0012121	total: 7.91s	remaining: 14.8s
348:	learn: 0.0012121	total: 7.93s	remaining: 14.8s
349:	learn: 0.0012121	total: 7.95s	remaining: 14.8s
350:	learn: 0.0012121	total: 7.97s	remaining: 14.7s
351:	learn: 0.0012121	total: 7.99s	remaining: 14.7s
352:	learn: 0.0012121	total: 8.01s	remaining: 14.7s
353:	learn: 0.0012121	total: 8.03s	remaining: 14.7s
354:	learn: 0.0012121	total: 8.05s	remaining: 14.6s
355:	learn: 0.0012121	total: 8.07s	remaining: 14.6s
356:	learn: 0.0012121	total: 8.1s	remaining: 14.6s
357:	learn: 0.0012121	total: 8.12s	remaining: 14.6s
358:	learn: 0.0012121	total: 8.14s	remaining: 14.5s
359:	learn: 0.0012121	total: 8.16s	remaining: 14.5s
360:	learn: 0.0012121	total: 8.18s	remaining: 14.5s
361:	learn: 0.0012121	total: 8.2s	remaining: 14.5s
362:	learn: 0.0012121	total: 8.22s	remaining: 14.4s
363:	learn: 0.0012120	total: 8.24s	remaining: 14.4s
364:	learn: 0.0012120	total: 8.27s	remaining: 14.4s
365:	learn: 0.0012120	total: 8.29s	remaining: 14.4s
366:	learn: 0.0012120	total: 8.31s	remaining: 14.3s
367:	learn: 0.0012119	total: 8.33s	remaining: 14.3s
368:	learn: 0.0012119	total: 8.35s	remaining: 14.3s
369:	learn: 0.0012118	total: 8.37s	remaining: 14.3s
370:	learn: 0.0012118	total: 8.39s	remaining: 14.2s
371:	learn: 0.0012118	total: 8.41s	remaining: 14.2s
372:	learn: 0.0012118	total: 8.44s	remaining: 14.2s
373:	learn: 0.0012118	total: 8.46s	remaining: 14.2s
374:	learn: 0.0012118	total: 8.48s	remaining: 14.1s
375:	learn: 0.0012118	total: 8.5s	remaining: 14.1s
376:	learn: 0.0012118	total: 8.52s	remaining: 14.1s
377:	learn: 0.0012118	total: 8.54s	remaining: 14.1s
378:	learn: 0.0012117	total: 8.57s	remaining: 14s
379:	learn: 0.0012117	total: 8.59s	remaining: 14s
380:	learn: 0.0012117	total: 8.61s	remaining: 14s
381:	learn: 0.0012117	total: 8.63s	remaining: 14s
382:	learn: 0.0012117	total: 8.65s	remaining: 13.9s
383:	learn: 0.0012117	total: 8.67s	remaining: 13.9s
384:	learn: 0.0012110	total: 8.69s	remaining: 13.9s
385:	learn: 0.0012110	total: 8.71s	remaining: 13.9s
386:	learn: 0.0012110	total: 8.74s	remaining: 13.8s
387:	learn: 0.0012110	total: 8.76s	remaining: 13.8s
388:	learn: 0.0012110	total: 8.78s	remaining: 13.8s
389:	learn: 0.0012110	total: 8.8s	remaining: 13.8s
390:	learn: 0.0012110	total: 8.82s	remaining: 13.7s
391:	learn: 0.0012110	total: 8.84s	remaining: 13.7s
392:	learn: 0.0012110	total: 8.86s	remaining: 13.7s
393:	learn: 0.0012110	total: 8.88s	remaining: 13.7s
394:	learn: 0.0012110	total: 8.9s	remaining: 13.6s
395:	learn: 0.0012110	total: 8.92s	remaining: 13.6s
396:	learn: 0.0012110	total: 8.94s	remaining: 13.6s
397:	learn: 0.0012110	total: 8.96s	remaining: 13.6s
398:	learn: 0.0012110	total: 8.98s	remaining: 13.5s
399:	learn: 0.0012110	total: 9s	remaining: 13.5s
400:	learn: 0.0012110	total: 9.03s	remaining: 13.5s
401:	learn: 0.0012110	total: 9.05s	remaining: 13.5s
402:	learn: 0.0012110	total: 9.07s	remaining: 13.4s
403:	learn: 0.0012110	total: 9.09s	remaining: 13.4s
404:	learn: 0.0012110	total: 9.11s	remaining: 13.4s
405:	learn: 0.0012109	total: 9.13s	remaining: 13.4s
406:	learn: 0.0012109	total: 9.15s	remaining: 13.3s
407:	learn: 0.0012109	total: 9.17s	remaining: 13.3s
408:	learn: 0.0012109	total: 9.19s	remaining: 13.3s
409:	learn: 0.0012109	total: 9.22s	remaining: 13.3s
410:	learn: 0.0012109	total: 9.24s	remaining: 13.2s
411:	learn: 0.0012107	total: 9.26s	remaining: 13.2s
412:	learn: 0.0012107	total: 9.28s	remaining: 13.2s
413:	learn: 0.0012107	total: 9.3s	remaining: 13.2s
414:	learn: 0.0012107	total: 9.32s	remaining: 13.1s
415:	learn: 0.0012107	total: 9.34s	remaining: 13.1s
416:	learn: 0.0012107	total: 9.36s	remaining: 13.1s
417:	learn: 0.0012107	total: 9.38s	remaining: 13.1s
418:	learn: 0.0012107	total: 9.41s	remaining: 13s
419:	learn: 0.0012107	total: 9.43s	remaining: 13s
420:	learn: 0.0012107	total: 9.45s	remaining: 13s
421:	learn: 0.0012107	total: 9.47s	remaining: 13s
422:	learn: 0.0012107	total: 9.5s	remaining: 13s
423:	learn: 0.0012107	total: 9.52s	remaining: 12.9s
424:	learn: 0.0012107	total: 9.54s	remaining: 12.9s
425:	learn: 0.0012107	total: 9.56s	remaining: 12.9s
426:	learn: 0.0012106	total: 9.58s	remaining: 12.9s
427:	learn: 0.0012106	total: 9.6s	remaining: 12.8s
428:	learn: 0.0012106	total: 9.63s	remaining: 12.8s
429:	learn: 0.0012106	total: 9.65s	remaining: 12.8s
430:	learn: 0.0012106	total: 9.68s	remaining: 12.8s
431:	learn: 0.0012106	total: 9.7s	remaining: 12.8s
432:	learn: 0.0012106	total: 9.72s	remaining: 12.7s
433:	learn: 0.0012106	total: 9.75s	remaining: 12.7s
434:	learn: 0.0012106	total: 9.77s	remaining: 12.7s
435:	learn: 0.0012106	total: 9.79s	remaining: 12.7s
436:	learn: 0.0012106	total: 9.82s	remaining: 12.6s
437:	learn: 0.0012106	total: 9.84s	remaining: 12.6s
438:	learn: 0.0012106	total: 9.86s	remaining: 12.6s
439:	learn: 0.0012106	total: 9.88s	remaining: 12.6s
440:	learn: 0.0012106	total: 9.91s	remaining: 12.6s
441:	learn: 0.0012106	total: 9.93s	remaining: 12.5s
442:	learn: 0.0012106	total: 9.95s	remaining: 12.5s
443:	learn: 0.0012106	total: 9.97s	remaining: 12.5s
444:	learn: 0.0012106	total: 10s	remaining: 12.5s
445:	learn: 0.0012106	total: 10s	remaining: 12.4s
446:	learn: 0.0012106	total: 10s	remaining: 12.4s
447:	learn: 0.0012106	total: 10.1s	remaining: 12.4s
448:	learn: 0.0012106	total: 10.1s	remaining: 12.4s
449:	learn: 0.0012106	total: 10.1s	remaining: 12.4s
450:	learn: 0.0012106	total: 10.1s	remaining: 12.3s
451:	learn: 0.0012106	total: 10.2s	remaining: 12.3s
452:	learn: 0.0012106	total: 10.2s	remaining: 12.3s
453:	learn: 0.0012106	total: 10.2s	remaining: 12.3s
454:	learn: 0.0012106	total: 10.2s	remaining: 12.3s
455:	learn: 0.0012106	total: 10.3s	remaining: 12.2s
456:	learn: 0.0012106	total: 10.3s	remaining: 12.2s
457:	learn: 0.0012105	total: 10.3s	remaining: 12.2s
458:	learn: 0.0012105	total: 10.3s	remaining: 12.2s
459:	learn: 0.0012105	total: 10.3s	remaining: 12.1s
460:	learn: 0.0012105	total: 10.4s	remaining: 12.1s
461:	learn: 0.0012105	total: 10.4s	remaining: 12.1s
462:	learn: 0.0012105	total: 10.4s	remaining: 12.1s
463:	learn: 0.0012105	total: 10.4s	remaining: 12.1s
464:	learn: 0.0012105	total: 10.5s	remaining: 12s
465:	learn: 0.0012105	total: 10.5s	remaining: 12s
466:	learn: 0.0012105	total: 10.5s	remaining: 12s
467:	learn: 0.0012105	total: 10.5s	remaining: 12s
468:	learn: 0.0012105	total: 10.6s	remaining: 11.9s
469:	learn: 0.0012104	total: 10.6s	remaining: 11.9s
470:	learn: 0.0012104	total: 10.6s	remaining: 11.9s
471:	learn: 0.0012104	total: 10.6s	remaining: 11.9s
472:	learn: 0.0012104	total: 10.6s	remaining: 11.9s
473:	learn: 0.0012104	total: 10.7s	remaining: 11.8s
474:	learn: 0.0012104	total: 10.7s	remaining: 11.8s
475:	learn: 0.0012103	total: 10.7s	remaining: 11.8s
476:	learn: 0.0012103	total: 10.7s	remaining: 11.8s
477:	learn: 0.0012102	total: 10.8s	remaining: 11.8s
478:	learn: 0.0012102	total: 10.8s	remaining: 11.7s
479:	learn: 0.0012102	total: 10.8s	remaining: 11.7s
480:	learn: 0.0012102	total: 10.8s	remaining: 11.7s
481:	learn: 0.0012101	total: 10.8s	remaining: 11.7s
482:	learn: 0.0012101	total: 10.9s	remaining: 11.6s
483:	learn: 0.0012101	total: 10.9s	remaining: 11.6s
484:	learn: 0.0012101	total: 10.9s	remaining: 11.6s
485:	learn: 0.0012101	total: 10.9s	remaining: 11.6s
486:	learn: 0.0012101	total: 11s	remaining: 11.6s
487:	learn: 0.0012100	total: 11s	remaining: 11.5s
488:	learn: 0.0012099	total: 11s	remaining: 11.5s
489:	learn: 0.0012099	total: 11s	remaining: 11.5s
490:	learn: 0.0012099	total: 11.1s	remaining: 11.5s
491:	learn: 0.0012099	total: 11.1s	remaining: 11.4s

492:	learn: 0.0012099	total: 11.1s	remaining: 11.4s
493:	learn: 0.0012099	total: 11.1s	remaining: 11.4s
494:	learn: 0.0012098	total: 11.1s	remaining: 11.4s
495:	learn: 0.0012098	total: 11.2s	remaining: 11.3s
496:	learn: 0.0012098	total: 11.2s	remaining: 11.3s
497:	learn: 0.0012098	total: 11.2s	remaining: 11.3s
498:	learn: 0.0012098	total: 11.2s	remaining: 11.3s
499:	learn: 0.0012098	total: 11.3s	remaining: 11.3s
500:	learn: 0.0012047	total: 11.3s	remaining: 11.2s
501:	learn: 0.0012047	total: 11.3s	remaining: 11.2s
502:	learn: 0.0011974	total: 11.3s	remaining: 11.2s
503:	learn: 0.0011974	total: 11.3s	remaining: 11.2s
504:	learn: 0.0011973	total: 11.4s	remaining: 11.1s
505:	learn: 0.0011973	total: 11.4s	remaining: 11.1s
506:	learn: 0.0011973	total: 11.4s	remaining: 11.1s
507:	learn: 0.0011973	total: 11.4s	remaining: 11.1s
508:	learn: 0.0011973	total: 11.5s	remaining: 11.1s
509:	learn: 0.0011886	total: 11.5s	remaining: 11s
510:	learn: 0.0011886	total: 11.5s	remaining: 11s
511:	learn: 0.0011886	total: 11.5s	remaining: 11s
512:	learn: 0.0011886	total: 11.6s	remaining: 11s
513:	learn: 0.0011803	total: 11.6s	remaining: 11s
514:	learn: 0.0011748	total: 11.6s	remaining: 10.9s
515:	learn: 0.0011748	total: 11.6s	remaining: 10.9s
516:	learn: 0.0011664	total: 11.7s	remaining: 10.9s
517:	learn: 0.0011664	total: 11.7s	remaining: 10.9s
518:	learn: 0.0011664	total: 11.7s	remaining: 10.8s
519:	learn: 0.0011664	total: 11.7s	remaining: 10.8s
520:	learn: 0.0011664	total: 11.7s	remaining: 10.8s
521:	learn: 0.0011664	total: 11.8s	remaining: 10.8s
522:	learn: 0.0011664	total: 11.8s	remaining: 10.8s
523:	learn: 0.0011664	total: 11.8s	remaining: 10.7s
524:	learn: 0.0011566	total: 11.8s	remaining: 10.7s
525:	learn: 0.0011482	total: 11.9s	remaining: 10.7s
526:	learn: 0.0011482	total: 11.9s	remaining: 10.7s
527:	learn: 0.0011482	total: 11.9s	remaining: 10.7s
528:	learn: 0.0011481	total: 12s	remaining: 10.6s
529:	learn: 0.0011481	total: 12s	remaining: 10.6s
530:	learn: 0.0011481	total: 12s	remaining: 10.6s
531:	learn: 0.0011481	total: 12s	remaining: 10.6s
532:	learn: 0.0011481	total: 12s	remaining: 10.5s
533:	learn: 0.0011481	total: 12.1s	remaining: 10.5s
534:	learn: 0.0011481	total: 12.1s	remaining: 10.5s
535:	learn: 0.0011481	total: 12.1s	remaining: 10.5s
536:	learn: 0.0011481	total: 12.1s	remaining: 10.5s
537:	learn: 0.0011481	total: 12.1s	remaining: 10.4s
538:	learn: 0.0011481	total: 12.2s	remaining: 10.4s
539:	learn: 0.0011481	total: 12.2s	remaining: 10.4s
540:	learn: 0.0011480	total: 12.2s	remaining: 10.4s
541:	learn: 0.0011480	total: 12.2s	remaining: 10.3s
542:	learn: 0.0011480	total: 12.3s	remaining: 10.3s
543:	learn: 0.0011480	total: 12.3s	remaining: 10.3s
544:	learn: 0.0011480	total: 12.3s	remaining: 10.3s
545:	learn: 0.0011480	total: 12.3s	remaining: 10.2s
546:	learn: 0.0011480	total: 12.3s	remaining: 10.2s
547:	learn: 0.0011480	total: 12.4s	remaining: 10.2s
548:	learn: 0.0011480	total: 12.4s	remaining: 10.2s
549:	learn: 0.0011480	total: 12.4s	remaining: 10.2s
550:	learn: 0.0011480	total: 12.4s	remaining: 10.1s
551:	learn: 0.0011480	total: 12.5s	remaining: 10.1s
552:	learn: 0.0011479	total: 12.5s	remaining: 10.1s
553:	learn: 0.0011479	total: 12.5s	remaining: 10.1s
554:	learn: 0.0011479	total: 12.5s	remaining: 10s
555:	learn: 0.0011479	total: 12.6s	remaining: 10s
556:	learn: 0.0011479	total: 12.6s	remaining: 10s
557:	learn: 0.0011479	total: 12.6s	remaining: 9.98s
558:	learn: 0.0011478	total: 12.6s	remaining: 9.96s
559:	learn: 0.0011478	total: 12.6s	remaining: 9.94s
560:	learn: 0.0011478	total: 12.7s	remaining: 9.92s
561:	learn: 0.0011478	total: 12.7s	remaining: 9.89s
562:	learn: 0.0011478	total: 12.7s	remaining: 9.87s
563:	learn: 0.0011478	total: 12.7s	remaining: 9.85s
564:	learn: 0.0011478	total: 12.8s	remaining: 9.82s
565:	learn: 0.0011478	total: 12.8s	remaining: 9.8s
566:	learn: 0.0011478	total: 12.8s	remaining: 9.78s
567:	learn: 0.0011477	total: 12.8s	remaining: 9.77s
568:	learn: 0.0011477	total: 12.9s	remaining: 9.75s
569:	learn: 0.0011477	total: 12.9s	remaining: 9.73s
570:	learn: 0.0011477	total: 12.9s	remaining: 9.71s
571:	learn: 0.0011431	total: 12.9s	remaining: 9.69s
572:	learn: 0.0011431	total: 13s	remaining: 9.67s
573:	learn: 0.0011431	total: 13s	remaining: 9.64s
574:	learn: 0.0011431	total: 13s	remaining: 9.62s
575:	learn: 0.0011430	total: 13s	remaining: 9.6s
576:	learn: 0.0011430	total: 13.1s	remaining: 9.58s
577:	learn: 0.0011430	total: 13.1s	remaining: 9.55s
578:	learn: 0.0011430	total: 13.1s	remaining: 9.53s
579:	learn: 0.0011430	total: 13.1s	remaining: 9.51s
580:	learn: 0.0011430	total: 13.2s	remaining: 9.48s
581:	learn: 0.0011346	total: 13.2s	remaining: 9.46s
582:	learn: 0.0011270	total: 13.2s	remaining: 9.44s
583:	learn: 0.0011270	total: 13.2s	remaining: 9.42s
584:	learn: 0.0011270	total: 13.2s	remaining: 9.39s
585:	learn: 0.0011270	total: 13.3s	remaining: 9.37s
586:	learn: 0.0011269	total: 13.3s	remaining: 9.35s
587:	learn: 0.0011269	total: 13.3s	remaining: 9.33s
588:	learn: 0.0011269	total: 13.3s	remaining: 9.31s
589:	learn: 0.0011269	total: 13.4s	remaining: 9.31s
590:	learn: 0.0011269	total: 13.4s	remaining: 9.29s
591:	learn: 0.0011269	total: 13.4s	remaining: 9.27s
592:	learn: 0.0011269	total: 13.5s	remaining: 9.24s
593:	learn: 0.0011269	total: 13.5s	remaining: 9.22s
594:	learn: 0.0011269	total: 13.5s	remaining: 9.2s
595:	learn: 0.0011269	total: 13.5s	remaining: 9.18s
596:	learn: 0.0011269	total: 13.6s	remaining: 9.16s
597:	learn: 0.0011269	total: 13.6s	remaining: 9.14s
598:	learn: 0.0011269	total: 13.6s	remaining: 9.11s
599:	learn: 0.0011269	total: 13.6s	remaining: 9.09s
600:	learn: 0.0011269	total: 13.7s	remaining: 9.07s
601:	learn: 0.0011269	total: 13.7s	remaining: 9.05s
602:	learn: 0.0011269	total: 13.7s	remaining: 9.02s
603:	learn: 0.0011269	total: 13.7s	remaining: 9s
604:	learn: 0.0011269	total: 13.8s	remaining: 8.98s
605:	learn: 0.0011269	total: 13.8s	remaining: 8.95s
606:	learn: 0.0011268	total: 13.8s	remaining: 8.93s
607:	learn: 0.0011267	total: 13.8s	remaining: 8.91s
608:	learn: 0.0011267	total: 13.8s	remaining: 8.89s
609:	learn: 0.0011267	total: 13.9s	remaining: 8.86s
610:	learn: 0.0011267	total: 13.9s	remaining: 8.84s
611:	learn: 0.0011267	total: 13.9s	remaining: 8.82s
612:	learn: 0.0011267	total: 13.9s	remaining: 8.8s
613:	learn: 0.0011267	total: 14s	remaining: 8.78s
614:	learn: 0.0011267	total: 14s	remaining: 8.75s
615:	learn: 0.0011267	total: 14s	remaining: 8.73s
616:	learn: 0.0011267	total: 14s	remaining: 8.71s
617:	learn: 0.0011244	total: 14.1s	remaining: 8.69s
618:	learn: 0.0011244	total: 14.1s	remaining: 8.66s
619:	learn: 0.0011244	total: 14.1s	remaining: 8.64s
620:	learn: 0.0011243	total: 14.1s	remaining: 8.62s
621:	learn: 0.0011243	total: 14.1s	remaining: 8.59s
622:	learn: 0.0011243	total: 14.2s	remaining: 8.57s
623:	learn: 0.0011243	total: 14.2s	remaining: 8.55s
624:	learn: 0.0011243	total: 14.2s	remaining: 8.52s
625:	learn: 0.0011243	total: 14.2s	remaining: 8.5s
626:	learn: 0.0011243	total: 14.3s	remaining: 8.48s
627:	learn: 0.0011243	total: 14.3s	remaining: 8.46s
628:	learn: 0.0011243	total: 14.3s	remaining: 8.43s
629:	learn: 0.0011243	total: 14.3s	remaining: 8.41s
630:	learn: 0.0011243	total: 14.3s	remaining: 8.38s
631:	learn: 0.0011242	total: 14.4s	remaining: 8.36s
632:	learn: 0.0011242	total: 14.4s	remaining: 8.34s
633:	learn: 0.0011242	total: 14.4s	remaining: 8.32s
634:	learn: 0.0011242	total: 14.4s	remaining: 8.29s
635:	learn: 0.0011242	total: 14.5s	remaining: 8.27s
636:	learn: 0.0011242	total: 14.5s	remaining: 8.25s
637:	learn: 0.0011242	total: 14.5s	remaining: 8.23s
638:	learn: 0.0011205	total: 14.5s	remaining: 8.2s
639:	learn: 0.0011205	total: 14.5s	remaining: 8.18s
640:	learn: 0.0011205	total: 14.6s	remaining: 8.16s
641:	learn: 0.0011204	total: 14.6s	remaining: 8.13s
642:	learn: 0.0011204	total: 14.6s	remaining: 8.11s
643:	learn: 0.0011202	total: 14.6s	remaining: 8.09s
644:	learn: 0.0011202	total: 14.7s	remaining: 8.07s
645:	learn: 0.0011202	total: 14.7s	remaining: 8.04s
646:	learn: 0.0011201	total: 14.7s	remaining: 8.02s
647:	learn: 0.0011199	total: 14.7s	remaining: 8s
648:	learn: 0.0011199	total: 14.7s	remaining: 7.97s
649:	learn: 0.0011199	total: 14.8s	remaining: 7.95s
650:	learn: 0.0011199	total: 14.8s	remaining: 7.92s
651:	learn: 0.0011199	total: 14.8s	remaining: 7.9s
652:	learn: 0.0011199	total: 14.8s	remaining: 7.88s
653:	learn: 0.0011199	total: 14.9s	remaining: 7.86s

654:	learn: 0.0011199	total: 14.9s	remaining: 7.83s
655:	learn: 0.0011198	total: 14.9s	remaining: 7.81s
656:	learn: 0.0011198	total: 14.9s	remaining: 7.79s
657:	learn: 0.0011198	total: 14.9s	remaining: 7.76s
658:	learn: 0.0011198	total: 15s	remaining: 7.74s
659:	learn: 0.0011198	total: 15s	remaining: 7.72s
660:	learn: 0.0011198	total: 15s	remaining: 7.7s
661:	learn: 0.0011198	total: 15s	remaining: 7.67s
662:	learn: 0.0011198	total: 15s	remaining: 7.65s
663:	learn: 0.0011198	total: 15.1s	remaining: 7.63s
664:	learn: 0.0011198	total: 15.1s	remaining: 7.6s
665:	learn: 0.0011198	total: 15.1s	remaining: 7.58s
666:	learn: 0.0011198	total: 15.1s	remaining: 7.56s
667:	learn: 0.0011198	total: 15.2s	remaining: 7.54s
668:	learn: 0.0011198	total: 15.2s	remaining: 7.52s
669:	learn: 0.0011197	total: 15.2s	remaining: 7.5s
670:	learn: 0.0011197	total: 15.2s	remaining: 7.47s
671:	learn: 0.0011197	total: 15.3s	remaining: 7.45s
672:	learn: 0.0011197	total: 15.3s	remaining: 7.43s
673:	learn: 0.0011197	total: 15.3s	remaining: 7.41s
674:	learn: 0.0011197	total: 15.3s	remaining: 7.38s
675:	learn: 0.0011196	total: 15.4s	remaining: 7.36s
676:	learn: 0.0011196	total: 15.4s	remaining: 7.34s
677:	learn: 0.0011196	total: 15.4s	remaining: 7.32s
678:	learn: 0.0011196	total: 15.4s	remaining: 7.29s
679:	learn: 0.0011196	total: 15.4s	remaining: 7.27s
680:	learn: 0.0011196	total: 15.5s	remaining: 7.25s
681:	learn: 0.0011196	total: 15.5s	remaining: 7.22s
682:	learn: 0.0011195	total: 15.5s	remaining: 7.2s
683:	learn: 0.0011153	total: 15.5s	remaining: 7.18s
684:	learn: 0.0011153	total: 15.6s	remaining: 7.15s
685:	learn: 0.0011153	total: 15.6s	remaining: 7.13s
686:	learn: 0.0011152	total: 15.6s	remaining: 7.11s
687:	learn: 0.0011152	total: 15.6s	remaining: 7.08s
688:	learn: 0.0011152	total: 15.6s	remaining: 7.06s
689:	learn: 0.0011152	total: 15.7s	remaining: 7.04s
690:	learn: 0.0011152	total: 15.7s	remaining: 7.01s
691:	learn: 0.0011152	total: 15.7s	remaining: 6.99s
692:	learn: 0.0011151	total: 15.7s	remaining: 6.97s
693:	learn: 0.0011151	total: 15.8s	remaining: 6.95s
694:	learn: 0.0011151	total: 15.8s	remaining: 6.92s
695:	learn: 0.0011151	total: 15.8s	remaining: 6.9s
696:	learn: 0.0011151	total: 15.8s	remaining: 6.87s
697:	learn: 0.0011151	total: 15.8s	remaining: 6.85s
698:	learn: 0.0011151	total: 15.9s	remaining: 6.83s
699:	learn: 0.0011151	total: 15.9s	remaining: 6.8s
700:	learn: 0.0011150	total: 15.9s	remaining: 6.78s
701:	learn: 0.0011150	total: 15.9s	remaining: 6.76s
702:	learn: 0.0011150	total: 15.9s	remaining: 6.73s
703:	learn: 0.0011150	total: 16s	remaining: 6.71s
704:	learn: 0.0011150	total: 16s	remaining: 6.69s
705:	learn: 0.0011150	total: 16s	remaining: 6.66s
706:	learn: 0.0011150	total: 16s	remaining: 6.64s
707:	learn: 0.0011150	total: 16s	remaining: 6.62s
708:	learn: 0.0011150	total: 16.1s	remaining: 6.59s
709:	learn: 0.0011150	total: 16.1s	remaining: 6.57s
710:	learn: 0.0011150	total: 16.1s	remaining: 6.55s
711:	learn: 0.0011070	total: 16.1s	remaining: 6.52s
712:	learn: 0.0011068	total: 16.1s	remaining: 6.5s
713:	learn: 0.0011068	total: 16.2s	remaining: 6.48s
714:	learn: 0.0011068	total: 16.2s	remaining: 6.45s
715:	learn: 0.0011068	total: 16.2s	remaining: 6.43s
716:	learn: 0.0011068	total: 16.2s	remaining: 6.41s
717:	learn: 0.0011068	total: 16.3s	remaining: 6.38s
718:	learn: 0.0011068	total: 16.3s	remaining: 6.36s
719:	learn: 0.0011068	total: 16.3s	remaining: 6.34s
720:	learn: 0.0011068	total: 16.3s	remaining: 6.32s
721:	learn: 0.0010991	total: 16.3s	remaining: 6.29s
722:	learn: 0.0010991	total: 16.4s	remaining: 6.27s
723:	learn: 0.0010991	total: 16.4s	remaining: 6.25s
724:	learn: 0.0010991	total: 16.4s	remaining: 6.23s
725:	learn: 0.0010991	total: 16.4s	remaining: 6.2s
726:	learn: 0.0010991	total: 16.5s	remaining: 6.18s
727:	learn: 0.0010991	total: 16.5s	remaining: 6.16s
728:	learn: 0.0010991	total: 16.5s	remaining: 6.14s
729:	learn: 0.0010991	total: 16.5s	remaining: 6.11s
730:	learn: 0.0010991	total: 16.6s	remaining: 6.09s
731:	learn: 0.0010990	total: 16.6s	remaining: 6.07s
732:	learn: 0.0010990	total: 16.6s	remaining: 6.05s
733:	learn: 0.0010990	total: 16.6s	remaining: 6.02s
734:	learn: 0.0010990	total: 16.6s	remaining: 6s
735:	learn: 0.0010990	total: 16.7s	remaining: 5.98s
736:	learn: 0.0010990	total: 16.7s	remaining: 5.96s
737:	learn: 0.0010990	total: 16.7s	remaining: 5.93s
738:	learn: 0.0010990	total: 16.7s	remaining: 5.91s
739:	learn: 0.0010989	total: 16.8s	remaining: 5.89s
740:	learn: 0.0010989	total: 16.8s	remaining: 5.87s
741:	learn: 0.0010989	total: 16.8s	remaining: 5.84s
742:	learn: 0.0010989	total: 16.8s	remaining: 5.82s
743:	learn: 0.0010989	total: 16.9s	remaining: 5.8s
744:	learn: 0.0010989	total: 16.9s	remaining: 5.78s
745:	learn: 0.0010988	total: 16.9s	remaining: 5.75s
746:	learn: 0.0010988	total: 16.9s	remaining: 5.73s
747:	learn: 0.0010988	total: 16.9s	remaining: 5.71s
748:	learn: 0.0010951	total: 17s	remaining: 5.68s
749:	learn: 0.0010951	total: 17s	remaining: 5.66s
750:	learn: 0.0010951	total: 17s	remaining: 5.64s
751:	learn: 0.0010951	total: 17s	remaining: 5.62s
752:	learn: 0.0010951	total: 17s	remaining: 5.59s
753:	learn: 0.0010879	total: 17.1s	remaining: 5.57s
754:	learn: 0.0010828	total: 17.1s	remaining: 5.55s
755:	learn: 0.0010828	total: 17.1s	remaining: 5.52s
756:	learn: 0.0010828	total: 17.1s	remaining: 5.5s
757:	learn: 0.0010828	total: 17.2s	remaining: 5.48s
758:	learn: 0.0010828	total: 17.2s	remaining: 5.46s
759:	learn: 0.0010828	total: 17.2s	remaining: 5.43s
760:	learn: 0.0010828	total: 17.2s	remaining: 5.41s
761:	learn: 0.0010828	total: 17.2s	remaining: 5.39s
762:	learn: 0.0010828	total: 17.3s	remaining: 5.36s
763:	learn: 0.0010828	total: 17.3s	remaining: 5.34s
764:	learn: 0.0010828	total: 17.3s	remaining: 5.32s
765:	learn: 0.0010828	total: 17.3s	remaining: 5.3s
766:	learn: 0.0010827	total: 17.4s	remaining: 5.27s
767:	learn: 0.0010826	total: 17.4s	remaining: 5.25s
768:	learn: 0.0010826	total: 17.4s	remaining: 5.23s
769:	learn: 0.0010826	total: 17.4s	remaining: 5.21s
770:	learn: 0.0010826	total: 17.4s	remaining: 5.18s
771:	learn: 0.0010826	total: 17.5s	remaining: 5.16s
772:	learn: 0.0010825	total: 17.5s	remaining: 5.14s
773:	learn: 0.0010825	total: 17.5s	remaining: 5.11s
774:	learn: 0.0010825	total: 17.5s	remaining: 5.09s
775:	learn: 0.0010758	total: 17.6s	remaining: 5.07s
776:	learn: 0.0010758	total: 17.6s	remaining: 5.04s
777:	learn: 0.0010758	total: 17.6s	remaining: 5.02s
778:	learn: 0.0010758	total: 17.6s	remaining: 5s
779:	learn: 0.0010758	total: 17.6s	remaining: 4.98s
780:	learn: 0.0010758	total: 17.7s	remaining: 4.95s
781:	learn: 0.0010758	total: 17.7s	remaining: 4.93s
782:	learn: 0.0010758	total: 17.7s	remaining: 4.91s
783:	learn: 0.0010758	total: 17.7s	remaining: 4.88s
784:	learn: 0.0010758	total: 17.8s	remaining: 4.86s
785:	learn: 0.0010758	total: 17.8s	remaining: 4.84s
786:	learn: 0.0010758	total: 17.8s	remaining: 4.82s
787:	learn: 0.0010758	total: 17.8s	remaining: 4.79s
788:	learn: 0.0010758	total: 17.8s	remaining: 4.77s
789:	learn: 0.0010758	total: 17.9s	remaining: 4.75s
790:	learn: 0.0010758	total: 17.9s	remaining: 4.73s
791:	learn: 0.0010757	total: 17.9s	remaining: 4.7s
792:	learn: 0.0010757	total: 17.9s	remaining: 4.68s
793:	learn: 0.0010757	total: 18s	remaining: 4.66s
794:	learn: 0.0010757	total: 18s	remaining: 4.64s
795:	learn: 0.0010757	total: 18s	remaining: 4.62s
796:	learn: 0.0010757	total: 18s	remaining: 4.59s
797:	learn: 0.0010757	total: 18.1s	remaining: 4.57s
798:	learn: 0.0010757	total: 18.1s	remaining: 4.55s
799:	learn: 0.0010757	total: 18.1s	remaining: 4.53s
800:	learn: 0.0010756	total: 18.1s	remaining: 4.5s
801:	learn: 0.0010756	total: 18.1s	remaining: 4.48s
802:	learn: 0.0010756	total: 18.2s	remaining: 4.46s
803:	learn: 0.0010756	total: 18.2s	remaining: 4.43s
804:	learn: 0.0010756	total: 18.2s	remaining: 4.41s
805:	learn: 0.0010756	total: 18.2s	remaining: 4.39s
806:	learn: 0.0010756	total: 18.3s	remaining: 4.37s
807:	learn: 0.0010756	total: 18.3s	remaining: 4.34s
808:	learn: 0.0010756	total: 18.3s	remaining: 4.32s
809:	learn: 0.0010756	total: 18.3s	remaining: 4.3s
810:	learn: 0.0010756	total: 18.3s	remaining: 4.28s
811:	learn: 0.0010756	total: 18.4s	remaining: 4.25s
812:	learn: 0.0010691	total: 18.4s	remaining: 4.23s

813:	learn: 0.0010691	total: 18.4s	remaining: 4.21s
814:	learn: 0.0010691	total: 18.4s	remaining: 4.18s
815:	learn: 0.0010690	total: 18.5s	remaining: 4.16s
816:	learn: 0.0010690	total: 18.5s	remaining: 4.14s
817:	learn: 0.0010690	total: 18.5s	remaining: 4.12s
818:	learn: 0.0010690	total: 18.5s	remaining: 4.09s
819:	learn: 0.0010690	total: 18.5s	remaining: 4.07s
820:	learn: 0.0010690	total: 18.6s	remaining: 4.05s
821:	learn: 0.0010689	total: 18.6s	remaining: 4.03s
822:	learn: 0.0010689	total: 18.6s	remaining: 4s
823:	learn: 0.0010689	total: 18.6s	remaining: 3.98s
824:	learn: 0.0010689	total: 18.7s	remaining: 3.96s
825:	learn: 0.0010689	total: 18.7s	remaining: 3.94s
826:	learn: 0.0010689	total: 18.7s	remaining: 3.92s
827:	learn: 0.0010689	total: 18.7s	remaining: 3.89s
828:	learn: 0.0010689	total: 18.8s	remaining: 3.87s
829:	learn: 0.0010689	total: 18.8s	remaining: 3.85s
830:	learn: 0.0010667	total: 18.8s	remaining: 3.82s
831:	learn: 0.0010667	total: 18.8s	remaining: 3.8s
832:	learn: 0.0010667	total: 18.9s	remaining: 3.78s
833:	learn: 0.0010666	total: 18.9s	remaining: 3.76s
834:	learn: 0.0010666	total: 18.9s	remaining: 3.73s
835:	learn: 0.0010666	total: 18.9s	remaining: 3.71s
836:	learn: 0.0010666	total: 18.9s	remaining: 3.69s
837:	learn: 0.0010666	total: 19s	remaining: 3.66s
838:	learn: 0.0010666	total: 19s	remaining: 3.64s
839:	learn: 0.0010666	total: 19s	remaining: 3.62s
840:	learn: 0.0010666	total: 19s	remaining: 3.6s
841:	learn: 0.0010666	total: 19s	remaining: 3.57s
842:	learn: 0.0010666	total: 19.1s	remaining: 3.55s
843:	learn: 0.0010666	total: 19.1s	remaining: 3.53s
844:	learn: 0.0010666	total: 19.1s	remaining: 3.5s
845:	learn: 0.0010646	total: 19.1s	remaining: 3.48s
846:	learn: 0.0010646	total: 19.1s	remaining: 3.46s
847:	learn: 0.0010646	total: 19.2s	remaining: 3.44s
848:	learn: 0.0010646	total: 19.2s	remaining: 3.41s
849:	learn: 0.0010646	total: 19.2s	remaining: 3.39s
850:	learn: 0.0010646	total: 19.2s	remaining: 3.37s
851:	learn: 0.0010646	total: 19.3s	remaining: 3.34s
852:	learn: 0.0010646	total: 19.3s	remaining: 3.32s
853:	learn: 0.0010646	total: 19.3s	remaining: 3.3s
854:	learn: 0.0010646	total: 19.3s	remaining: 3.28s
855:	learn: 0.0010646	total: 19.3s	remaining: 3.25s
856:	learn: 0.0010646	total: 19.4s	remaining: 3.23s
857:	learn: 0.0010646	total: 19.4s	remaining: 3.21s
858:	learn: 0.0010646	total: 19.4s	remaining: 3.19s
859:	learn: 0.0010646	total: 19.4s	remaining: 3.16s
860:	learn: 0.0010646	total: 19.4s	remaining: 3.14s
861:	learn: 0.0010646	total: 19.5s	remaining: 3.12s
862:	learn: 0.0010646	total: 19.5s	remaining: 3.09s
863:	learn: 0.0010646	total: 19.5s	remaining: 3.07s
864:	learn: 0.0010646	total: 19.5s	remaining: 3.05s
865:	learn: 0.0010646	total: 19.6s	remaining: 3.02s
866:	learn: 0.0010645	total: 19.6s	remaining: 3s
867:	learn: 0.0010645	total: 19.6s	remaining: 2.98s
868:	learn: 0.0010645	total: 19.6s	remaining: 2.96s
869:	learn: 0.0010645	total: 19.6s	remaining: 2.93s
870:	learn: 0.0010645	total: 19.7s	remaining: 2.91s
871:	learn: 0.0010645	total: 19.7s	remaining: 2.89s
872:	learn: 0.0010645	total: 19.7s	remaining: 2.87s
873:	learn: 0.0010645	total: 19.7s	remaining: 2.84s
874:	learn: 0.0010645	total: 19.8s	remaining: 2.82s
875:	learn: 0.0010645	total: 19.8s	remaining: 2.8s
876:	learn: 0.0010645	total: 19.8s	remaining: 2.78s
877:	learn: 0.0010644	total: 19.8s	remaining: 2.75s
878:	learn: 0.0010644	total: 19.8s	remaining: 2.73s
879:	learn: 0.0010644	total: 19.9s	remaining: 2.71s
880:	learn: 0.0010643	total: 19.9s	remaining: 2.69s
881:	learn: 0.0010643	total: 19.9s	remaining: 2.66s
882:	learn: 0.0010643	total: 19.9s	remaining: 2.64s
883:	learn: 0.0010643	total: 20s	remaining: 2.62s
884:	learn: 0.0010643	total: 20s	remaining: 2.6s
885:	learn: 0.0010643	total: 20s	remaining: 2.57s
886:	learn: 0.0010643	total: 20s	remaining: 2.55s
887:	learn: 0.0010643	total: 20s	remaining: 2.53s
888:	learn: 0.0010643	total: 20.1s	remaining: 2.5s
889:	learn: 0.0010643	total: 20.1s	remaining: 2.48s
890:	learn: 0.0010643	total: 20.1s	remaining: 2.46s
891:	learn: 0.0010642	total: 20.1s	remaining: 2.44s
892:	learn: 0.0010642	total: 20.2s	remaining: 2.41s
893:	learn: 0.0010642	total: 20.2s	remaining: 2.39s
894:	learn: 0.0010642	total: 20.2s	remaining: 2.37s
895:	learn: 0.0010643	total: 20.2s	remaining: 2.35s
896:	learn: 0.0010643	total: 20.2s	remaining: 2.32s
897:	learn: 0.0010643	total: 20.3s	remaining: 2.3s
898:	learn: 0.0010643	total: 20.3s	remaining: 2.28s
899:	learn: 0.0010642	total: 20.3s	remaining: 2.26s
900:	learn: 0.0010642	total: 20.3s	remaining: 2.23s
901:	learn: 0.0010642	total: 20.4s	remaining: 2.21s
902:	learn: 0.0010642	total: 20.4s	remaining: 2.19s
903:	learn: 0.0010642	total: 20.4s	remaining: 2.17s
904:	learn: 0.0010642	total: 20.4s	remaining: 2.14s
905:	learn: 0.0010642	total: 20.4s	remaining: 2.12s
906:	learn: 0.0010642	total: 20.5s	remaining: 2.1s
907:	learn: 0.0010642	total: 20.5s	remaining: 2.07s
908:	learn: 0.0010642	total: 20.5s	remaining: 2.05s
909:	learn: 0.0010642	total: 20.5s	remaining: 2.03s
910:	learn: 0.0010642	total: 20.5s	remaining: 2.01s
911:	learn: 0.0010642	total: 20.6s	remaining: 1.98s
912:	learn: 0.0010642	total: 20.6s	remaining: 1.96s
913:	learn: 0.0010642	total: 20.6s	remaining: 1.94s
914:	learn: 0.0010642	total: 20.6s	remaining: 1.92s
915:	learn: 0.0010642	total: 20.6s	remaining: 1.89s
916:	learn: 0.0010642	total: 20.7s	remaining: 1.87s
917:	learn: 0.0010642	total: 20.7s	remaining: 1.85s
918:	learn: 0.0010642	total: 20.7s	remaining: 1.82s
919:	learn: 0.0010641	total: 20.7s	remaining: 1.8s
920:	learn: 0.0010641	total: 20.8s	remaining: 1.78s
921:	learn: 0.0010641	total: 20.8s	remaining: 1.76s
922:	learn: 0.0010641	total: 20.8s	remaining: 1.74s
923:	learn: 0.0010641	total: 20.8s	remaining: 1.71s
924:	learn: 0.0010641	total: 20.8s	remaining: 1.69s
925:	learn: 0.0010641	total: 20.9s	remaining: 1.67s
926:	learn: 0.0010641	total: 20.9s	remaining: 1.64s
927:	learn: 0.0010641	total: 20.9s	remaining: 1.62s
928:	learn: 0.0010641	total: 20.9s	remaining: 1.6s
929:	learn: 0.0010641	total: 20.9s	remaining: 1.58s
930:	learn: 0.0010640	total: 21s	remaining: 1.55s
931:	learn: 0.0010640	total: 21s	remaining: 1.53s
932:	learn: 0.0010640	total: 21s	remaining: 1.51s
933:	learn: 0.0010640	total: 21s	remaining: 1.49s
934:	learn: 0.0010640	total: 21.1s	remaining: 1.46s
935:	learn: 0.0010639	total: 21.1s	remaining: 1.44s
936:	learn: 0.0010639	total: 21.1s	remaining: 1.42s
937:	learn: 0.0010639	total: 21.1s	remaining: 1.4s
938:	learn: 0.0010639	total: 21.1s	remaining: 1.37s
939:	learn: 0.0010639	total: 21.2s	remaining: 1.35s
940:	learn: 0.0010638	total: 21.2s	remaining: 1.33s
941:	learn: 0.0010638	total: 21.2s	remaining: 1.3s
942:	learn: 0.0010638	total: 21.2s	remaining: 1.28s
943:	learn: 0.0010638	total: 21.2s	remaining: 1.26s
944:	learn: 0.0010638	total: 21.3s	remaining: 1.24s
945:	learn: 0.0010638	total: 21.3s	remaining: 1.22s
946:	learn: 0.0010638	total: 21.3s	remaining: 1.19s
947:	learn: 0.0010638	total: 21.3s	remaining: 1.17s
948:	learn: 0.0010638	total: 21.4s	remaining: 1.15s
949:	learn: 0.0010638	total: 21.4s	remaining: 1.13s
950:	learn: 0.0010638	total: 21.4s	remaining: 1.1s
951:	learn: 0.0010638	total: 21.4s	remaining: 1.08s
952:	learn: 0.0010637	total: 21.4s	remaining: 1.06s
953:	learn: 0.0010637	total: 21.5s	remaining: 1.03s
954:	learn: 0.0010637	total: 21.5s	remaining: 1.01s
955:	learn: 0.0010637	total: 21.5s	remaining: 990ms
956:	learn: 0.0010637	total: 21.5s	remaining: 968ms
957:	learn: 0.0010637	total: 21.6s	remaining: 945ms
958:	learn: 0.0010637	total: 21.6s	remaining: 922ms
959:	learn: 0.0010637	total: 21.6s	remaining: 900ms
960:	learn: 0.0010637	total: 21.6s	remaining: 877ms
961:	learn: 0.0010637	total: 21.6s	remaining: 855ms
962:	learn: 0.0010637	total: 21.7s	remaining: 832ms
963:	learn: 0.0010636	total: 21.7s	remaining: 810ms
964:	learn: 0.0010636	total: 21.7s	remaining: 787ms
965:	learn: 0.0010636	total: 21.7s	remaining: 765ms
966:	learn: 0.0010636	total: 21.7s	remaining: 742ms
967:	learn: 0.0010636	total: 21.8s	remaining: 720ms
968:	learn: 0.0010636	total: 21.8s	remaining: 697ms
969:	learn: 0.0010635	total: 21.8s	remaining: 675ms
970:	learn: 0.0010635	total: 21.8s	remaining: 652ms
971:	learn: 0.0010635	total: 21.9s	remaining: 630ms
972:	learn: 0.0010635	total: 21.9s	remaining: 607ms
973:	learn: 0.0010635	total: 21.9s	remaining: 585ms
974:	learn: 0.0010635	total: 21.9s	remaining: 562ms

975:	learn: 0.0010635	total: 21.9s	remaining: 540ms
976:	learn: 0.0010635	total: 22s	remaining: 517ms
977:	learn: 0.0010635	total: 22s	remaining: 495ms
978:	learn: 0.0010635	total: 22s	remaining: 472ms
979:	learn: 0.0010635	total: 22s	remaining: 450ms
980:	learn: 0.0010635	total: 22.1s	remaining: 427ms
981:	learn: 0.0010634	total: 22.1s	remaining: 405ms
982:	learn: 0.0010634	total: 22.1s	remaining: 382ms
983:	learn: 0.0010634	total: 22.1s	remaining: 360ms
984:	learn: 0.0010634	total: 22.1s	remaining: 337ms
985:	learn: 0.0010634	total: 22.2s	remaining: 315ms
986:	learn: 0.0010634	total: 22.2s	remaining: 292ms
987:	learn: 0.0010634	total: 22.2s	remaining: 270ms
988:	learn: 0.0010634	total: 22.2s	remaining: 247ms
989:	learn: 0.0010634	total: 22.2s	remaining: 225ms
990:	learn: 0.0010634	total: 22.3s	remaining: 202ms
991:	learn: 0.0010634	total: 22.3s	remaining: 180ms
992:	learn: 0.0010634	total: 22.3s	remaining: 157ms
993:	learn: 0.0010634	total: 22.3s	remaining: 135ms
994:	learn: 0.0010634	total: 22.4s	remaining: 112ms
995:	learn: 0.0010634	total: 22.4s	remaining: 89.8ms
996:	learn: 0.0010633	total: 22.4s	remaining: 67.4ms
997:	learn: 0.0010633	total: 22.4s	remaining: 44.9ms
998:	learn: 0.0010633	total: 22.4s	remaining: 22.5ms
999:	learn: 0.0010633	total: 22.5s	remaining: 0us

In [33]:
df = pd.read_csv('Test_Dataset.csv')
df

,EmployeeID,Age,TravelProfile,Department,HomeToWork,EducationField,Gender,HourlnWeek,Involvement,WorkLifeBalance,...,JobSatisfaction,ESOPs,NumCompaniesWorked,OverTime,SalaryHikelastYear,WorkExperience,LastPromotion,CurrentProfile,MaritalStatus,MonthlyIncome
0,6110001,18.0,No,NaN,9.0,CA,Male,80.0,3,2,...,3,1,1,0,17.0,0.0,0.0,0.0,Single,16904.0
1,6110002,20.0,Rarely,Analytics,28.0,Statistics,Female,59.0,1,3,...,1,1,2,1,18.0,2.0,1.0,NaN,Single,18994.0
2,6110003,50.0,Rarely,Analytics,19.0,CA,Female,76.0,3,3,...,5,0,5,1,22.0,18.0,3.0,3.0,M,18587.0
3,6110004,32.0,Rarely,Sales,23.0,Statistics,Female,73.0,5,2,...,3,0,4,1,17.0,5.0,3.0,3.0,Married,20559.0
4,6110005,39.0,Rarely,Analytics,7.0,CA,Male,42.0,4,1,...,5,1,4,0,20.0,9.0,1.0,7.0,Married,24991.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2625,6112626,46.0,Rarely,Sales,12.0,Marketing Diploma,Male,76.0,3,5,...,5,1,5,1,18.0,10.0,1.0,3.0,Married,26761.0
2626,6112627,29.0,Rarely,Analytics,22.0,CA,Male,80.0,4,4,...,5,0,2,0,18.0,7.0,4.0,4.0,Divorsed,19196.0
2627,6112628,44.0,Rarely,Analytics,8.0,CA,F,42.0,4,1,...,1,1,3,0,19.0,24.0,5.0,17.0,Married,25248.0
2628,6112629,NaN,Rarely,Analytics,11.0,Statistics,Female,NaN,4,3,...,4,0,2,0,18.0,2.0,1.0,1.0,Single,17261.0
2629,6112630,50.0,Yes,Analytics,1.0,Statistics,F,73.0,3,4,...,4,1,3,1,24.0,28.0,0.0,7.0,Married,33172.0

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2630 entries, 0 to 2629
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   EmployeeID          2630 non-null   int64
 1   Age                 2488 non-null   float64
 2   TravelProfile       2630 non-null   object
 3   Department          2572 non-null   object
 4   HomeToWork          2504 non-null   float64
 5   EducationField      2630 non-null   object
 6   Gender              2600 non-null   object
 7   HourlnWeek          2494 non-null   float64
 8   Involvement         2630 non-null   int64
 9   WorkLifeBalance     2630 non-null   int64
 10  Designation         2600 non-null   object
 11  JobSatisfaction     2630 non-null   int64
 12  ESOPs               2630 non-null   int64
 13  NumCompaniesWorked  2630 non-null   int64
 14  OverTime            2630 non-null   int64
 15  SalaryHikelastYear  2536 non-null   float64
 16  WorkExperience      2508 non-null   float64
 17  LastPromotion       2573 non-null   float64
 18  CurrentProfile      2496 non-null   float64
 19  MaritalStatus       2630 non-null   object
 20  MonthlyIncome       2597 non-null   float64
dtypes: float64(8), int64(7), object(6)
memory usage: 431.6+ KB

In [35]:
df.isnull().sum()

EmployeeID              0
Age                   142
TravelProfile           0
Department             58
HomeToWork            126
EducationField          0
Gender                 30
HourlnWeek            136
Involvement             0
WorkLifeBalance         0
Designation            30
JobSatisfaction         0
ESOPs                   0
NumCompaniesWorked      0
OverTime                0
SalaryHikelastYear     94
WorkExperience        122
LastPromotion          57
CurrentProfile        134
MaritalStatus           0
MonthlyIncome          33
dtype: int64

In [36]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Department'].fillna(df['Department'].value_counts().index[0],inplace=True)
df['HomeToWork'].fillna(df['HomeToWork'].mean(),inplace=True)
df['Gender'].fillna(df['Gender'].value_counts().index[0],inplace=True)
df['HourlnWeek'].fillna(df['HourlnWeek'].mean(),inplace=True)
df['Designation'].fillna(df['Designation'].value_counts().index[0],inplace=True)
df['SalaryHikelastYear'].fillna(df['SalaryHikelastYear'].mean(),inplace=True)
df['WorkExperience'].fillna(df['WorkExperience'].mean(),inplace=True)
df['LastPromotion'].fillna(df['LastPromotion'].mean(),inplace=True)
df['CurrentProfile'].fillna(df['CurrentProfile'].mean(),inplace=True)
df['MonthlyIncome'].fillna(df['MonthlyIncome'].mean(),inplace=True)

In [37]:
df.isnull().sum()

EmployeeID            0
Age                   0
TravelProfile         0
Department            0
HomeToWork            0
EducationField        0
Gender                0
HourlnWeek            0
Involvement           0
WorkLifeBalance       0
Designation           0
JobSatisfaction       0
ESOPs                 0
NumCompaniesWorked    0
OverTime              0
SalaryHikelastYear    0
WorkExperience        0
LastPromotion         0
CurrentProfile        0
MaritalStatus         0
MonthlyIncome         0
dtype: int64

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2630 entries, 0 to 2629
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   EmployeeID          2630 non-null   int64
 1   Age                 2630 non-null   float64
 2   TravelProfile       2630 non-null   object
 3   Department          2630 non-null   object
 4   HomeToWork          2630 non-null   float64
 5   EducationField      2630 non-null   object
 6   Gender              2630 non-null   object
 7   HourlnWeek          2630 non-null   float64
 8   Involvement         2630 non-null   int64
 9   WorkLifeBalance     2630 non-null   int64
 10  Designation         2630 non-null   object
 11  JobSatisfaction     2630 non-null   int64
 12  ESOPs               2630 non-null   int64
 13  NumCompaniesWorked  2630 non-null   int64
 14  OverTime            2630 non-null   int64
 15  SalaryHikelastYear  2630 non-null   float64
 16  WorkExperience      2630 non-null   float64
 17  LastPromotion       2630 non-null   float64
 18  CurrentProfile      2630 non-null   float64
 19  MaritalStatus       2630 non-null   object
 20  MonthlyIncome       2630 non-null   float64
dtypes: float64(8), int64(7), object(6)
memory usage: 431.6+ KB

In [39]:
df = pd.get_dummies(df,drop_first=True)
df

,EmployeeID,Age,HomeToWork,HourlnWeek,Involvement,WorkLifeBalance,JobSatisfaction,ESOPs,NumCompaniesWorked,OverTime,...,EducationField_Statistics,Gender_Female,Gender_Male,Designation_Executive,Designation_Manager,Designation_Senior Manager,Designation_VP,MaritalStatus_M,MaritalStatus_Married,MaritalStatus_Single
0,6110001,18.000000,9.0,80.000000,3,2,3,1,1,0,...,0,0,1,1,0,0,0,0,0,1
1,6110002,20.000000,28.0,59.000000,1,3,1,1,2,1,...,1,1,0,1,0,0,0,0,0,1
2,6110003,50.000000,19.0,76.000000,3,3,5,0,5,1,...,0,1,0,1,0,0,0,1,0,0
3,6110004,32.000000,23.0,73.000000,5,2,3,0,4,1,...,1,1,0,0,1,0,0,0,1,0
4,6110005,39.000000,7.0,42.000000,4,1,5,1,4,0,...,0,0,1,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2625,6112626,46.000000,12.0,76.000000,3,5,5,1,5,1,...,0,0,1,0,0,1,0,0,1,0
2626,6112627,29.000000,22.0,80.000000,4,4,5,0,2,0,...,0,0,1,1,0,0,0,0,0,0
2627,6112628,44.000000,8.0,42.000000,4,1,1,1,3,0,...,0,0,0,0,0,1,0,0,1,0
2628,6112629,37.425643,11.0,57.863272,4,3,4,0,2,0,...,1,1,0,1,0,0,0,0,0,1
2629,6112630,50.000000,1.0,73.000000,3,4,4,1,3,1,...,1,0,0,0,0,0,1,0,1,0

In [40]:
df['Attrition'] = model.predict(df.drop('EmployeeID',axis=1))
df

,EmployeeID,Age,HomeToWork,HourlnWeek,Involvement,WorkLifeBalance,JobSatisfaction,ESOPs,NumCompaniesWorked,OverTime,...,Gender_Female,Gender_Male,Designation_Executive,Designation_Manager,Designation_Senior Manager,Designation_VP,MaritalStatus_M,MaritalStatus_Married,MaritalStatus_Single,Attrition
0,6110001,18.000000,9.0,80.000000,3,2,3,1,1,0,...,0,1,1,0,0,0,0,0,1,1.0
1,6110002,20.000000,28.0,59.000000,1,3,1,1,2,1,...,1,0,1,0,0,0,0,0,1,0.0
2,6110003,50.000000,19.0,76.000000,3,3,5,0,5,1,...,1,0,1,0,0,0,1,0,0,0.0
3,6110004,32.000000,23.0,73.000000,5,2,3,0,4,1,...,1,0,0,1,0,0,0,1,0,1.0
4,6110005,39.000000,7.0,42.000000,4,1,5,1,4,0,...,0,1,0,0,1,0,0,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2625,6112626,46.000000,12.0,76.000000,3,5,5,1,5,1,...,0,1,0,0,1,0,0,1,0,0.0
2626,6112627,29.000000,22.0,80.000000,4,4,5,0,2,0,...,0,1,1,0,0,0,0,0,0,0.0
2627,6112628,44.000000,8.0,42.000000,4,1,1,1,3,0,...,0,0,0,0,1,0,0,1,0,0.0
2628,6112629,37.425643,11.0,57.863272,4,3,4,0,2,0,...,1,0,1,0,0,0,0,0,1,1.0
2629,6112630,50.000000,1.0,73.000000,3,4,4,1,3,1,...,0,0,0,0,0,1,0,1,0,0.0

In [41]:
df2=df[['EmployeeID','Attrition']]
df2['EmployeeID'] = df2['EmployeeID'].astype('int64')
df2['Attrition'] = df2['Attrition'].astype('int64')
df2

<ipython-input-41-6a5a3b235e5b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['EmployeeID'] = df2['EmployeeID'].astype('int64')
<ipython-input-41-6a5a3b235e5b>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Attrition'] = df2['Attrition'].astype('int64')

      EmployeeID  Attrition
0        6110001          1
1        6110002          0
2        6110003          0
3        6110004          1
4        6110005          0
...          ...        ...
2625     6112626          0
2626     6112627          0
2627     6112628          0
2628     6112629          1
2629     6112630          0

[2630 rows x 2 columns]

In [42]:
df = pd.read_csv('Test_Dataset.csv')
df

,EmployeeID,Age,TravelProfile,Department,HomeToWork,EducationField,Gender,HourlnWeek,Involvement,WorkLifeBalance,...,JobSatisfaction,ESOPs,NumCompaniesWorked,OverTime,SalaryHikelastYear,WorkExperience,LastPromotion,CurrentProfile,MaritalStatus,MonthlyIncome
0,6110001,18.0,No,NaN,9.0,CA,Male,80.0,3,2,...,3,1,1,0,17.0,0.0,0.0,0.0,Single,16904.0
1,6110002,20.0,Rarely,Analytics,28.0,Statistics,Female,59.0,1,3,...,1,1,2,1,18.0,2.0,1.0,NaN,Single,18994.0
2,6110003,50.0,Rarely,Analytics,19.0,CA,Female,76.0,3,3,...,5,0,5,1,22.0,18.0,3.0,3.0,M,18587.0
3,6110004,32.0,Rarely,Sales,23.0,Statistics,Female,73.0,5,2,...,3,0,4,1,17.0,5.0,3.0,3.0,Married,20559.0
4,6110005,39.0,Rarely,Analytics,7.0,CA,Male,42.0,4,1,...,5,1,4,0,20.0,9.0,1.0,7.0,Married,24991.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2625,6112626,46.0,Rarely,Sales,12.0,Marketing Diploma,Male,76.0,3,5,...,5,1,5,1,18.0,10.0,1.0,3.0,Married,26761.0
2626,6112627,29.0,Rarely,Analytics,22.0,CA,Male,80.0,4,4,...,5,0,2,0,18.0,7.0,4.0,4.0,Divorsed,19196.0
2627,6112628,44.0,Rarely,Analytics,8.0,CA,F,42.0,4,1,...,1,1,3,0,19.0,24.0,5.0,17.0,Married,25248.0
2628,6112629,NaN,Rarely,Analytics,11.0,Statistics,Female,NaN,4,3,...,4,0,2,0,18.0,2.0,1.0,1.0,Single,17261.0
2629,6112630,50.0,Yes,Analytics,1.0,Statistics,F,73.0,3,4,...,4,1,3,1,24.0,28.0,0.0,7.0,Married,33172.0

In [43]:
df2['EmployeeID'] = df['EmployeeID']
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2630 entries, 0 to 2629
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  2630 non-null   int64
 1   Attrition   2630 non-null   int64
dtypes: int64(2)
memory usage: 41.2 KB

<ipython-input-43-ede409ad4317>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['EmployeeID'] = df['EmployeeID']

In [44]:
df2.to_csv('file1.csv',index=0)